### ISSUE TITLE
[BUG] SfFilter with SfColor - click on checkbox is not working

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#1000]
**Describe the bug**
When you use SfFilter with SfColors on the mobile view (passing color as a prop), checked is not working when you click on the checkbox. Instead, click on SfColor tile works fine. 

**How to reproduce**
1. Go to 'Category'
2. Click on 'Filters' with mobile view
3. Open Accordion with Colors
4. Try to click on the checkbox and see nothing happens

**Expected behavior**
Click on the checkbox and on SfColor tile should work.

**Comment by pspaczek** [comment]
@martaradziszewska you should use `:label` to set `id` and `for` :) 
We should add some fallback for that case when the label is empty. 
But this is the case for all inputs :)

**Comment by dimasch** [comment]
@martaradziszewska Maybe need use the `change` event name, instead `click`. This is helped me.
