### ISSUE TITLE
[BUG] SfPagination lacks design and story case for mobile view

### ISSUE THREAD

**Issue by Qrzy** [DivanteLtd/storefront-ui#1001]
`SfPagination` component in design is not even considered for mobile view.   
In example category page it's explicitly set with `desktop-only` class which hides it in mobile devices, suggesting that there should be some other control for paged content of the products listing.

There should be at least a guideline for the case of mobile devices.   
As discussed internally, infinite scroll is not a good choice for that, especially due to poor UX.

**Comment by mbaran-dvnt** [comment]
Done :)
