### ISSUE TITLE
[A11y compliance] - SfBanner - the text looks great until resizing

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#101]
SfBanner - the text looks great until resizing
<img width="847" alt="Screen Shot 2019-05-24 at 9 11 43" src="https://user-images.githubusercontent.com/6650139/58309877-0335a500-7e0e-11e9-808a-3062d55b14a9.png">

**Comment by filrak** [comment]
@mayashavin can you split it into multiple issues so people can pick granular ones?

**Comment by mayashavin** [comment]
@filrak Sure

**Comment by filrak** [comment]
I believe we fixed it ;)
