### ISSUE TITLE
[DESIGN] SfColorPicker with more than 6 colors

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#1016]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

How SfColorPicker should look like when there are more colors than 6 like in the design?
![image](https://user-images.githubusercontent.com/34887212/78988532-78e35600-7b31-11ea-900f-8cda2441b0fd.png)
![image](https://user-images.githubusercontent.com/34887212/78988599-aaf4b800-7b31-11ea-8509-c10a2a03d356.png)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-19 o 21 33 23](https://user-images.githubusercontent.com/62093203/79697856-68478400-8285-11ea-9451-d829c9911250.png)
 
Done:)
