### ISSUE TITLE
[FEATURE] Quantity Selector Slot for Product Card

### ISSUE THREAD

**Issue by regenrek** [DivanteLtd/storefront-ui#1019]
Hi,

maybe I'm missing something here but it would be nice to use the Quantity Selector inside a Product Card Component to quick choose products on category view.

Like on `danonedirect.ru`

![image](https://user-images.githubusercontent.com/5182020/79127571-6b80d280-7da2-11ea-9771-7686c7a4c8d4.png)

**Comment by aniamusial** [comment]
Thank you for your FR @regenrek :) So far you can use slots to put quantity selector in there and code it. @mbaran-dvnt can we add a view with SfQuantitySelector to the designs? IMO this can be a common case.

**Comment by regenrek** [comment]
In terms of capybara theme it's currently a bit problematic since capybara is using `storefront-ui 0.6.0` but you need to `0.7.0` to use SfQuantitySelector with its buttons. (And if I upgrade to 0.7.0 the theme breaks somehow). 

> So far you can use slots to put quantity selector in there and code it

Unfortunately, there is not an appropriate slot for it. Additionally, you need a `add to cart` button which basically `SfAddToCart`can be.  So I've adjusted

`SfProductCard`  with a new slot (which i basically took from `CollectedProduct.vue`) and added

``` 
    <slot name="input">
      <SfAddToCartExt v-model="qty" @click="changeQuantity" />
    </slot>
```

**Hierarchy:**

``` 
-- SfProductCardExt (develop branch)
---- SfAddToCartExt (develop branch)
------ `SfQuantitySelectorExt (develop branch)
```

**Remains over**

- How to handle events on changing quantity. Probably in SfProductCard
- Styles
- Use AddToCart Icon (and replace Add To Card) from SfProductCard (so they don't interfere)

**Comment by filrak** [comment]
@mbaran-dvnt :)

**Comment by mbaran-dvnt** [comment]
Designs added only for desktop as on mobile add to cart on PLP has a modal with quantity and other options.
