### ISSUE TITLE
[Update] Adjust SfPrice styling for special price

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#102]
![image](https://user-images.githubusercontent.com/15185752/58339533-1a928380-7e4a-11e9-8c9b-afa629d409e1.png)
Adjust designs for special price (crossed out and new one) in SfPrice according to figma designs (Product Listing board)

https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0

**Comment by lauragift21** [comment]
I'll work on this :)

**Comment by lauragift21** [comment]
Is it okay to close this since it's already merged in? @filrak

**Comment by filrak** [comment]
yup ;)
