### ISSUE TITLE
[FEATURE][CHECKOUT] Personal details view for logged-in user

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/storefront-ui#1025]
## Concept
When the user is already logged in, he can still go to the Personal Details step. He's allowed to change his name and surname same as in MyAccount page (with the same result - he's changing account settings).
We need design and view implementation to allow that.

## Acceptance criteria
- [ ] design is created for this step when the user is already logged in
- [ ] design is consulted before implementation, to ensure use-cases coverage
- [ ] create a composition of step in a storybook, with created designs and flow for logged-in user

## Context: Current personal details step:
![image](https://user-images.githubusercontent.com/13100280/79211913-22cf2500-7e47-11ea-8300-f83a68c88d7c.png)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-23 o 22 38 12](https://user-images.githubusercontent.com/62093203/80147028-1ec3a580-85b3-11ea-8c00-9d7488d59b88.png)

Good call guys!

**Comment by patzick** [comment]
@mbaran-dvnt designs for this step meets the acceptance needs, thanks
just would modify this area a bit

![image](https://user-images.githubusercontent.com/13100280/80208313-37be6c00-8630-11ea-9180-31d9eb05e493.png)

* user is already logged in so doesn't need to know advantages of his account :)
* go back button - get dig of him or turn to "go back to shopping" or something like this if you think it's necessary

Thanks :)

**Comment by mbaran-dvnt** [comment]
Done.

Marcin Baran
Senior Product Designer
[image: Phone number] +48 792 197 444
[image: Phone number] www.divante.com
<https://divante.com/ecommerce-trends?utm_source=footer&utm_medium=email&utm_campaign=footer>
[image: Phone number] Follow us on: [image: LinkedIn]
<https://www.linkedin.com/company/divanteltd/>[image: Twitter]
<https://twitter.com/DivanteLTD>[image: Facebook]
<https://www.facebook.com/DivanteCareer/>[image: Dribbble]
<https://dribbble.com/divante?utm_source=footer&utm_medium=email&utm_campaign=footer>[image:
Instagram] <https://www.instagram.com/divante_com/>
Visit us in: Wrocław | Berlin | New York | Singapore
[image: banner]
<https://divante.com/career?utm_source=footer&utm_medium=email&utm_campaign=footer>
Divante Sp. z o.o., Dmowskiego 17, 50-203 Wrocław, VAT ID 8951930748, KRS
(register) No. 0000313348, share capital 58 000 PLN.

**Comment by patzick** [comment]
@mbaran-dvnt cool, that closes our issue, thanks :)

@pspaczek you can plan to implement this on storybook but it probably will be another issue as all components from this design are already available so we can implement this by ourselves :)
