### ISSUE TITLE
[FEATURE][Checkout] Address management for logged-in user

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/storefront-ui#1026]
## Concept
When the user is logged in he should be able to pick one of his existing addresses, edit one of them and mark as default (for shipping or payment).

### Proposition of solution
I believe Allegro has a nice example of address management and my recommendation would be to follow that pattern.

## Acceptance criteria
- [ ] the user has a list of his available addresses
- [ ] possibility to chose address marked as default shipping/billing (if any exist)
- [ ] adding a new address to the list
- [ ] possibility to edit any address from the list
- [ ] possibility to mark the address as default shipping/billing
- [ ] all above easily possible in mobile view
- [ ] implementation of it in storybook for shipping and payment steps

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-23 o 22 39 53](https://user-images.githubusercontent.com/62093203/80147158-5af70600-85b3-11ea-98e6-6b058896c9e3.png)

Let me know if that works for you guys

**Comment by patzick** [comment]
@mbaran-dvnt as for acceptance criteria regarding designs fo this task 
✅   the user has a list of his available addresses
✅  possibility to chose address marked as default shipping/billing (if any exist)
✅  adding a new address to the list
❌  possibility to edit any address from the list
❌  possibility to mark the address as default shipping/billing
❌  all above easily possible in mobile view

**Comment by mbaran-dvnt** [comment]
Hi guys,

I've made a few changes.

I think that possibility to edit any address from the list is the same as adding a new address. While adding a new address user should have the possibility to save that address in his account list. And also the possibility to change the already existing address is in "My Account". 

![Zrzut ekranu 2020-04-25 o 14 59 39](https://user-images.githubusercontent.com/62093203/80280605-64908300-8705-11ea-9e4d-e2f420cdec25.png)
