### ISSUE TITLE
[FEATURE][My Account] Address management in MyAccount

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/storefront-ui#1028]
## Concept
In MyAccount there is a "Shipping details" section, which is misleading as it may contain both shipping and billing addresses. User cannot see from the list which address is default shipping and which default billing nor switch defaults there.

The related task for address management: #1026, would be nice to reuse these components.

## Acceptance Criteria
- [ ] User sees from the list which address is his default shipping and default billing address (can be the same address or can be different ones)
- [ ] user can mark address on list ad default shipping/billing
- [ ] during address edition or adding new one user can mark defaults as well
- [ ] all above easily handled in mobile view
- [ ] implementation in storybook

### Additionally
- [ ] storybook menu shows something like "My Addresses" instead of "Shipping details"

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-25 o 14 36 07](https://user-images.githubusercontent.com/62093203/80280091-1af26900-8702-11ea-8cc0-6df896dfa11c.png)

Take a look, I think that it should work. By clicking "edit" you will be able to edit those addresses.
