### ISSUE TITLE
[BUG] MegaMenu confusing on theme

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/storefront-ui#1029]
## Description
related: https://github.com/DivanteLtd/shopware-pwa/pull/593

During our first implementation, there is a problem with recognizing where megamenu is and where the template is. 

![image](https://user-images.githubusercontent.com/13100280/79220280-fff73d80-7e53-11ea-8ef8-51f8770a986d.png)

on Figma, there is a grey overlay with megamenu, so there is one more issue how to show properly more top-level categories without subcategories

## Acceptance criteria
- [ ] add overlay area to mega menu
- [ ] [DESIGNS] add instructions to what is the proper way to show an example from the screenshot and in case that only some of the categories contain subcategories (@mbaran-dvnt )
- [ ] Above example with a larger number of categories and still place for banners from Figma designs

**Comment by mbaran-dvnt** [comment]
Ok, I think I understand what's the issue. 

First of all - the background overlay to the mega menu is in the Figma designs:

![Zrzut ekranu 2020-04-25 o 15 19 46](https://user-images.githubusercontent.com/62093203/80280983-33658200-8708-11ea-8747-81a2eb9c588f.png)

Secondly, the MegaMenu in the designs is one of the options of mega menus available.
In cases as you showed, You should use one of those two:

![Zrzut ekranu 2020-04-25 o 15 24 08](https://user-images.githubusercontent.com/62093203/80281053-d0c0b600-8708-11ea-9c33-9d2a15d23768.png)

I suggest the first one as the names are really long. So on white are you'll have categories, and on grey one, you can have even one column os subcategories.

Let me know if that's clear. If you are confused we can make a call on Monday so i will try to explain it better or make a quick wireframed design.
