### ISSUE TITLE
[Mobile / Desktop ] Implement SfCollectedProduct

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#103]
![image](https://user-images.githubusercontent.com/15185752/58341929-b246a080-7e4f-11e9-91e3-2d98adf9e713.png)
![image](https://user-images.githubusercontent.com/15185752/58341941-bbd00880-7e4f-11e9-8dce-b42431311ae1.png)
![image](https://user-images.githubusercontent.com/15185752/58342005-e15d1200-7e4f-11e9-9b82-ee8025401a5c.png)
Used in checkout, wishlist, cart.

As you can see it differs in every context (mostly elements at the bottom) so instead of fulfilling every use case we should just provide a slot in there.

Please notice that width is not fixed and image size differs depending on the size of the container.

FIRST Please propose API similar to SfProductCard and after discussing API and agreeing on it we can start implementing this component.

**Comment by mayashavin** [comment]
I'll take it :)

**Comment by leomp12** [comment]
If you need help, I would like to help with this API discussion :)

**Comment by filrak** [comment]
Maya on the 1st screen there is quantity, I think we can make it look like in the rest

**Comment by mayashavin** [comment]
@filrak I remember you said something about this component is postponed due to design, am I right? Can I start working on it?

**Comment by filrak** [comment]
yup, Actually I think we can go with this version and use it everywhere in the app if thats possible
![image](https://user-images.githubusercontent.com/15185752/61864736-3c53c980-aed2-11e9-9a69-9afd5c4c0165.png)
![image](https://user-images.githubusercontent.com/15185752/61864903-98b6e900-aed2-11e9-8c09-9c294e6683d0.png)

**Comment by filrak** [comment]
The only thing that I thnk we can change in mobile design is replacing "remove from cart" with 'x' on top right corner (just a black x) wdyt?

**Comment by mayashavin** [comment]
@filrak should be fine, is it the first design (with x)?

**Comment by filrak** [comment]
Update:
 price/name/count should be via props but content at the bottom should be a slot
