### ISSUE TITLE
[FEATURE] SfImage <img srcset> support

### ISSUE THREAD

**Issue by EugeneHlushko** [DivanteLtd/storefront-ui#1042]
**Describe how this feature will help us improve**
Retina

**Is your proposal related to a problem?**
`<img` should support rendering an `srcset` attribute here if passed as a string: https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/components/atoms/SfImage/SfImage.vue#L14

**Describe the solution you'd considered**
a prop `srcset` of type string for <img use case, allow to pass custom mq instead of pixel values to be able to target for pixel density MQs when using picture.

**Comment by CthulhuDev** [comment]
I think the whole component should be re-thinked to be data-driven.
Imho it should support also more sources in the picture tag, based on the array of data that you pass as a prop.

**Comment by theomanus** [comment]
I think that shopware won't add the webp format in their media manager. You can achieve that via 3rd party plugin, but then you still have the problem that this "extra" format won't be available via  the store-api.

**Comment by Rigo-m** [comment]
@theomanus this thread is for the storefront-ui implementation, not for  shopware-pwa
