### ISSUE TITLE
[FEATURE] update Lozad

### ISSUE THREAD

**Issue by bkarlson** [DivanteLtd/storefront-ui#1048]
Hi, 
The current lozad.js version is 1.14.0, but in SF is still @ 1.9.0. 
Quite a few fixed since then:
https://github.com/ApoorvSaxena/lozad.js/commits/master

In addition, it would be nice to pass options prop to lozad.js via `SfImage`, at least `rootMargin` would be useful. 

Cheers!

**Comment by pspaczek** [comment]
@bkarlson thank you, we 1.9.0 lozad.js now on development.
@AdamPawlinski please add `rootMargin` and `threshold` props for lozad.js to SfImage
