### ISSUE TITLE
[BUG] SfIcon misses badge 

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#1061]
**Describe the bug**
There is no badge visible on SfHeader for cart icon.

**How to reproduce**
1. Go to Header
2. Add some value to cartItemsQty
3. See error

**Expected behavior**
A badge appears.

**Actual behavior**
Nothing happend.

**Comment by martaradziszewska** [comment]
related https://github.com/DivanteLtd/storefront-ui/pull/1021
