### ISSUE TITLE
[BUG][a11y] Voiceover: some SfButton texts are read out incorrectly

### ISSUE THREAD

**Issue by Qrzy** [DivanteLtd/storefront-ui#1070]
As reported here: https://github.com/DivanteLtd/next/issues/391 the `Add to cart` button on list view is read incorrectly by screen reader (as 'A D D to cart' instead of 'Add to cart').
Is there anything that should be added to the button to avoid such issue?

**Comment by pspaczek** [comment]
@Qrzy with screen reader do you use? When I use PL lang then they reed A D D but when I change it to EN everything sounds good

**Comment by pspaczek** [comment]
tested by ChoromeVox :)

**Comment by Qrzy** [comment]
Indeed, it seems to be an issue of a screen reader. Thank you for pointing that out!
