### ISSUE TITLE
[BUG] SfCircleIcon is not always circular

### ISSUE THREAD

**Issue by Michal-Dziedzinski** [DivanteLtd/storefront-ui#1087]
**Describe the bug**
SfCircleIcon does not always have a round shape. 

**How to reproduce**
1. Go to  https://a43ad4c11ce49ceb9fd580194df218d0fe72a2b3.shopware-pwa.preview.storefrontcloud.io
2. Click on filter or cart
3. See SfCircleIcon  which is squered

**Expected behavior**
SfCircleIcon should always have a circular shape

**Actual behavior**
Locally it has a round shape, while after deploy it has a square shape

**Screenshots**
Locally: 
![image](https://user-images.githubusercontent.com/32803679/79746269-ff561f80-8309-11ea-936c-ea5db997b2ba.png)

Deployed:
![image](https://user-images.githubusercontent.com/32803679/79746423-46dcab80-830a-11ea-9956-c2006f0337e5.png)

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome 80.0.3987.163

**Comment by pspaczek** [comment]
fixed in 0.7.2
