### ISSUE TITLE
[A11y Compliance] SfAlert - Alert background and font color don't have enough contrastivity

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#109]
SfAlert - alert background and the text color don't have enough contrastivity.
<img width="761" alt="Screen Shot 2019-05-24 at 9 09 57" src="https://user-images.githubusercontent.com/6650139/58309878-0335a500-7e0e-11e9-9a40-533a8101949c.png">

**Comment by filrak** [comment]
New colors are ready to be applied now :)
![image](https://user-images.githubusercontent.com/15185752/58431649-0ac7a900-80af-11e9-98fc-81eb4517096a.png)

**Comment by mayashavin** [comment]
@filrak Still not good enough. I just tested the contrast ratio of blue and red, one is 1.28 and one is 2.18 respectively (too low compared to 4.5 as max)
<img width="196" alt="Screen Shot 2019-05-27 at 19 47 26" src="https://user-images.githubusercontent.com/6650139/58431882-84b06000-80b8-11e9-8396-d67b7953acb7.png">
<img width="192" alt="Screen Shot 2019-05-27 at 19 48 23" src="https://user-images.githubusercontent.com/6650139/58431883-8548f680-80b8-11e9-9f7e-5dcdcedd3966.png">

**Comment by filrak** [comment]
Ok so we're waiting for another Svieta's try :)

**Comment by filrak** [comment]
Now it's ready ^^ 
![image](https://user-images.githubusercontent.com/15185752/58461806-cda3fb00-8130-11e9-863c-d22d0ff029f7.png)
