### ISSUE TITLE
[FEATURE] SfInput type tel add validation for numbers 

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1094]
**Describe how this feature will help us improve**
Adding validation for numbers to input type=tel would improve user experience 

**Is your proposal related to a problem?**
input allows typing any kind of character

**Describe the solution you'd considered**
add validation and test it on  every browser

**Comment by pspaczek** [comment]
thank you @AdamPawlinski but IMO it's a part of Vue app, it's not our responsibility :)
