### ISSUE TITLE
[FEATURE] Add bordered version of SfInput

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#1106]
**Describe how this feature will help us improve**
Pretty common case in many projects.

**Is your proposal related to a problem?**
No.
**Describe the solution you'd considered**
We should have a UI version of bordered input with different helper texts.

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-25 o 23 39 43](https://user-images.githubusercontent.com/62093203/80291471-0b007680-874e-11ea-8915-b006017561b8.png)

There you go:)
