### ISSUE TITLE
[BUG] Cannot set height of Divider to be less than 2px

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#1108]
**Describe the bug**
Due to hr tag properties, it is impossible to set Divider height smaller than 2px.

**Expected behavior**
In many projects dividers can be smaller/bigger than the default 2px value. We should add a possibility to set it with prop.

**Solution**
Instead of border, use height property and set border to 0.

**Comment by pspaczek** [comment]
you can use --divider-border-width to set height less than 2px, tested on chrome and safari
![Zrzut ekranu 2020-04-28 o 09 14 52](https://user-images.githubusercontent.com/12138170/80458237-c84ac400-8930-11ea-8434-1903c475d21e.png)
