### ISSUE TITLE
[FEATURE] SfColorPicker with more colors 

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#1114]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 
We need to have a more consistent layout regarding color picker with colors - when we click on the button, the container should appear from the "button" position - so, when the button is on the left the container should appear from the left corner as well. Wdyt @mbaran-dvnt ?

![image](https://user-images.githubusercontent.com/34887212/80368466-1908e100-888d-11ea-87c5-76ddbcdc077a.png)

**Is your proposal related to a problem?**
#1012

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-27 o 21 52 47](https://user-images.githubusercontent.com/62093203/80414510-7030a500-88d1-11ea-8a38-4c4413157196.png)

Fixed;)

**Comment by martaradziszewska** [comment]
@mbaran-dvnt  thank you!
