### ISSUE TITLE
sf-button--unstyled

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#1116]
with a lot of components, we used a button instead of .sf-button.
1. add sf-button--unstyled to remove button styles
2. replace button to sf-button with sf-button--unstyled
3. remove v-focus from components where you improve these changes

**Comment by martaradziszewska** [comment]
@pspaczek maybe `sf-button--pure` / or `sf-button--standard`, wdyt ?

**Comment by pspaczek** [comment]
pure sound better, standards sound like primary or default

**Comment by filrak** [comment]
`unstyled` is most descriptive but can you give some use cases for the usage of this class?

**Comment by martaradziszewska** [comment]
It is used when SfButton contains SfIcon and we have to remove padding/background properties. Instead of writing repeated styles, we can use a modifier.
