### ISSUE TITLE
[Mobile] SfBanner button disappears and all texts are pushed to the left side

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#112]
On Desktop:
<img width="1438" alt="Screen Shot 2019-05-25 at 22 53 08" src="https://user-images.githubusercontent.com/6650139/58374062-0b8dfd00-7f40-11e9-89e6-5d68d5b58c28.png">

On Small screen:
<img width="874" alt="Screen Shot 2019-05-25 at 22 53 01" src="https://user-images.githubusercontent.com/6650139/58374066-12b50b00-7f40-11e9-9eec-d229528c89bd.png">

Button disappeared. All texts are pushed to the left side.
Should have an option for placing the texts and button location (maybe?)

**Comment by filrak** [comment]
It's actually a feature according to designs :D

**Comment by filrak** [comment]
I'm keeping it open since the photo is not properly aligned anyway
