### ISSUE TITLE
[FEATURE] [design] SfLanguageSelector 

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#1124]
**Describe how this feature will help us improve**
How should SfLanguageSelector look when it's open?

![image](https://user-images.githubusercontent.com/34887212/80473959-271b3800-8947-11ea-8482-a2544f4c496a.png)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-29 o 12 14 28](https://user-images.githubusercontent.com/62093203/80585073-fa345700-8a12-11ea-830e-d25bd4b6d9bf.png)

There you go:)

**Comment by pspaczek** [comment]
@mbaran-dvnt IMO when you support just a few languages like EN, PL, DE it's too big. And the more important thing. You ad another modal to our design. Can we base on our components? 
![Zrzut ekranu 2020-05-4 o 12 06 08](https://user-images.githubusercontent.com/12138170/80955463-a608e880-8dff-11ea-966e-5db69b997793.png)
