### ISSUE TITLE
[Refactor] replace all <component is> for link and <a> to SfLink

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#1125]
you can find it for example on SfProductCart, begin at line 3

**Comment by bkarlson** [comment]
This was kinda breaking change, as now it seems impossible to get rid of <a> tag around SfImage in SfProductCardHorizontal, and it leads to side-effects in a situation when SfImage slot is used or handles a custom click event.

@martaradziszewska , can you address this please, as there's no workaround apart from downgrade.

Possible solution would be not rendering SfLink if null is passed (and make it default prop value).
