### ISSUE TITLE
[FEATURE] [design] SfHeader navigation items

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#1126]
**Describe how this feature will help us improve**
How Navigation should look like with more than 2 categories? 

![image](https://user-images.githubusercontent.com/34887212/80497853-4a57de80-896b-11ea-9b43-fd97d2244251.png)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-29 o 12 18 28](https://user-images.githubusercontent.com/62093203/80585384-89416f00-8a13-11ea-9c0f-6fb7ead20381.png)

Basically this is something optional. We can add the most popular categories there or anything that is crucial for the company. Main / Normal navigation is available from Bottom Nav Menu Icon.
