### ISSUE TITLE
[FEATURE] Page size selector for pagination

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#1138]
**Describe how this feature will help us improve**
It is very common that users want to change page size on the paginated list. 

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:
  - building page size select component base on `SfSelect`
- add the possibility/modifier for select to change the direction of the dropdown list (on the top)

![image](https://user-images.githubusercontent.com/34887212/80689034-067cea80-8acd-11ea-8c8d-48cca138779c.png)
![image](https://user-images.githubusercontent.com/34887212/80689056-0bda3500-8acd-11ea-9c1d-40a78631b267.png)

**Comment by pspaczek** [comment]
@martaradziszewska IMO it should be SfSelect, outside SfPagination component.

**Comment by martaradziszewska** [comment]
@pspaczek you're right, I changed the description :)

**Comment by martaradziszewska** [comment]
Since you requested for this feature, I am referring to you directly :) This component can be done based on SfSelect. You can pass there your page size options and invoke a method on value changed - I think you should have everything that you need to create such a version. This looks exactly like SfSelect so there is no need to create another component. If you need we can prepare some story showing the example of using :) Please let me know
