### ISSUE TITLE
[ Desktop / Mobile ] Implement SfCarousel

### ISSUE THREAD

**Issue by przspa** [DivanteLtd/storefront-ui#117]
Desktop
![Carousel](https://user-images.githubusercontent.com/12138170/58425717-d0541100-809a-11e9-90aa-b056e95a3175.png)

Mobile
![Carousel_Mobile](https://user-images.githubusercontent.com/12138170/58426116-ed3d1400-809b-11e9-9946-7ed518518fef.png)

Can be found [designe ](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0 )for Product Page

Proposed API

```
<SfCarousel per-page="2">
   <!-- default slot -->
   <SfCarouselItem><!-- slot content --></SfCarouselItem>
   <SfCarouselItem><!-- slot content --></SfCarouselItem>
   <SfCarouselItem><!-- slot content --></SfCarouselItem>
</SfSelect>
```
Use [Glidejs](https://github.com/glidejs/glide)

**Comment by leomp12** [comment]
Merged
