### ISSUE TITLE
[BUG]Product Page - hardly visible arrows in the carousel

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/storefront-ui#1172]
**Describe the bug**
In the 'You may also like section' there are hardly visible arrows in the carousel

**How to reproduce**
1. go to any product page
2.  scroll down the 'you may also like' section
3. see the error
 
**Expected behavior**
The arrows should be large enough to be visible to the user

**Actual behavior**
The arrows are hardly visible to the user

**Screenshots**
<img width="685" alt="PParrows" src="https://user-images.githubusercontent.com/57936972/81539620-c93c1680-9370-11ea-8123-98ff9386a274.png">

**Devices (please complete the following information):**
 all

**Comment by pspaczek** [comment]
thanks @akrajna it should be fixed at #1154
before:
![Zrzut ekranu 2020-05-11 o 12 23 12](https://user-images.githubusercontent.com/12138170/81551484-386e3680-9382-11ea-8c2f-0ec433c997f7.png) 
after:
![Zrzut ekranu 2020-05-11 o 12 20 43](https://user-images.githubusercontent.com/12138170/81551494-3c01bd80-9382-11ea-8a0b-92800f746daf.png)

**Comment by akrajna** [comment]
More visible arrows are not implemented yet on https://shopware-pwa.storefrontcloud.io/ The arrows are already done in UI storybook
