### ISSUE TITLE
[BUG]Product Page - illegible inscription 'size'

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/storefront-ui#1173]
**Describe the bug**
On product page after selecting size, the inscription 'size' is written in too small font and is therefore illegible.

**How to reproduce**
1. go to any product page
2. select any size
3. see the error

**Expected behavior**
The inscription 'size' should be written in such a font size that it is readable by the user
**Actual behavior**
The inscription 'size' is written in too small font and is therefore hardly readable.

**Screenshots**
<img width="678" alt="PPsize" src="https://user-images.githubusercontent.com/57936972/81540533-15d42180-9372-11ea-8908-705e38ff79e3.png">

**Devices (please complete the following information):**
all

**Comment by martaradziszewska** [comment]
@akrajna @patzick  I see here two options that can be done:
- you can add a label before this select by your own without passing a label to SfSelect,
- we can add a slot with label outside of the select or some modifier, wdyt @pspaczek ?

**Comment by AdamPawlinski** [comment]
@martaradziszewska is it possible to add just another property like this: --select-is-selected-label-font-size, or is it bad idea, wdyt?

**Comment by patzick** [comment]
We have two separate things here
### first thing - the label size is too small,
I see there's a 10px there and I agree with @akrajna - it's illegible, even in Checkout and so on. 
This is how it looks like:
![image](https://user-images.githubusercontent.com/13100280/82020990-6d340380-968a-11ea-8dc7-a666bc5e6d93.png)
this is how it probably should 
![image](https://user-images.githubusercontent.com/13100280/82021033-8472f100-968a-11ea-8342-382da3439b13.png)

### second thing - size label in theme
to make it consistent we should place a `Size` as @martaradziszewska suggested - before select same as `Color` label

## Action points
- [ ] SFUI team - change label size in inputs from 10px to 12px (cc @pspaczek @mbaran-dvnt )
- [ ] @akrajna create an issue in shopware-pwa repo for creating label in same way as for colour
