### ISSUE TITLE
[BUG] Always stick to exact same version in vue and shared packages

### ISSUE THREAD

**Issue by psmyrek** [DivanteLtd/storefront-ui#1176]
**Describe the bug**
Lack of fixed version for `@storefront-ui/shared`  dependency inside `package.json` of `@storefront-ui/vue` package is causing that every time new release is made, the latest version of "shared" package is used even if in our project we are sticked to fixed versioning, i.e. `0.7.8`.

**How to reproduce**
1. Initialize new (empty) project and create `package.json` with dependency to `@storefront-ui/vue` `0.7.8` - without `^`.
2. Run `npm install`.
3. Error: the `@storefront-ui/vue` is installed as requested with version `0.7.8`, but `@storefront-ui/shared` is in the latest available version that do not match the "vue" package. At the time of writing this issue the "shared" package is installed in `0.7.10`.

**Expected behavior**
The `@storefront-ui/shared` version must always match the `@storefront-ui/vue` version. The `^` must be removed from `package.json` for `@storefront-ui/shared` dependency.

**Actual behavior**
The `@storefront-ui/vue` is installed with requested version, but `@storefront-ui/shared` is in the latest version that do not match the "vue" package.

**Devices (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any

**Comment by pspaczek** [comment]
@psmyrek now I used [--exact](https://github.com/lerna/lerna/blob/master/commands/version/README.md#--exact) for lerna publish. Thanks for your help to make the UI better 💚
![Zrzut ekranu 2020-05-19 o 10 55 27](https://user-images.githubusercontent.com/12138170/82306356-4134bd00-99bf-11ea-97d9-1e32738298dc.png)
