### ISSUE TITLE
[FEATURE] Order details in the my account section

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/storefront-ui#1190]
In my account, in the section of history orders, each element has a link to "view details",  but there is no such a view:

<img width="618" alt="Screenshot 2020-05-15 at 11 29 37" src="https://user-images.githubusercontent.com/7943292/82035167-74194100-969f-11ea-99d6-6e34015f0773.png">

**Comment by mbaran-dvnt** [comment]
Done:)
![Zrzut ekranu 2020-06-29 o 23 12 44](https://user-images.githubusercontent.com/62093203/86056630-0b730180-ba5e-11ea-816e-adfa40ff3717.png)
