### ISSUE TITLE
[FEAT] wishlist 

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/storefront-ui#1194]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:

  - Details of the technical implementation
  - Tradeoffs made in design decisions
  - Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by martaradziszewska** [comment]
@lukeromanowicz I'll close this issue, it seems that the proper one is in #1195 :)
