### ISSUE TITLE
[ Mobile ] Create Header mobile view

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#12]
![image](https://user-images.githubusercontent.com/15185752/54690570-fcdf3000-4b21-11e9-9437-9bd830e30da5.png)

**Proposed api**
- slot left
- slot right
- slot center
- default slot

**How to find on designs**
See designs: https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=291%3A1461

Under "components" tab on bottom left corner find "mobile components -> top bar"
![image](https://user-images.githubusercontent.com/15185752/54691044-e71e3a80-4b22-11e9-9dfa-985ab317ad97.png)

**Comment by leomp12** [comment]
What do you think should be done with slot left, right and top?
In my vision, it haven't space for more than one content plus the arrow vector, and the vector should be a default for the component (enabled with a prop), or not?

**Comment by filrak** [comment]
Imho by default
- left, right, center (i have no idea why i wrote "top" before) are meant mostly for mobile view and content is highly depending on the current page context. Center slot should contain logo by default
- default slot should contain desktop version of header by default

I'm open to discussion though since this component is rather a complicated case.
