### ISSUE TITLE
[ Update ] Add Wishlist icon to ProductCard

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#120]
On hover -> desktop
![image](https://user-images.githubusercontent.com/15185752/58462000-3db28100-8131-11e9-8d1d-645734775093.png)
Always visible -> mobile
![image](https://user-images.githubusercontent.com/15185752/58462102-7ce0d200-8131-11e9-96bf-9b8f8091fd71.png)

When item is on wishlist: 
![image](https://user-images.githubusercontent.com/15185752/58462414-23c56e00-8132-11e9-8f6b-43eb332ca186.png)

- [ ] Add icon
- [ ] Add `wishlist-icon`  prop defaulting to current wishlist icon and accepting other icons url or false
- [ ] Add wishlist-icon slot around wishlist icon
- [ ] add `on-wishlist` prop defaulting to false
- [ ] emit `click:wishlist` even on click
- [ ] write unit test for setting other icon (or none) via prop
- [ ] write unit test for clicking icon (check if event is emitted

**Comment by mayashavin** [comment]
@filrak need the icon of favourited (aka filled heart svg)

**Comment by mayashavin** [comment]
@filrak we need a `on-wishlist-icon` so user can decide to select what when it's favorite. default will be filled heart. wdyt?
