### ISSUE TITLE
[FEATURE] Change hover effect for close button in BottomModal

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/storefront-ui#1209]
**Describe how this feature will help us improve**
Imho close button in BottomModal should change color from green to black when you hover the mouse over it.

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
Close button in BottomModal should change color from green to black when you hover the mouse over it.

  
**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by martaradziszewska** [comment]
@alinadivante thanks for the issue! I checked and according to design, the close button has color back at the beginning. 
![image](https://user-images.githubusercontent.com/34887212/82641282-68cc9500-9c0c-11ea-9dcc-b043b2e61a34.png)

**Comment by martaradziszewska** [comment]
@mbaran-dvnt Can you give us some info about this? :)

**Comment by mbaran-dvnt** [comment]
Agreed with Alina.  Close button in BottomModal should change color from green to black when you hover the mouse over it.

 
![Zrzut ekranu 2020-06-29 o 23 14 43](https://user-images.githubusercontent.com/62093203/86056812-51c86080-ba5e-11ea-9464-43716739752a.png)
