### ISSUE TITLE
[BUG] Missing placeholder property in SfInput

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#1222]
**Describe the bug**
 - Currently there is no way to set a placeholder on `<input>` via prop. The label acts as a placeholder and this is considered a bad practice.

- Is someone doesn't want the 'label going up' behavior then this is impossible to type in text without label overlapping input. Thats why placeholder property is needed. 

**Expected behavior**
It is possible to set placeholder via prop.

**Comment by AdamPawlinski** [comment]
I think there is possibility to pass this prop: 
![image](https://user-images.githubusercontent.com/32042425/83033267-302b2200-a037-11ea-9330-737282aa3b00.png)
resulting in this:
![image](https://user-images.githubusercontent.com/32042425/83033375-50f37780-a037-11ea-9975-ca3956d7a971.png)
Wdyt @aniamusial?

**Comment by aniamusial** [comment]
@AdamPawlinski cool, can we add it to storybook? :) As its not there I assumed we do not have it.

**Comment by pspaczek** [comment]
@aniamusial is native property :) @AdamPawlinski can you add it to the storybook, do PR for it and close these issues?

**Comment by AdamPawlinski** [comment]
Yes of course :)
