### ISSUE TITLE
[FEATURE] Adjust SfBreadcrumbs to small screens

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/storefront-ui#1224]
**Describe how this feature will help us improve**
Currently, `SfBreadcrumbs` component is not adjusted to small screens, especially when there is a lot of breadcrumbs. When there is no place to display all breadcrumbs, they are are cut off.

**Describe the solution you'd considered**
In my option, the best solution will be add the possibility to wrap breadcrumbs in a second line, when there is no place. We can achieve it in a very simple way:

1) Add `flex-wrap: wrap;` CSS rule to `.sf-breadcrumbs__list`
2) Replace `before` pseudo-element, which is used to display separator, to `after` pseudo-element
3) Add bigger line-height

These changes allow us to achieve something like this, where there is no place to display breadcrumbs in one line: https://prnt.sc/sp809s

**Comment by AdamPawlinski** [comment]
Multiline breadcrumbs added. I left line height unchanged, because it looks good imo, but it need to be designed @mbaran-dvnt
