### ISSUE TITLE
[FEATURE] Add possibility to go through mobile menu by keyboard

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/storefront-ui#1225]
**Describe how this feature will help us improve**
Currently, there is not possible to go through mobile menu by keyboard only.

**Describe the solution you'd considered**
By changing `SfMenuItem` and back arrow to `buttons` we can achieve this goal.

**Comment by AdamPawlinski** [comment]
@qiqqq I added button role to menuItem component, but could you please precise what you mean with adding button on back arrow? There is back arrow button in SfBar already used and it works well.

**Comment by AdamPawlinski** [comment]
@qiqqq I added button role to menuItem component, but could you please precise what you mean with adding button on back arrow? There is back arrow button in SfBar already used and it works well.
