### ISSUE TITLE
[BUG] not strong version dependency to @storefront-ui/shared broke the project on deploy

### ISSUE THREAD

**Issue by OleksiiStepanov** [DivanteLtd/storefront-ui#1229]
I dont have any change in my project but after sometime when my CI/DI environment have build the project the project was broken    

Bug was described there #1176 

Could anybody explain why closed this issue? I have same problem and i not  understand how i can use not latest version of @storefrotn-ui package.

If each version  @storefrotn-ui/vue correctly work with same version @storefrotn-ui/shared then shoud be specify  in packackge.json without symbol ^ 

If only some versions incompatible, then  @storefrotn-ui/shared should be change the major version of library. 

Otherwise we have got broken project on deploy when after sometime in CI/DI environment project have build with new incompatible version of  @storefrotn-ui/shared 

In my case after build on deploy I have got  @storefrotn-ui/vue:0.7.6 and @storefrotn-ui/sared:0.7.13

**Comment by pspaczek** [comment]
@OleksiiStepanov like on #1176, after 0.7.10 we stopped used `^` for `@storefront-ui/shared` packed, that's the reason to close #1176 issues. Sorry for that. 
Soon, we will improve our semver in Storefront-UI
