### ISSUE TITLE
[FEATURE] Add possibility to add label to SfPrice 

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#1244]
**Describe how this feature will help us improve**
There are some cases when special prices have additional labels or icons leading and emphasizing  the promotions such as "WAS $15.00, NOW $10.00" or maybe some icons instead. 
Right now, there is no possibility to add such a label without overriding entire component.

**Describe the solution you'd considered**
- adding slot with label to prices

**Comment by filrak** [comment]
Maybe it would be better to first ask @mbaran-dvnt to design how something like this should look like to keep design <> code consistency. We can then add an example to Storybook

**Comment by filrak** [comment]
@justyna-13 can you first ask Marcin? ;)

**Comment by justyna-13** [comment]
@filrak sure, I'll ask Marcin :)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-06-29 o 23 17 51](https://user-images.githubusercontent.com/62093203/86057065-c1d6e680-ba5e-11ea-84b3-1f77ae78592b.png)

Also you can find labels and pricing defined in Atoms / Molecules. 

Hope that's enough:)
