### ISSUE TITLE
[ Update ] Add description prop & slot to SfRadio

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#126]
Design (slightly different to what we have in figma, it is the second row, I ommited first one since it's not so generic)
![image](https://user-images.githubusercontent.com/15185752/58470176-6d698500-8141-11e9-963b-a83530f0449c.png)

This feature is pretty useful especially on checkout so why not to implement it as an option? ;)

Add `description` slot and prop to SfRadio (prop if you want to provide plain string and slot with same name to enable html injection)

**Comment by bahdcoder** [comment]
A question about this design: Does this apply to each option of `SfRadio`, or to this:

![Screen Shot 2019-06-09 at 9 25 19 PM](https://user-images.githubusercontent.com/19477966/59163767-1e3a3180-8afd-11e9-9ce1-5036ade49c8a.png)

**Comment by filrak** [comment]
What you mean by each design? Every version of SfRadio should have this option

**Comment by bahdcoder** [comment]
What I mean is, Does every single radio option get a description, Which means `apple` gets its description, `banana` get's it's description and `pineapple` gets its description (Meaning each option object will have a `description` field)? Or, is there simply one description explaining what the options are, which appears below all the options ?

**Comment by filrak** [comment]
Ah ok, sorry :) . Each option should have description

**Comment by bahdcoder** [comment]
If that's is the case, then I'm not too sure the `prop` API can be supported. Only the `slot`

**Comment by filrak** [comment]
Why you think so? It doesn't need to be complicated markup. Most likely it will be just a simple description from headless cms or sth like this. Imho we should support both versions

**Comment by bahdcoder** [comment]
So here's the thing. You can't pass a prop in a prop. For example look at the current version of the component. Is it possible to have a `label` prop if we wanted to ? It isn't. Same thing with the `description`, we can't have a `description prop for each item, unless I am getting this wrong.
