### ISSUE TITLE
[FEATURE] Implementation of Banner Grid 1 defined in Figma

### ISSUE THREAD

**Issue by swapnilmmane** [DivanteLtd/storefront-ui#1269]
**Describe how this feature will help us improve**

The Banner Grid 1 is defined in the [Figma file](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A3809).
With the implementation of Banner Grid 1, our users will have one more option in Banner Grid component.

![Banner Grid 1](https://user-images.githubusercontent.com/7145848/85718840-83fb5a80-b70c-11ea-8394-7508c490a485.png)

**Describe the solution you'd considered**

Here is the technical implementation details, I am planning to follow, please have a look:

1.) Add one more template with bannerGrid=3 at [SfBannerGrid/SfBannerGrid.vue](https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfBannerGrid/SfBannerGrid.vue)

Sample Code:
```vue
<template v-if="bannerGrid === 3">
  <div class="sf-banner-grid__row">
    <slot name="banner-A" />
  </div>
  <div class="sf-banner-grid__row">
    <div class="sf-banner-grid__col">
      <slot name="banner-B" />
    </div>
    <div class="sf-banner-grid__col">
      <slot name="banner-C" />
    </div>
  </div>
</template>
```

2.) Update the [SfBannerGrid stories](https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfBannerGrid/SfBannerGrid.stories.js) file to support newly implemented grid.

Hi team,
Kindly let me know if I am missing any step in the suggested implementation, thank you!

**Comment by justyna-13** [comment]
Banner Grid has changed in our new designs. The new one is implemented. New designs are [here](https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-%7C-Design-System?node-id=4392%3A19143)
