### ISSUE TITLE
SfIcon - receive svg path as part of props

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#127]
SfIcon will render svg as icon according to `path` prop which is SVG path passed from outside.

The icon path is kept and passed as prop variable.

User can import icon he needs from our available icons (which are just collections of svg paths) and pass it to SfIcon to render the icon accordingly. 

Or he can choose his own icon path.

_Example_: (variable name or implementation can be adjusted to the correct convention and logic)

```
//script
 data() {
       return {
          twitter: '<path of icon>'
....

//Template
<SfIcon :path="twitter"/>

//In SfIcon template
<svg> <path :d="path"/></svg>
```

**Comment by filrak** [comment]
It's more like a task for a whole component so can you give a more in-depth description of internals and bahevior (including resolution of icons) or just assign yourself? 🍡

**Comment by mayashavin** [comment]
@filrak Do we support to config also the resolution of `size` and `color` as `props` of the icon?
If so:
1. What sizes are we supporting? I saw in `SfCircleIcon` we have several sizes, should I follow it?
2. Size will be computed into a related form of class?
3. Same questions for `color`

If not, we will let user define whatever size and pass it as a class in  `customClass` ?

**Comment by filrak** [comment]
@mayashavin  yes, both.

I guess there should be an option to just pass custom size/color.

1. you mean what should be presented in storybook or which size we should support generally. If storybook -> it's according to designs. There is nothing about icons in designs so you need to figure it out by yourself. 
2. what you mean exactly?
3. same for color

`customClass` is actually just for knobs to work. I couldn't find a way to hide it

**Comment by mayashavin** [comment]
@filrak 
1. Got it
2. I mean for example in `SfCircleIcon` size comes in class name form (`<something>-small` for example). I was wonder if  we got the size as px or as a string represented `s, xs, lg` and so on. If it's the string, then we will map it to the related class name.

I will try to figure out what is the best way to support this.
