### ISSUE TITLE
[FEATURE] SfHeader icons should have possibility to change size

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1300]
**Describe how this feature will help us improve**
Icon in SfHeader have size set by inline style, like so: 

```
<SfIcon
       :icon="accountIcon"
        size="1.25rem"
        :class="{
        'sf-header__icon--is-active': activeIcon === 'account',
         }"
 />
```
There should be possibility to change it easily by prop.

**Is your proposal related to a problem?**

You can't easily change icon size in SfHeader. 

**Describe the solution you'd considered**

I would propose to use prop like "iconsSize" to add proper sizes to all SfIcon used in SfHeader.
```
iconsSize: {
      type: String,
      default: "",
    },
``` 
and pass to SfIcon:
`:size: "iconsSize"`
You can pass there common sizes like '12px' or SFUI standard sizes like so 'sm'.
Other solution would be to use custom properties like --header-icon-size and assign it to --icon-size inside .sf-header__icons class. But it's less efficient I think.

**Comment by justyna-13** [comment]
will be solved by #1399
