### ISSUE TITLE
[BUG] Typos + misleading links in Documentation

### ISSUE THREAD

**Issue by daksamit** [DivanteLtd/storefront-ui#1303]
**Describe the bug**

Some typos in docs to fix:
- [become-a-contributor.md](https://docs.storefrontui.io/contributing/become-a-contributor.html#work-on-documentation) - `extremply` instead of `extremly`
- [coding-guidelines.md](https://docs.storefrontui.io/contributing/coding-guidelines.html#css-custom-properties) `you cand find` instead of `you can find` 
some broken links like `coding-guidelines.md#Unit-tests` instead of lower case `coding-guidelines.md#unit-tests`  and more.

I can handle it by myself.

**Comment by daksamit** [comment]
There are a little more bugs, could you assign me to this issue @filrak ?

**Comment by AdamPawlinski** [comment]
Could you please prepare new issue for these bugs? I can assign you to it, just let me know :) Thank you.
