### ISSUE TITLE
[BUG] Documentation broken links and code snippets formatting

### ISSUE THREAD

**Issue by daksamit** [DivanteLtd/storefront-ui#1309]
**Describe the bug**
Documentation still contains some page with broken links and badly formatted snippets like 4 indentations instead of 2.

**Comment by daksamit** [comment]
@AdamPawlinski, please assign me :)

**Comment by AdamPawlinski** [comment]
It's yours. You are damn fast :)

**Comment by daksamit** [comment]
Just testing GitHub mobile app. I'll take care of it tomorrow :D

**Comment by AdamPawlinski** [comment]
Ok that's great. Thanks for your contribution :)
