### ISSUE TITLE
[BUG] Image atom broken in Storybook

### ISSUE THREAD

**Issue by AishwaryShrivastav** [DivanteLtd/storefront-ui#1310]
**Describe the bug**

Image atom is not displaying on the storybook [website](https://storybook.storefrontui.io/?path=/story/atoms-image--common) 

**How to reproduce**
1. Go to https://storybook.storefrontui.io
2. Click image inside atoms

**Expected behavior**
Error should not be visible and working 

**Actual behavior**
Error is displaying 

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Michal-Dziedzinski** [comment]
@AishwaryShrivastav I do't see an error, are you sure that it exists?

**Comment by AishwaryShrivastav** [comment]
> @AishwaryShrivastav I don't see an error, are you sure that it exists?

@Michal-Dziedzinski, I am sure it exist in this [page](https://storybook.storefrontui.io/?path=/story/atoms-image--common).



> Me too, what do you mean by'image inside atoms' @AishwaryShrivastav ?
> It seems to be everything ok on desktop and mobile (windows and linux)

In the steps to reproduce, I mean to click on the image link, inside atoms list.



I saw this error on the link mentioned in readme.md file, assuming that its a official display of the elements and things were broken there, So I created a ticket here, Do we have any other place to mention bugs for this storybook 


![ImageAtom](https://user-images.githubusercontent.com/8766155/87897810-12dc6800-ca6a-11ea-83af-54d65080dc55.png)

**Comment by Michal-Dziedzinski** [comment]
@AishwaryShrivastav  This is a good place to report such issues, but I still don't see such a case. The error may be due to the value you entered in the rootMargin prop.

**Comment by AishwaryShrivastav** [comment]
@Michal-Dziedzinski, I haven't entered any value, its just a case that I open 
https://storybook.storefrontui.io,
navigate to image inside atom list,
click on image, that is displaying this error. 

On proper testing I found that that this is working on chrome browser and not firefox browser.
