### ISSUE TITLE
[BUG] Injecton "tabConfig" not found in SfTab

### ISSUE THREAD

**Issue by Michal-Dziedzinski** [DivanteLtd/storefront-ui#1327]
**Describe the bug**
There is error: `[Vue warn]: Injection "tabConfig" not found` in SfTab

**How to reproduce**
1. run `test:dev` npm script

**Expected behavior**
Error does not occur

**Actual behavior**
Error is occur

**Comment by AdamPawlinski** [comment]
I coudn't reproduce this error. Are there special conditions for it to appear?
