### ISSUE TITLE
SfSelect changes

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#1334]
This task has 2 parts

1. Change `SfSelect` to `SfComponentSelect` and replace all its occurencies
2. Build a new component that looks like `Sfselect` but uses a native `select` UI and selector (like bootstrap select component https://getbootstrap.com/docs/4.0/components/forms/#form-controls ).The API should remain unchanged except removing `size` and `persistent` props.

cc @aniamusial

**Comment by AdamPawlinski** [comment]
I wonder. maybe we should keep the size prop? It can be useful to limit the amount of items. 
And there were some questions about possibility of using multiple choice. Adding multiple prop can be useful, wdyt @filrak ?

**Comment by AdamPawlinski** [comment]
There is another solution worth of considering, I think. We can build hybrid select consisting of two: native and custom one and show them depending on user's device (mouse or keyboard). Although it can be surprising for someone when it changes depending on control device, but it will be good for a11y reasons. The solution is described in this article https://css-tricks.com/striking-a-balance-between-native-and-custom-select-elements/. Wdyt @filrak ?
