### ISSUE TITLE
[BUG] There is no "TextArea" field

### ISSUE THREAD

**Issue by Malwurf** [DivanteLtd/storefront-ui#1350]
**Describe the bug**
There is no input type TextArea.

**Expected behavior**
The input type of TextArea should be added. It should have a consistent appearance with other form elements.

**Actual behavior**
That kind of field doesn't exist.

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-07-31 o 15 09 47](https://user-images.githubusercontent.com/62093203/89038048-e107b300-d33f-11ea-88c9-584ac8b9a49f.png)

Done:)
