### ISSUE TITLE
[BUG] SfSelect options is not scrollable

### ISSUE THREAD

**Issue by leonel1524** [DivanteLtd/storefront-ui#1357]
**Describe the bug**
if the SfSelect has many options, when displaying them the list becomes infinite down

**How to reproduce**
1. Go to checkout in shipping tab.
2. Click on country field
3. See list of optiones

**Expected behavior**
A scroll for the lists with many options

**Actual behavior**
The list grows down according to the number of options

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**
![image](https://user-images.githubusercontent.com/23490674/89681642-4ff68600-d8c3-11ea-87be-6cef95bdcf6c.png)

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Debian 10 (buster)
 - Browser: chrome 84.0.4147.105

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by filrak** [comment]
On it ;)

**Comment by AdamPawlinski** [comment]
Connected with these issue https://github.com/DivanteLtd/storefront-ui/issues/1139. It will be solved in https://github.com/DivanteLtd/storefront-ui/pull/1296

**Comment by mayashavin** [comment]
closed since it's solved on #1296
