### ISSUE TITLE
[BUG] SfModal close button 's type is submit (default html), it submits forms on close if placed within one.

### ISSUE THREAD

**Issue by EugeneHlushko** [DivanteLtd/storefront-ui#1378]
**Describe the bug**
Placing SfModal inside a <form> will submit the form when cross (SfButton) is clicked.

**How to reproduce**
1. Mount SfModal inse a html form 
2. click on close cross in the modal
3. observe form being submitted

**Expected behavior**
Modal close button type is set to `button` so it doesnt act as a submit trigger

**Actual behavior**
it does submit.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by EugeneHlushko** [comment]
You might want to consider defaulting to `type="button"` button in SfButton when its not a link

**Comment by Qrzy** [comment]
Looks like #1416 fixed it for desktop only, since buttons in SfBar still don't have `type="button"`.
Could this be reopened?
