### ISSUE TITLE
[BUG] SfColor has no border with light colors

### ISSUE THREAD

**Issue by justyna-13** [DivanteLtd/storefront-ui#1379]
**Describe the bug**
SfColor should have a border for light colors

**How to reproduce**
1. Go to SfColor
2. Enter "white" in color prop
3. Now you can't see where SfColor is

**Expected behavior**
Light colors have visible border

**Actual behavior**
Light colors have not border 

**Screenshots**

![Zrzut ekranu z 2020-08-27 10-52-14](https://user-images.githubusercontent.com/46591755/91419218-715be980-e853-11ea-8ff2-c2873aeb20d7.png)

**Comment by mayashavin** [comment]
Close since it's duplicate with #1381
