### ISSUE TITLE
[ Minor ] Fix SfCarousel pagination

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#138]
`SfCarousel` pagination is not working properly, testing on [storybook](https://storybook.storefrontui.io/?path=/story/organisms-carousel--basic) I'm getting:
_(1-4) -> (5-8) -> (8-3) -> (1-4)_
The correct would be:
_(1-4) -> (5-8) -> (1-4)_

I think we have to hard set the glide index with:
```js
move.direction = '='
move.steps = newIndex
```

@przspa can you take care of it? I can do it if you prefer.

**Comment by leomp12** [comment]
Actually, I think it's a glide bug, but we can deal with it by forcing the index instead of just using side moves.

**Comment by przspa** [comment]
@leomp12 I will fix this bug

**Comment by leomp12** [comment]
Great, thanks!
