### ISSUE TITLE
 [ Desktop ] Create SfTopBar

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#139]
[Designs on Figma](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=303%3A1239)

![Screenshot_2019-06-04 Figma](https://user-images.githubusercontent.com/10326572/58907348-53e9af80-86e4-11e9-9a0f-324941a83f3f.png)

Imo we may handle just the bar with this component, languages menu (country flags) would be another component.

# Proposed API

- `default` slot for centralized content;
- `left` and `right` slots for custom content on respective sides;

No props, no methods, no events...
Please mind that it's **just a proposal**. We're open to discussion regarding component API.

**Comment by bahdcoder** [comment]
@leomp12 would love to work on this to get a feel of the project. Awaiting your response. Thanks !

**Comment by leomp12** [comment]
Hey @bahdcoder , sounds awesome!
@filrak please take a look here and assign this issue to @bahdcoder :)

**Comment by filrak** [comment]
API looks good to me, thanjks @leomp12  ;) @bahdcoder please confirm invitation on email and assign yourself

**Comment by bahdcoder** [comment]
Done !
