### ISSUE TITLE
[BUG] css-loader warning

### ISSUE THREAD

**Issue by StreadChou** [DivanteLtd/storefront-ui#1390]
**Describe the bug**
css-loader  warning

**How to reproduce**
1. install quasar cli (A Vue framework)
2. install storefront-ui
3. run

WARNING  Compiled with 1 warnings                                                                                                                                                                                            5:35:19 PM

 warning  in ./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue?vue&type=style&index=0&lang=scss&

Module Warning (from ./node_modules/css-loader/dist/cjs.js):
Warning

(47:5) Unable to find uri in 'background: var(--select-option-background, var(--select-option-background-image, url("")) var(--select-option-background-color, var(--c-white)) no-repeat var(--select-option-background-position, 0% 0%))'

 @ ./node_modules/vue-style-loader??ref--8-oneOf-2-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-2-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-2-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-2-3!./node_modules/@quasar/app/lib/webpack/loader.quasar-scss-variables.js!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue?vue&type=style&index=0&lang=scss& 4:14-531 14:3-18:5 15:22-539
 @ ./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue?vue&type=style&index=0&lang=scss&
 @ ./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue
 @ ./node_modules/@storefront-ui/vue/index.js
 @ ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=js&
 @ ./src/pages/Index.vue?vue&type=script&lang=js&
 @ ./src/pages/Index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from 
 App · Opening default browser at http://localhost:8080

**Comment by ryanC1993** [comment]
Facing the same issue.

**Comment by Gabrieljsilva** [comment]
I am also facing the same problem

**Comment by f3ltron** [comment]
arf i made a duplicate #1436
