### ISSUE TITLE
[ RFC ] [ Mobile / Desktop ] Create SfProductsGroup

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#140]
[Designs on Figma](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=3677%3A2)

![Screenshot_2019-06-04 Figma(1)](https://user-images.githubusercontent.com/10326572/58910310-919e0680-86eb-11e9-904f-f6472ec9c90d.png)

# Proposed API

## Props
```js
{
  /**
   * Whether to show quantity selector for each item
   */
  editQuantity: {
    type: Boolean,
    default: true
  },
  /**
   * List of product items:
   * array of nested objects with format: `[{ image, title, sku, label, price, quantity, min, max }]`)
   */
  products: {
    type: Array,
    required: true
  }
}
```
On product object (element of `products` array), `quantity`, `min` and `max` may be optional, min and quantity should defaults to 1;
I've called `label` the _White_, _Green_ and _Black_ on screenshot sample, would also be `property`, `specification` or something like that (not color because it should not always be color variation, I think).
eg.:
```js
let products = [
  {
    image: 'https://any.com/img.png',
    title: 'My Blue Product',
    sku: '123BLUE',
    label: 'Blue',
    quantity: 1,
    price: 10,
    min: 1,
    max: 20
  }
]
```

## Slots
`product` (or `default` ?) slot for custom markup for each item, binds `product` object:
```vue
<slot name="product" :product="product">
  <!-- -->
</slot>
```

**Comment by filrak** [comment]
We need to wait till we have this one https://github.com/DivanteLtd/storefront-ui/issues/103

**Comment by leomp12** [comment]
Yup, almost the same API.
Same for `SfProductCard`, I've based the product object on current product card api.
Maybe `SfCartItem`? I know it may be used not only for cart but I think "cart item" is simpler and self-explanatory.

**Comment by filrak** [comment]
I guess we should stick with generic names. Even if what you suggested looks descriptive it can be also misleading for some folks

**Comment by leomp12** [comment]
Maybe, but don't you think `SfCollectedProduct` is very large and yet not so descriptive? I think it can be even more misleading.
`SfCartItem` is not perfect but I think it's more common at least, [Reaction](https://designsystem.reactioncommerce.com/#!/CartItem) is using that for example..

**Comment by filrak** [comment]
It's not blocked anymore. I think we need to do this one froms cratch and don't resuse any other component in here except small ones

**Comment by filrak** [comment]
I think we will end up with API following our conventions as a scoped slot. Inner items will be similar to SfProductCard and SfCollectedProduct mix ;) @przspa please reach em before starting this one as there are significant differences in designs to make it work for either bundled and grouped product (refs https://marketplace.webkul.com/knowledgebase/bundle-product-vs-grouped-product/)

**Comment by filrak** [comment]
@leomp12 how about making a single component for each product instead? Is there a reason to wrap them together?

**Comment by leomp12** [comment]
@filrak agree! No reason to wrap it

**Comment by leomp12** [comment]
Then it can't be `SfProductGroup`, you have a name suggestion?

**Comment by juanfrantomas** [comment]
I think it's a way of listing products, we could make different views of listing products and that could be used for a future on different sites of the page, What do you think ```SfProductListView```?
