### ISSUE TITLE
[BUG] SfArrow with transparent modifier on disbaled mode 

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1418]
**Describe the bug**
When disabled and with transparent modifier doesn't look like disabled when hovered:

**How to reproduce**
Go to SfArrow add transparent modifier, turn on disabled state and hover state.

**Expected behavior**
Not to change behaviour after hover. 

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.

Or add code snippets (Code sandbox)

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/94136524-59cd4c00-fe65-11ea-8cb9-d778bfeed367.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by ilumin** [comment]
@AdamPawlinski  I want to help fix this one too, could you assign it to me?

**Comment by AdamPawlinski** [comment]
Yes, I assigned it.
