### ISSUE TITLE
[BUG] SfCircleIcon in disabled state with color modifier

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1420]
**Describe the bug**
When color modifier is added in disabled state it doesn't look like disabled. 

**How to reproduce**
Go to CircleIcon and add color modifier e.g. color-warning and turn disabled on. See the result.  

**Expected behavior**
No matter what modifier is added it should look like disabled in disabled state. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/94201597-81033800-febc-11ea-8a43-223c01329786.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by ilumin** [comment]
@AdamPawlinski I want to contribute, could you assign me?

**Comment by AdamPawlinski** [comment]
Yes, of course with pleasure :) Thanks for your support.
