### ISSUE TITLE
[BUG] SfInput placeholder overwritten by label

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1421]
**Describe the bug**
On SfInput when placeholder is added label overwrites it. 

**How to reproduce**
Add placeholder prop to SfInput.

**Expected behavior**
Adding placeholder should move label up like when text is typed.

**Actual behavior**
What actual happened.

**Code examples**
Use placeholder-shown pseudoclass to move label up. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/94202149-709f8d00-febd-11ea-847e-02b0af4ae494.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by rungta08** [comment]
Can I work on this issue?? @AdamPawlinski

**Comment by AdamPawlinski** [comment]
Obviously you can :)

**Comment by justyna-13** [comment]
fixed #1435
