### ISSUE TITLE
[FEAT] SfSection remove underline modifier

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1425]
**Describe how this feature will help us improve**
Remove underline modifier in SfSection. It is no longer necessary as it doesn't work now and has no effect on layout. MOreover there are no use cases on designs regarding using this modifier. 
![image](https://user-images.githubusercontent.com/32042425/94236381-66a57a80-ff0d-11ea-9cd8-87425b91c2d9.png)

![image](https://user-images.githubusercontent.com/32042425/94236391-69a06b00-ff0d-11ea-9145-ee51e616f72f.png)

**Is your proposal related to a problem?**
No.

**Describe the solution you'd considered**
Just remove css class from component and stories.

**Comment by JonathanDn** [comment]
Hey @AdamPawlinski I would love to tackle this.
- I cloned the project and have it in my local env
- I am in SFSection component and if I understand you correctly you would like to remove the condition class `sf-heading--underline` from the comp?

**Comment by JonathanDn** [comment]
@AdamPawlinski 
Issue fixed on PR. Reviewed. Can it be merged?
