### ISSUE TITLE
[BUG] SfCollectedProduct adjust to designs

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#1426]
**Describe how this feature will help us improve**
Adjust SfCollectedProduct layout with detailed modification to the Figma designs.

Figma:
![image](https://user-images.githubusercontent.com/32042425/94237000-707bad80-ff0e-11ea-973b-87e85be7c267.png)

Current layout:

![image](https://user-images.githubusercontent.com/32042425/94237029-7d989c80-ff0e-11ea-9233-2bbd588f0fa6.png)

on hover: 
![image](https://user-images.githubusercontent.com/32042425/94238104-21cf1300-ff10-11ea-9e11-68d5b1d0deef.png)

**Is your proposal related to a problem?**
No.

**Describe the solution you'd considered**
Add new links to configuration slot according to designs.
Add new slot for text.   

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by justyna-13** [comment]
The view that is shown on figma is for Detailed cart view :) so it's not a common view for SfCollectedProduct

**Comment by AdamPawlinski** [comment]
@justyna-13 You are right so I close this issue. Thx :)
