### ISSUE TITLE
Add yarn lint as precommit hook

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#144]
![image](https://user-images.githubusercontent.com/15185752/59084086-29713f80-88fa-11e9-9428-bf767b037d2d.png)

**Comment by jahvi** [comment]
I can handle this, would it be worth including prettier as well to keep the coding formatting consistent?

**Comment by mayashavin** [comment]
@jahvi thanks but next time please make sure the assigned person (which is me ;)) confirmed before you start working to make sure we don't do double work on the same task. Please assign your PR to me once done. Thanks :)

**Comment by jahvi** [comment]
@mayashavin My bad I didn't realise someone was working on it already, I'll pay more attention next time!
