### ISSUE TITLE
[BUG] Docs for global .scss  variables file -->`variables` directs to a non-existing file

### ISSUE THREAD

**Issue by JonathanDn** [DivanteLtd/storefront-ui#1441]
**Describe the bug**
Docs for global .scss  variables file -->`variables` directs to a non-existing file

**How to reproduce**
1. Go to [docs](https://docs.storefrontui.io/contributing/coding-guidelines.html#css-custom-properties)
2. Bullet number 3
3. See the description mentioning 2 different files `variables` and `__variables`

**Expected behavior**
The docs should address a single file for global css variables `__variables`

**Actual behavior**
The docs address 2 differnt files and can cause confusion.

**Screenshots**
![image](https://user-images.githubusercontent.com/19703819/94524698-a1741f00-023b-11eb-9890-f0089b10f412.png)

**Devices (please complete the following information):**
 - Device: Dell Latitude Laptopt
 - OS: Windows
 - Browser: Chrome

**Comment by AdamPawlinski** [comment]
@JonathanDn thanks for your efforts. Can you take a look at the code: 

- all global variables are in three files inside `shared/styles/variables` folder
- but they are all imported through '_variables.scss' file in `shared/styles' folder and you can import them from this file,
- the same situation is with '_helpers.scss' file mentioned above. 

I think it is not clearly stated, so could you please propose better way to explain this? Wdyt @JonathanDn?

**Comment by JonathanDn** [comment]
@AdamPawlinski Okay, so essentially what you tried to achieve there is having an index scss file that has imports of all the other files divided by context.

Maybe its good to name the file with the word **index** as an alternative naming convention? I assume I and other people would understand it better if it did not have the same name. it can be confusing.

Maybe something like `variables-index.scss`

Then in the docs we can also explain better, something like this(attached)
![image](https://user-images.githubusercontent.com/19703819/94530739-31b66200-0244-11eb-97d4-42ff751516e4.png)

**Comment by mayashavin** [comment]
Please note that there is folder shared/styles/variables which contains all the variables declaration files, and there is _variables.scss which united them. I'm closing this PR since it's not valid. Thanks
