### ISSUE TITLE
[BUG] fix responsive for table component

### ISSUE THREAD

**Issue by Malwurf** [DivanteLtd/storefront-ui#1444]
**Describe the bug**
Currently table component on mobile is unreadable (photo above). If implementation doesn't have colorful data it is less readable than on screens.

**How to reproduce**
1. Go to any item which has table
2. Display it on mobile device
3. See error

**Expected behavior**
Data from the table should be readable on mobile devices.

**Solution**
I recommend using [attr data solution](https://css-tricks.com/responsive-data-tables/)

![responsive-table-on-iphone-1](https://user-images.githubusercontent.com/4071200/94547289-60860580-024f-11eb-9f9e-5a29b880e859.png)

**Screenshots**
Desktop:
![Screenshot from 2020-09-29 12-21-41](https://user-images.githubusercontent.com/4071200/94546665-7fd06300-024e-11eb-8314-2c2e581d168f.png)

Mobile:
![Screenshot from 2020-09-29 12-21-59](https://user-images.githubusercontent.com/4071200/94546662-7fd06300-024e-11eb-9573-70b74fef4477.png)

Small device:
![Screenshot from 2020-09-29 12-22-12](https://user-images.githubusercontent.com/4071200/94546659-7e9f3600-024e-11eb-8d29-5dad35a39795.png)

**Devices (please complete the following information):**
 - Any mobile device smaller than tablet

**Comment by filrak** [comment]
@mbaran-dvnt :)

**Comment by mbaran-dvnt** [comment]
Designs added to Molecules. Good catch!
