### ISSUE TITLE
[BUG] v-focus on ssr frameworks causing issues

### ISSUE THREAD

**Issue by masterblah** [DivanteLtd/storefront-ui#1449]
**Describe the bug**
As of now, if we install storefront-ui in NUXT or Gridsome to generate static pages, it will crash the compiler/app.

**How to reproduce**
1. Install Gridsome or NUXT .. in static pages form .. (on gridsome only crashes on build)
2. run dev ... (or build in gridsome)
3. see error -> "v-focus directive not found" ...

**Expected behavior**
Nuxt should be able to build... :P 

**Actual behavior**
v-focus (found in sfSearchBar) should have a ssr complient directive or created as a plugin, in order to ensure more compatibility to other platforms, if we delete the directive in the module, everithing works great

**Devices (please complete the following information):**
 - Device:Laptop
 - OS: Ubuntu
 - Browser: chrome (but not really applicable .. )

**Additional context**
Nuxt, Gridsome

**Comment by justyna-13** [comment]
Thank you @masterblah for reporting this issue. We also found this bug and will be fixed in 9.0.1 #1446
