### ISSUE TITLE
[BUG] Storybook example for ProductCardHorizontal has bug for hover links

### ISSUE THREAD

**Issue by daksamit** [DivanteLtd/storefront-ui#1471]
**Describe the bug**
Storybook -> ProductCardHorizontal -> Common [OK]
![image](https://user-images.githubusercontent.com/7165997/95975572-9feb4f00-0e16-11eb-91cc-c36deb48b18b.png)

Storybook -> ProductCardHorizontal -> With 2 Pictures [button hover background bug]
![image](https://user-images.githubusercontent.com/7165997/95975470-82b68080-0e16-11eb-8145-c53e91bb1ef8.png)

Buttons are next to each other and hovers all green (color--primary)

**How to reproduce**
- https://storybook.storefrontui.io/?path=/story/organisms-productcardhorizontal--common
- https://storybook.storefrontui.io/?path=/story/organisms-productcardhorizontal--with-2-pictures

**Expected behavior**
- Should links 'save for later and 'add to compare' be primary text color instead of primary background color ?
- Should links be positioned one by one instead next to each other ?

**Code examples**
Story examples for templates #actions
- common
```
          </template>
          <template #actions>
              <SfButton
                class="sf-button--text desktop-only"
                @click="$emit('click:add-to-wishlist')"
                style="margin: 0 0 1rem auto; display: block" 
              >
                Save for later
              </SfButton>
              <SfButton
                class="sf-button--text desktop-only"
                @click="$emit('click:add-to-compare')"
                style="margin: 0 0 0 auto; display: block"
              >
                Add to compare
              </SfButton>
          </template>
```

- with 2 pictures
```
        <template #actions>
          <div>
              <SfButton
                class="sf-button--text color-primary desktop-only"
                style="padding-bottom: 1rem" 
                @click="$emit('click:add-to-wishlist')"
              >
                Save for later
              </SfButton>
              <SfButton
                class="sf-button--text color-primary desktop-only"
                @click="$emit('click:add-to-compare')"
              >
                Add to compare
              </SfButton>
          </div>
          </template>
```

I think "with 2 pictures" should have #actions slot example same as common story example
I can fix this.

**Comment by AdamPawlinski** [comment]
@daksamit Yes you are right. I assign it to you. Thanks for noticing.
