### ISSUE TITLE
[BUG] Property isAddedToCart on ProductCard doesn't change how item displays

### ISSUE THREAD

**Issue by VMescheryakov** [DivanteLtd/storefront-ui#1482]
For reproduce go to the Playground  (https://storybook.storefrontui.io/?path=/story/organisms-productcard--common)
Check and uncheck property  isAddedToCart 
I expected to see badge on add-to-card button or changing icons

![image](https://user-images.githubusercontent.com/3495337/96547247-37dcb300-12c5-11eb-9460-c85edffebde2.png)

**Comment by daksamit** [comment]
I see the same with [ProductCardHorizontal](https://storybook.storefrontui.io/?path=/story/organisms-productcardhorizontal--common) component.

**Comment by justyna-13** [comment]
Duplicated #1427 and fixed in 0.9.2
