### ISSUE TITLE
[BUG] SfProductOption causes SSR missmatch

### ISSUE THREAD

**Issue by filipsobol** [DivanteLtd/storefront-ui#1507]
**Describe the bug**
Use of SfProductOption component causes SSR missmatch, resulting in following error:

![SSR missmatch error](https://i.imgur.com/BeGCeyP.jpg)

This issue can be reproduced on Product page in VSF NEXT (`commercetools` integration).

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
<SfSelect
    data-cy="product-select_size"
    v-if="options.size"
     :selected="configuration.size"
    @change="size => updateFilter({ size })"
    label="Size"
    class="sf-select--underlined product__select-size"
    :required="true"
>
    <SfSelectOption
        v-for="size in options.size"
         :key="size.value"
        :value="size.value"
    >
        <SfProductOption :label="size.label" /> <!-- Remove this line to get rid of the error -->
    </SfSelectOption>
</SfSelect>
```

**Comment by AdamPawlinski** [comment]
@filipsobol SfSelect was refactored to a native select element, maybe this change causes the problem. SfProductOption component is added to the storybook story as an example and not in the SfSelect component itself. I remove it from the stories and I can do it in VSF theme as well.
