### ISSUE TITLE
[Improvement] Simplify styles imports

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#157]
Currently for many components in `_internal` dirs we have separate css files. It doesn't make sense since internal components are just a parts of the bigger parents. 

The task is to simplify the SCSS structure and merge internals with their parents. for example
for `SfAccordion` and `SfAccordionItem` item we have two SCSS files named the same -> they should be merged into one (`SfAccordion`).

The easiest way to find those components is to look into `packages/vue/src/components/` and find all components inside `_internal` folders. Then merge corresponding SCSS files into their parent styles.

**Comment by dimitor115** [comment]
Hey! I really like the idea behind StorefrontUI and I would like to contribute to this project :smile: 
This task looks nice to explore the project and its structure. I would like to take it.

**Comment by dimitor115** [comment]
Should I wait till, the issue will be assigned to me? Or I can just do it?

**Comment by leomp12** [comment]
@dimitor115 I think you can start doing that :)

**Comment by dimitor115** [comment]
It was quite easy : https://github.com/DivanteLtd/storefront-ui/pull/231
