### ISSUE TITLE
[Docs] Update import script in storybook

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#158]
Currently when we enter any of the components stories the docs are telling that it should be imported this way:

```
import SfComponent from "@storefrontui/vue/dist/SfComponent.vue
```
( see ref https://github.com/DivanteLtd/storefront-ui/blob/master/packages/vue/src/components/atoms/SfArrow/SfArrow.stories.js#L68 )
Currently there is much better and cleaner way to do this:

```
import { SfComponent } from "@storefrontui/vue"
```

The task is to update all import references in docs to new format

**Comment by peoray** [comment]
@filrak I think this has been done, yeah?
