### ISSUE TITLE
[ Mobile / Desktop ] Create SfCharacteristic

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#164]
![image](https://user-images.githubusercontent.com/15185752/59355678-b87dbd80-8d27-11e9-8247-eb6fa446cbfb.png)

https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0

Feel free to propose any API, i guess props/slots for icon/title and description are enough

**Comment by filrak** [comment]
It can be also called SfCharacteristic, please propose a naming before coding ;)

**Comment by leomp12** [comment]
`SfFeature`?

**Comment by filrak** [comment]
We decided on characteristic in chat I believe. wdyt @leomp12 ?

**Comment by leomp12** [comment]
Not so good, but it's ok I think haha

**Comment by filrak** [comment]
@leomp12 I'm unpinning you ;)
