### ISSUE TITLE
[ Mobile / Desktop ] Implement SfFooter

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#167]
![image](https://user-images.githubusercontent.com/15185752/59356359-f9c29d00-8d28-11e9-8d03-0c7415a084f2.png)
![image](https://user-images.githubusercontent.com/15185752/59356423-1959c580-8d29-11e9-9fda-205ee3b9a5ac.png)
![image](https://user-images.githubusercontent.com/15185752/59356551-56be5300-8d29-11e9-86a8-d8e9d0852fff.png)

It should receive object for columns and social content. Please propose API before implementing the component.

**Comment by filrak** [comment]
`SfFooter` should have inner component called `SfFooterColumn` that receives `title` prop and have a default slot that can be filled with content

Feel free to ping me on discord with questions

**Comment by Flyingmana** [comment]
I would like to pick this one

**Comment by filrak** [comment]
@Flyingmana any updates on this? ;)

**Comment by Flyingmana** [comment]
will push the workInProgress tomorrow, 
Desktop is mostly done, Mobile still pending

**Comment by EugeneHlushko** [comment]
Hi guys, just found an issue where on desktop clicking a column header hides the items in list (mobile side effect?)
<img width="1121" alt="Screen Shot 2019-12-16 at 4 13 12 PM" src="https://user-images.githubusercontent.com/10549495/70913967-b7ec1980-201f-11ea-9f19-24f25bcda256.png">

**Comment by przspa** [comment]
@EugeneHlushko thanks, can you create an issue for that?

**Comment by EugeneHlushko** [comment]
Hi @przspa 
Just opened #559

**Comment by przspa** [comment]
fixed, thanks
