### ISSUE TITLE
[Mobile / Desktop ] Search Bar component styling and tests

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#17]
Create a search bar component for desktop and mobile;

Desktop (can be found on header)
![image](https://user-images.githubusercontent.com/15185752/54912415-e4d82980-4ef0-11e9-9cb9-588324633913.png)
Mobile (can be found on mobile components board)
![image](https://user-images.githubusercontent.com/15185752/54912499-0802d900-4ef1-11e9-9c9b-38dc3c273e69.png)

Proposed API
- icon (slot)
- placeholder (prop)

Tests
- props
- basic rendering
- slot

Designs: https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=291%3A1461

**Comment by martaradziszewska** [comment]
@filrak @patzick I'll try do this task
