### ISSUE TITLE
[ Docs ] Move docs to separate package

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#177]
Since docs will be shared for every version of SFUI (react/vue/whatever) they should become a separate package ( `@storefrontui/docs` )

**Comment by lauragift21** [comment]
Hi @filrak For this issue you want the entire docs folder to be moved to a separate package in this case `docs` just like we have the vue and shared packages?

**Comment by filrak** [comment]
@lauragift21 sorry i somehow missed your reply. Yes, entire docs
