### ISSUE TITLE
[ Mobile / Desktop ] Create SfSection

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#181]
The idea for this component is to create a responsive section wrapper as a general way to divide pages into sections.

The desktop look:
![image](https://user-images.githubusercontent.com/15185752/59421666-48c30d80-8dcf-11e9-8682-47e3937c0a40.png)
Mobile has 2 versions:
![image](https://user-images.githubusercontent.com/15185752/59421740-67c19f80-8dcf-11e9-987e-baf13656bc61.png)
and also closed one
![image](https://user-images.githubusercontent.com/15185752/59421892-b3744900-8dcf-11e9-8b0e-f0accdbd4f19.png)
Requires SfHeader component (currently blocked by it)

The API would be pretty simple:
For header options we will pass an object with SfHeader props.
For content there will be a slot
If someone wants it to be togglable on mobile (last example) maybe we should just pass `togglable` prop. I'm open to discussion on how we approach this.

CSS modifiers: `sf-section--underlined`

**Comment by leomp12** [comment]
It's not clear to me, this `SfSection` itself will not make the content responsive, right?
So with this component you're planning just to render the titles (eg.: _Share your look_) and subtitles (eg.: _YOURLOOK_), have a default slot for any content, centralize it by default and optionally make it toggable on mobile, right?

**Comment by leomp12** [comment]
I think you can add another modifier `sf-section--light` to have a gray light bg.
Not sure if you're thinking in another approach, but imo it may also have a SCSS var `$section-max-width` to work as a container, then it should also have a modifier `sf-section--fluid` to set full width.
