### ISSUE TITLE
[ Mobile / Desktop ] Implement SfCart

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#183]
Currently blocked by other issues and lack of full designs.
![image](https://user-images.githubusercontent.com/15185752/59423417-65ad1000-8dd2-11e9-8499-2f212b89e585.png)
![image](https://user-images.githubusercontent.com/15185752/59423437-7067a500-8dd2-11e9-9016-bb0347c70297.png)
![image](https://user-images.githubusercontent.com/15185752/59423673-e2d88500-8dd2-11e9-8f5f-7bf313eb1da1.png)
https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0

**Comment by leomp12** [comment]
@filrak what about `SfMinicart`? I think cart should refers to the shopping cart page...

**Comment by leomp12** [comment]
I can take care of it when unblocked (after `SfCollectedProduct` I think).
I'm available to discuss api first if someone wants to :)

**Comment by filrak** [comment]
@leomp12 sure, feel free to take ownership.https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/cart/components/Microcart.ts you may find this API helpful
