### ISSUE TITLE
[ Improvement ] Wrap SfCarousel arrows into slots

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#206]
Like in every other component we got carousel controls content should be replaceable via slot.

This two components in SfCarousel should be wrapped into slots and divs 9to preserve their position on left and right side). The slot should be inside div that positions the arrow in the right position and arrow should be inside a slot.

When someone replaces slot content with their own arrows should be automatically positioned on left and right side. 

I suggest arrow-left and arrow-right for slot names, keep in mind that go() function must be passed via scoped slot

This is a content I'm talking about
```HTML
    <SfArrow
      @click="go('<')"
      class="sf-arrow--long"
      aria-label="previous"/>
    <SfArrow
    @click="go('>')"
      class="sf-arrow--long sf-arrow--right"
      aria-label="next"/>
```

**Comment by filrak** [comment]
@peoray I unassigned you since you are busy with 2 more issues assigned to you and there is someone willing to take this one tight now

**Comment by michasik** [comment]
I'll take it
