### ISSUE TITLE
[ Desktop / Mobile ] Implement SfAddToCart molecule

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#207]
![image](https://user-images.githubusercontent.com/15185752/59773020-32c0bb80-92ad-11e9-951b-4198a404fd0b.png)
![image](https://user-images.githubusercontent.com/15185752/59773115-597ef200-92ad-11e9-9029-7e5458813f79.png)

Proposed api
```html
<SfAddToCart v-model="qty" @click="addToCart(product, qty)" />
```

If you have any suggestions to make this API better don't hesitate to propose it

**Comment by mayashavin** [comment]
@filrak isn't it need to have the icon of `add_to_cart` :)

**Comment by filrak** [comment]
According to our designer, nope ;)

**Comment by mayashavin** [comment]
@filrak 
1. Why are there 2 different designs ? if they are for different resolution, which is for which?
2. Don't we want to allow user to decide what the label should be? `Add to Cart` will be default, but if user wants to change to different text, he/she should be able to, right?
3. `qty` - is this max quantity?
