### ISSUE TITLE
[ RFP ] Theming Storefront UI

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#208]
## Question
The concept that I would like to see being widely used with Storefront UI is theming capability.

Let's say someone is willing to make custom SFUI theme to use components in his/her app. 
Are in-component SCSS vars enough to fulfill this need OR we need to think about CSS as a theme so sfui css = default theme, custom css = other theme.

## Idea 1
Current - via SCSS vars

## Idea 2
Treating CSS as a theme while keeping HTML and JS as SFUI base.

In `vue` package we have everything needed for components to work, in `shared` package we have icons and styles so basically everything that could be consider a theme.

StorefrontUI should support theming capabilities which means you should be able to simply replace `shared` package as a source of assets and styles for your components.

To make this possible we need two things:
- generic HTML (we will make sure our components HTML is generic before releasing beta)
- good API for theming

In theory every component should look more or less like this
```html
<script src="@storefrontui/vue/SfBreadcrumbs.js"></script>
<template lang="html" src="@storefrontui/vue/SfBreadcrumbs.html"></template>
<style lang="scss">
// theme css
</style>
```

But it requires people to actually create all those components. It would be much better if we could just override paths to default SCSS stylesheets. Even though the idea seems right I'm struggling with finding a proper way of handling this. 

Having such theming mechanism may potentially make our in-component SCSS vars redundant. Maybe we are trying to fulfill too many use cases with them instead of providing a general solution.

Please let me know what do you think about this idea and if possible propose how such theming API should work. Also please lmk if you think we still need in-component SCSS vars with such system. Let's make it great together ;)

**Comment by leomp12** [comment]
Second option sounds better, but I'm not sure if it works well with more complex components, even if we found a great API.
At the truth, I think SASS variables is good enough, I just think we should use more global variables, but it's also harder to style components with global variables then with internal ones, as we're doing now.
Maybe on next version we can do this migration from internals to globals (not only globals, but as possible).

**Comment by leomp12** [comment]
Actually, even with current HTML templates and BEM classes, the entire theme may be replaced, It's laborious and not so obvious, but it's possible.
For simple components we can make it simpler, but for complex components I can't see the same yet.

**Comment by leomp12** [comment]
Maybe we can just centralize the variables on just one file, as [Bootstrap does here](https://github.com/twbs/bootstrap/blob/master/scss/_variables.scss), and use less variables as possible.

Another idea (just a breath for now), maybe we can try to use same variables from Bootstrap 4 (just because it's the most popular CSS framework) as possible, then many people will be able to create a theme even before reading our documentation, just because they're already familiar with twbs, and many twbs themes would also work for sfui.

**Comment by filrak** [comment]
@leomp12 I agree that moving as global as possible is the way to go. In a long run I was thinking about replacing SCSS vars with CSS vars so we can make a WYSIWYG editor of this vars (with pages from `examples` folder on live preview) so people can adjust the vars and generate `sfui.scss` file. Going more global with vars will help with that a lot.

**Comment by filrak** [comment]
I'm not a big fan of Bootstrap vars though. Imho we should aim to have as fewer vars as possible while Bootstrap api is rather big. maybe we can use their approach as reference and try to minimize amount of variables?

**Comment by leomp12** [comment]
@filrak CSS vars sounds really good, but it's not so powerful as SCSS yet, and not fully supported (correct me if I'm wrong).
So replacing SCSS vars with CSS vars entirely we're discarding IE support, for example.
Anyway we can research and discuss more about this.

I agree that Bootstrap uses many variables, sure we can try to minimize.

**Comment by filrak** [comment]
Ok so we are leaving it to SCSS vars at least for v1 :) thanks for comments!
