### ISSUE TITLE
[ RFC ] Global color modifiers

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#209]
I've discussed with @filrak about creating common modifiers for components globally (as [Bulma](https://bulma.io/documentation/modifiers/) does), at least for colors.

So, some classes like `has-bg-primary` and `has-text-primary` should be created and available for all convenient components, then these components shouldn't have BEM modifiers specifically for the `primary` color.

Imo we should create these modifiers for `primary`, `secondary`, `danger`, `warning`, `info` and `success` colors, wdyt? The respective modifiers should be removed from components, we should use the global ones instead.

**Comment by filrak** [comment]
imho it's certainly the way to go. Could you propose the modifiers list @leomp12? Also I would love to hear opinions from @mayashavin @przspa @patzick @lauragift21 (even a short ones)

**Comment by mayashavin** [comment]
@leomp12 @filrak I agree on the global ones. We should have a global palettes and global sizes, this way we don't need to define again specific modifiers and make it harder to control the styling. You can check the implementation of the size in `SfIcon`. I would suggest we define something more specific rather than `pink-primary` and `pink-secondary` also.

**Comment by lauragift21** [comment]
This is a great idea @leomp12. I also believe this is the right way to go it helps us manage all color modifiers in one place.

**Comment by leomp12** [comment]
@filrak sure, I'll take care of it.

@mayashavin about sizes, I think it may be available for almost all atoms, right?
Although, I think it would be component specific, we can use modifiers with the same class names, but imo `.sf-price.lg` should apply different styles than `.sf-button.lg` for example, wdyt?

**Comment by mayashavin** [comment]
@leomp12 Indeed. Forgot that it need to be specific per component :)
