### ISSUE TITLE
[Reusable component] Move all svg files and icons.js to shared folder

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#223]
Need to move all `.svg` files and `icons.js` to `shared` package so other team can use the same icons

**Comment by peoray** [comment]
Can you provide more descriptions?

**Comment by filrak** [comment]
@peoray Icons are a shared resources so should be placed in `packages/shared/icons`

**Comment by filrak** [comment]
Please move ONLY icons that are listed in `icons.js`
