### ISSUE TITLE
[Design] All svg icons should follow same size (Material Icon standards)

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#224]
1. Current icons in SVGs are designed in different size, making it hard to control. 
2. Icons should have `viewBox` of `0 0 24 24` as in Material Icon guidelines

**Comment by mbaran-dvnt** [comment]
I've tried to make at simple as possible, some of the icons are bigger some of the are smaller. Please check if the groups of 42x42, 32x32, 26x26 is enough for you. Switching every icon to 24x24 will cause the problem of different states of icons in different views.

**Comment by pspaczek** [comment]
summon @pspaczek

**Comment by pspaczek** [comment]
@mbaran-dvnt we should adjust it to the same size. Now we have a problem with different icon sizes like on the bottom screenshot. 
![Zrzut ekranu 2020-04-23 o 08 57 07](https://user-images.githubusercontent.com/12138170/80068838-94425e00-8540-11ea-8faf-1d856d633402.png)

**Comment by mbaran-dvnt** [comment]
@pspaczek can you send me all of the icons that you already have in assets? This way it will be much more efficient for you and easier for me to create the same size icons. 
Cause I see you have more than it is in Figma already:)

**Comment by mayashavin** [comment]
@mbaran-dvnt it won't cause a problem if the icon is set to bigger size than the default 24x24 (not `viewBox`. Icon is scalable, respectively to `viewBox` dimension though, so even if an icon has `viewBox` it can be scaled to 42x42 without losing resolution or whatsoever.
@pspaczek FYI :)
