### ISSUE TITLE
[Cleaning] Change unnecessary relative imports to absolute

### ISSUE THREAD

**Issue by dimitor115** [DivanteLtd/storefront-ui#232]
I figure out that there are a lot of files in the project where relative imports were used over the absolute one. 

For example in the **SfAccordionItem.vue** there is import like this:
 `import "../../../../utilities/transitions/transitions.scss";` 
when `utilities` folder is directly unter the `src`, so we can use default vue-cli alias `~@/utilities/`.

Also, I personally think that `atoms`, `molecules` and `organisms` should be defined as direct alias in `vue.config.js`. These would allow as to avoid using relative imports in components, which are using some 'atoms' components etc.

**Comment by leomp12** [comment]
Sounds good, we should just take care to keep some files easy to reuse, even on environment without the aliases. @filrak wdyt? @dimitor115 can you propose a PR?

**Comment by dimitor115** [comment]
Yes, of course, I would like to do it and propose a PR, but maybe let @filrak firstly share his opinion :smile:

**Comment by michasik** [comment]
@dimitor115 
I would add tests files as well. I am on win10 and some paths are broken for me.

**Comment by dimitor115** [comment]
So guys @leomp12 @michasik which option is better in your opinion?
1. Just fix every import to be absolute and using standard vue-cli alias: `import SfArrow from "@/components/atoms";`
2. Extend webpack config :
```
 configureWebpack: {
    resolve: {
      alias: {
        atoms: "./src/components/atoms",
        modules: "./src/components/molecules",
        organisms: "./src/components/organisms"
      }
    }
  }
```
Then just: `import SfArrow from "atoms";`

**Comment by przspa** [comment]
@dimitor115 for me second option look more friendly. But we must use it like that `import SfArrow from "atoms/SfArrow/SfArrow.vue"` because by default when we use `import SfArrow from "atoms"` we import .js file?

**Comment by filrak** [comment]
Hey. The purpose for relwtive pathes is just to let people consume raw source..Correct me of I'm wrong but alias-based imports will break on others apps, right?

**Comment by dimitor115** [comment]
@filrak Yes, you are right. I totally forgot about the fact that we want people to consume raw source. However, I have another idea how to make imports a little bit nicer.
 So I can add `index.js` file in **atoms**, **molecules**, **organisams** with following content :
```
export { default as SfArrow } from "./SfArrow/SfArrow.vue";
export { default as SfBullets } from "./SfBullets/SfBullets.vue";
etc.
```
Then , for example in `SfHero.js` importing atomic components will look like this :
`import { SfArrow, SfBullets } from "../../atoms";`
Insted of this :
```
import SfArrow from "../../atoms/SfArrow/SfArrow.vue";
import SfBullets from "../../atoms/SfBullets/SfBullets.vue";
```

**Comment by filrak** [comment]
We have such stuff in `index.js` file in the root of the library. Then imports will look the same. The only thing i'm afraid of is that could break our `sideEffects: false` flag and therefore bundle unnecessary components in users bundle. Also this might introduce cyclical dependencies. 

I'm generally against such simplifications if they may produce some unexpected behaviors. Let me think about this for a while ok? Others are free (and strongly encouraged) to express their opinions

**Comment by filrak** [comment]
@dimitor115 I believe what we can do is changing all import paths to `index.js`. I just hope we won't run into any circular dependencies or break side effects flag. Would you be able to check it? For the side effects flag to check it what I do is :
1. setup project with vue-cli
2. install storefront ui locally (in `package.json` add `"storefrontui/vue" : "file://relative/path/to/sfui/on/your/pc"` and just run `npm install`
3. in node modules add random string to some component I'm not including
4. Import one or two sfui components in a project
5. Build and look for the string that shouldn't be there in output bundle (strings are not minified so it's easy to spot)

Could you repeat those steps after finishing the task? It shouldn't take more than 2-3 mins.

(you can also use webpack dependency graph inspector or bundle analyzer, whatever you find faster )

**Comment by dimitor115** [comment]
@filrak of course, I would check it!
