### ISSUE TITLE
[Documentation] - Create component document needs to be updated

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#246]
1. The note below is no longer relevant as it is fixed. Need to remove
<img width="727" alt="Screen Shot 2019-07-23 at 8 49 11" src="https://user-images.githubusercontent.com/6650139/61685922-d8d96880-ad26-11e9-9052-6b6148fff545.png">
2. The command `npm run create-component` doesn't need parameters anymore. Passing `atoms component-name` or `molecules component-name` will still display the configuration selection panel (see below).

<img width="854" alt="Screen Shot 2019-07-23 at 8 43 18" src="https://user-images.githubusercontent.com/6650139/61686044-37064b80-ad27-11e9-9ab0-fb8e37a2879c.png">

Need to update it with proper description and screenshot.

**Comment by leomp12** [comment]
Hey @mayashavin , I'm already purposing some edits on this guide [here](https://github.com/DivanteLtd/storefront-ui/pull/221), so I think we should wait this PR.

**Comment by mayashavin** [comment]
@leomp12 no problem :)

**Comment by leomp12** [comment]
hey @mayashavin it was updated, take a look: https://docs.storefrontui.io/creating-new-component.html#start-with-template
you think we still needing editions there?
