### ISSUE TITLE
 SfProductCard tweaks

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#249]
@mayashavin as we discussed 
- Remove onWishlistColor prop
- change onWishlistIcon and other on props to isOn
- Wishlist icon should always be visible when product is on wishlist
- wishlisticon prop should accept `false` and not display the icon

**Comment by leomp12** [comment]
Don't you think may be a good idea to also check if it's on cart?
In this case `isOn` would not be explanatory because we can have both "on cart" and/or "on wishlist".
I think it's really important for some segments, specially for supermarkets.

**Comment by filrak** [comment]
@leomp12 it's just a shortcut, basically, I meant changing `on` to `isOn`, sorry for the inconvenience

**Comment by leomp12** [comment]
@filrak don't be sorry haha
Btw, it was just a suggestion, wdyt about it? Did you understand what i meant?

**Comment by filrak** [comment]
Actually this feature is even designed so of course I agree. Its just not there yet. I think first we should add badges. This is one of the most important and complicated components so it's still missing important stuff

**Comment by mayashavin** [comment]
@filrak do we have badge design? like `sfbadge`? do you want to include here?

**Comment by mayashavin** [comment]
@filrak @leomp12 `onWishlistIcon` is actually the icon for when the product is already on wishlist, **not** a boolean :smiley: for indicating whether it's on or not. Maybe `addedToWishlistIcon`?
