### ISSUE TITLE
[ Mobile / Desktop ] Create SfNotification

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#250]
Desktop
![image](https://user-images.githubusercontent.com/15185752/61855239-01e13100-aec0-11e9-81b8-632e16b6852d.png)
Mobile (no icon, full width)
![image](https://user-images.githubusercontent.com/15185752/61855461-6603f500-aec0-11e9-8651-1bab1dc3bbe5.png)

Proposed API
```html
<SfNotification type="some types as SfAlert" message="" icon="string|boolean if false just don't show ">
```
Should have a default slot in case someone is willing to put a message with links.

**Comment by filrak** [comment]
@mayashavin I'm temporarily unassigning you before yesterday hackathon since you have 4 issues on yourself. If noone will take it tomorrow i'll reassign you :)

**Comment by leomp12** [comment]
It's also a good component to use color modifiers.
I would like to take this as an example right after [this PR](https://github.com/DivanteLtd/storefront-ui/pull/221) merged (will be ready today I guess).

**Comment by filrak** [comment]
Good idea :)

**Comment by filrak** [comment]
Issue si free since @leomp12 is currently busy ;)

**Comment by filrak** [comment]
@AdamPawlinski sure, no problem at all ;) Have you got a chance to finish this component on Monday?

**Comment by AdamPawlinski** [comment]
@filrak  Today it will be hard, I'm sorry.
