### ISSUE TITLE
[BUG] Storybook Organisms Footer is shown wrong on both mobile and desktop

### ISSUE THREAD

**Issue by MaciejWolowski** [DivanteLtd/storefront-ui#2500]
**Describe the bug**
Storybook Organisms Footer is shown wrong on both mobile and desktop

**How to reproduce**
1. Go to sfui1 storybook using mobile and desktop
2. Go to components -> organisms -> footer
3. Inspect screen

**Expected behavior**
Footer is shown correctly depending on the screen resolution and size.

**Actual behavior**
Component is shown wrong not right with diferent sizes.

**Screenshots**

<img width="2090" alt="image (1)" src="https://user-images.githubusercontent.com/103260041/200859821-5afcf0e0-b0ed-4a39-9c83-4a4f0d57e242.png">

**Devices (please complete the following information):**
 - Device: [Mobile, Desktop]
 - OS: [Ios and windows]
 - Browser: [e.g chrome, safari]

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-305) by [Unito](https://www.unito.io)
┆Link To Issue: https://vsf.atlassian.net/browse/SFUI-305

**Comment by AdamPawlinski** [comment]
I'm closing this ticket as it doesn't meet[ the requirements of LTS policy.](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page).
