### ISSUE TITLE
[ Mobile / Desktop ] Implement SfReview

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#252]
![image](https://user-images.githubusercontent.com/15185752/61865176-095e0580-aed3-11e9-86fe-979402b3d196.png)
Designs: https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0

Proposed API:
```html
<SfReview
  author="string"
  date="to be discussed"
  message=""
  rating="number/string"
  max-rating="number/string default: 5"
  char-limit="number/string default 250" 
/>
```
Char-limit can also be named better if you have any idea. It's just a limit of words after which we show "read more"
I'm not sure how we should approach date object. Imho it should expect a string instead of date object but I'm open for discussion

**Comment by Flyingmana** [comment]
I would like to pick this one

**Comment by dz3n** [comment]
PR is added
