### ISSUE TITLE
[Convention] Adjust scoped slots

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#254]
> Use scoped slots for markup customization and put template inside them<slot :prop="prop">//template</slot> instead of wrapping slot into a markup with v-for or click event. Just give people needed data properties and methods and let them handle whole section markup by themselves.

Make sure this rule is true for all components and adjust remaining ones.

Part of https://github.com/DivanteLtd/storefront-ui/issues/230

**Comment by leomp12** [comment]
Now all slots must be scoped, right? I mean, no more default slots?

**Comment by leomp12** [comment]
Just to confirm..
