### ISSUE TITLE
[ Mobile / Desktop ] Implement SfGallery

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#26]
Desktop:
![image](https://user-images.githubusercontent.com/15185752/55072178-b2623400-508a-11e9-87bf-a3be13b8c1f0.png)
Mobile:
![image](https://user-images.githubusercontent.com/15185752/55072249-e50c2c80-508a-11e9-80de-d119990568f6.png)

Implement mobile and desktop gallery component.
On mobile it should support touch events and be swappable.

Proposed API:
- images - (prop )Array of objects containing main image and optionally a thumbnail
- active (prop) - id of active image

Optional (if you don't handle it we can make separate issues)
- if there is a separate image for thumbnail main image should be loaded lazily
- add autoScroll prop and functionality

Please mind that it's just a proposal. We're open to discussion regarding component API.

Can be found on [designs](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0) on product pages.

**Comment by leomp12** [comment]
I could try, what do you think about adding a magnifier (zoom, [such as that component](https://akulubala.github.io/vue-product-zoomer/)) for desktop?

**Comment by filrak** [comment]
good idea, just make it optional

**Comment by leomp12** [comment]
I've found that Alpaca storybook already have a [gallery component](https://alpaca-storybook.now.sh/?path=/story/modules-gallery--default) (have you seen it?), but I don't know if it's ready, I'm thinking about doing some tests and try to let the gallery component based on alpaca's version, editing the styles and maybe applying more functionalities.
What do you think?

**Comment by filrak** [comment]
Sure, go for it but first check if it will not take more time than doing it by ourselves with some 3rd party lib ;)

**Comment by leomp12** [comment]
On mobile view, the dots are vertically listed, imo it's not the best option for user experience.
I think this takes the user to try vertical swipe, but we can't handle vertical swipe with this component because it would probably disturb the page scroll, so I think it's better to use horizontal list of dots, which is also more common.
What do you think?

**Comment by leomp12** [comment]
I've already made CSS styles following the current designs at the PR in progress, but I'll change it if you agree.

**Comment by Jensderond** [comment]
> I think this takes the user to try vertical swipe, but we can't handle vertical swipe with this component because it would probably disturb the page scroll, so I think it's better to use horizontal list of dots, which is also more common.

I agree
