### ISSUE TITLE
Broken styles on vue project build for production 

### ISSUE THREAD

**Issue by przspa** [DivanteLtd/storefront-ui#276]
Storefront-ui styles doesn't bundle on a production build but if you remove packega.json from @storefrontui/vue everything was work.

1. Created new vue app by vue-cli, 
2. Add @storefrontui/vue and 
3. Build app

![@](https://user-images.githubusercontent.com/12138170/62623637-a08a7a80-b921-11e9-883a-2190c6e47f20.png)

**Comment by filrak** [comment]
Ok i suspect it has something to do with `sideEffects: true` flag in package.json. CSS styles from shared package may be treated as side effects (because css is always a side effect) therefore not bundled

**Comment by filrak** [comment]
I'll try to fix this once I'm done with other issues but if we have someone adventurous feel free to pick this ;)

**Comment by filrak** [comment]
fixed https://github.com/DivanteLtd/storefront-ui/commit/5c7436a58ebdf290d5d744068e0520e62cfb49a9
