### ISSUE TITLE
[ Mobile / Desktop ] Implement SfCheckbox

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#28]
![image](https://user-images.githubusercontent.com/15185752/55075488-6667bd00-5093-11e9-8afb-21fd9d208e7c.png)
![image](https://user-images.githubusercontent.com/15185752/55075525-7d0e1400-5093-11e9-8ae7-3a8d214a3090.png)

Use alpaca component as a base (already included as a dependency)
https://alpaca-storybook-ebth12xpx.now.sh/components/?path=/story/elements-form-checkbox--default. (https://github.com/SnowdogApps/alpaca-storybook/tree/develop/components/src/02-elements/checkbox)

You can safely import JS part and just override HTML SCSS to match our design

Read more in [Working with Alpaca](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/working-with-alpaca.md)

It should incude
- prop label to fill default slot with label
- default slot with content of "label" slot that can be used to add custom markup

Can be found on [designs](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=497%3A782) on `IPhoneChackoutPersonal Details` and `IPhone/Checkout/Review Order` (checked)

**Comment by MikeSheward** [comment]
I'll have a crack at this.
