### ISSUE TITLE
[ Mobile / Desktop ] Create SfCombinations

### ISSUE THREAD

**Issue by cristian-g** [DivanteLtd/storefront-ui#283]
## What is the motivation for adding / enhancing this feature?
Suggesting product combinations increases endgagement and makes the user to add more products to the cart.
This is pretty usual in the fashion industry, as it serves as an "outfit gallery". It is an image gallery where each image has a list of products (typically, a shirt, jeans and shoes).

It would be used on the product page, so combinations there would include the product that the user is seeing info about.

It is usefull also in other industries: technology industries can show combinations of computers and screen, keyboard, mouse...

## What are the acceptance criteria
* User can navigate using left and right arrows to see more combinations (e.g. outfits).
* Each image has a list of products (e.g. a shirt, jeans and shoes).

## The screenshots

* Desktop
![desktop1](https://user-images.githubusercontent.com/15870631/63106231-b1229c80-bf82-11e9-8647-ca067dc0706d.png)
![desktop2](https://user-images.githubusercontent.com/15870631/63106247-b8e24100-bf82-11e9-8dfa-3ad4acd9900d.png)
![desktop3](https://user-images.githubusercontent.com/15870631/63106254-bd0e5e80-bf82-11e9-9261-255d8ad443f4.png)

* Mobile
![mobile1](https://user-images.githubusercontent.com/15870631/63106271-c4ce0300-bf82-11e9-8b32-9a642bc7bdef.jpg)
![mobile1-2](https://user-images.githubusercontent.com/15870631/63106281-c7c8f380-bf82-11e9-8436-a0f8d0a9e57f.jpg)
![mobile2](https://user-images.githubusercontent.com/15870631/63106288-cb5c7a80-bf82-11e9-87bd-f55dcb3cfb0f.jpg)
![mobile3](https://user-images.githubusercontent.com/15870631/63106291-cd263e00-bf82-11e9-8b75-4cf3ef82fd71.jpg)

## Online demo
Available at:
https://www.zalando.co.uk/levisr-sportswear-polo-shirt-dark-blue-le222p00v-k11.html

## Can you complete this feature request by yourself?
* [ ]  YES
* [x]  NO

**Comment by filrak** [comment]
I think we need some designs here
