### ISSUE TITLE
SfProperty Adjustments and rename

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#285]
1. Adjust color:
![image](https://user-images.githubusercontent.com/15185752/63226715-d7904400-c1dd-11e9-9273-516506239bff.png)
vs
![image](https://user-images.githubusercontent.com/15185752/63226717-e0811580-c1dd-11e9-9b8d-7f4829df4ac5.png)
2. add `full-width` modifier
![image](https://user-images.githubusercontent.com/15185752/63226728-fbec2080-c1dd-11e9-983e-037b3a95af47.png)
3. Rename to `SfLabeledItem`

**Comment by mayashavin** [comment]
@filrak not sure `SfLabeledItem` is a good name here

**Comment by filrak** [comment]
@mayashavin me either just SfProperty seem bad to me. Or maybe it is just me? can you give a second opinion?
