### ISSUE TITLE
[ Mobile / Desktop ] Implement SfOptions

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#29]
![image](https://user-images.githubusercontent.com/15185752/55146285-8dca9280-5144-11e9-8564-2d5ff61ba409.png)

Implement SfOptions component based on Alpaca swatch https://alpaca-storybook-ebth12xpx.now.sh/components/?path=/story/elements-swatch--default

The API can remain the same so the task involves only custom styling

Read more in [Working with Alpaca](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/working-with-alpaca.md)

**Comment by runyasak** [comment]
Hi, I'm World from Twitter DM.
I would like to pick this issue to do.
Please, assign this issue to me. Thank you 😎

**Comment by filrak** [comment]
Hey, i forgot to post mobile version, sorry 
![image](https://user-images.githubusercontent.com/15185752/55224056-e61a9680-520f-11e9-9746-f6168a635cfa.png)

can be found on this board: 
![image](https://user-images.githubusercontent.com/15185752/55224167-398ce480-5210-11e9-91c7-cfb0cef262d0.png)

**Comment by filrak** [comment]
also confirm your invitation on email so i can assign you ;)

**Comment by runyasak** [comment]
@filrak I have confirmed from email already. Please, assign me. 😎

**Comment by runyasak** [comment]
@filrak I have create PR for my progress and need some comments from you. Please, checkout on this PR #46
