### ISSUE TITLE
Add SFUI favicon to docs and storybook

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#291]
Add favicons to our storybook and docs. They can be taken from https://divante.co/open-graph/favicons_storefrontui/sfui_favicon-32x32.png

**Comment by LadyMashiro** [comment]
Would love to do this 😁

**Comment by mayashavin** [comment]
@LadyMashiro hey have you started yet? If not, I will take this one as I'm doing the contribution guide and can add it together :). Lmk

**Comment by LadyMashiro** [comment]
Hey Maya, no I haven’t stared yet. That would be awesome :)

Maya Shavin <notifications@github.com> schrieb am Di. 3. Sept. 2019 um
18:04:

**Comment by mayashavin** [comment]
@LadyMashiro awesome :) Thanks <3
