### ISSUE TITLE
SfImage improvements

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#292]
We need a few improvements on SfImage
1. Make image load lazily (add prop `lazy` defaulting to `true`)
2. Add placeholder (prop `placeholder`)

**Comment by leomp12** [comment]
Browser native lazy load stills on very early stages ([only Chrome supports](https://caniuse.com/#search=lazy)), lozad is already being used on `SfGallery` so I think we should also use it on `SfImage`.

Additionally, would be good to optionally render a [`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture), I would suggest to receive a src string on prop or a picture object with multiple sizes, wdyt?

**Comment by leomp12** [comment]
We have talked about on dicord...

**Comment by leomp12** [comment]
@matheusgnreis

**Comment by leomp12** [comment]
@talissonf @matheusgnreis

**Comment by filrak** [comment]
@leomp12, 100% agree on both points ;)
