### ISSUE TITLE
Get rid of all '--secondary' modifiers

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#295]
Since we are relying now on utility classes we should get rid of those modifiers that are redundant.

You can find them in SCSS files of `shared` package. The task is just to remove them ;)

**Comment by dbolufer** [comment]
👋 Can I pick this issue?

**Comment by jahvi** [comment]
Glad to see you around these parts @dbolufer, go for it!

**Comment by filrak** [comment]
The issue is free to pick ;)
