### ISSUE TITLE
[Documentation] Add content to FAQs section

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#322]
FAQs section is located in `github-guidelines.md`. We need to ask some common questions for contributors in working with Github repo.

**Comment by filrak** [comment]
@mayashavin do you have any references?

**Comment by mayashavin** [comment]
@filrak Looking for one :)

**Comment by martaradziszewska** [comment]
@mayashavin FAQ section sounds great! do you need some help with it?

**Comment by mayashavin** [comment]
@martaradziszewska currently in need for some basic questions to start with. If you have a list of questions, go ahead!
