### ISSUE TITLE
[ Mobile / Desktop ] Implement SfSteps

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#33]
Desktop
![image](https://user-images.githubusercontent.com/15185752/55168329-ed3f9700-5172-11e9-94b1-86281547a285.png)
Mobile
![image](https://user-images.githubusercontent.com/15185752/55168448-211abc80-5173-11e9-9223-5cea9b30bd98.png)

Proposed API (open for discussion)
- Simple version with props
````html
<SfSteps :steps="steps" @change="" active=""/>
````

Can be found on [designs](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=300%3A7) on checkout boards

**Comment by techlab23** [comment]
@filrak  Can you assign it to me ?

**Comment by filrak** [comment]
@techlab23 are you still willing to work on this?
