### ISSUE TITLE
[Mobile / Desktop ] Add animation to sf-steps

### ISSUE THREAD

**Issue by DonNicoJs** [DivanteLtd/storefront-ui#335]
Currently the line showing `current` and `done` step is not animated when the user click.
We would like to add animation.

Nb: currently the component utilise a trick to show the line stopping under the end of the text on `current` element. This trick will render the animation much harder if not possible. 
Reworking the trick may be necessary

**Comment by jahvi** [comment]
I'll give it a go 👍🏽
