### ISSUE TITLE
Automate Creation of Component Docs

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#337]
## Status Quo
Currently, each component docs page needs to be created manually (eg. by copy&pasta from an existing component.md).

## Issue
This way, repetitive work has to be done and chances are high these docs pages become inconsistent.

## Proposed Changes
This work can be automated via a (yarn) script target. Most parts of the information on the component docs pages can be extracted from the corresponding _.stories.js_ file.

### Note
The exact location for the information needed has to be evaluated. Eg. the info about slots/props/events is not present in the stories file.

**Comment by EduardDopler** [comment]
I'd appreciate tips on where to extract the information from (besides the _.stories.js_ file).

**Comment by filrak** [comment]
Thanks for your help! This script will save us a looooot of time and I'll be happy to help you with this if any help will be needed
Regarding props/slots you can get ti via https://www.google.com/search?q=vue+docgen&oq=vue+docgen&aqs=chrome..69i57j0l2j69i64l2.1409j0j7&sourceid=chrome&ie=UTF-8
Regarding SCSS vars extracting them from top of each file should be trivial

**Comment by filrak** [comment]
Storybook plugin (Info(vue) section) that we use to collect information about slots/props/events is using the same tool

**Comment by filrak** [comment]
Exactly as you described except one thing

Play with this component can be generated under the condition of renaming every 1st story of given component to "Basic" (it will be renamed anyway).

Then URL looks like this: `https://storybook.storefrontui.io/?path=/story/atoms-arrow--basic` so we can generalize it to ``https://storybook.storefrontui.io/?path=/story/{group}-{name-without-prefix}--basic`

**Comment by filrak** [comment]
I also found information about this:
https://medium.com/storybookjs/storybook-docspage-e185bc3622bf and
https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md

This might be also way to go but I'm not sure if it won't be hard to add custom and generated stuff into these files. WDYT?

**Comment by EduardDopler** [comment]
My current approach is the following:
We have one **component-docs-template.md**  and many **ComponentName.md** files for custom placeholder values which can not be extracted from somewhere else (like the usage).

### component-docs-template.md
````md
# [[component-name]]

[[component-description]]


[[toc]]


## Most common usage scenario

### Demo

<br><[[sf-component-name]] />

### Source

[[usage-source]]


## Props

[[props]]


## Slots

[[slots]]


## Events

[[events]]


## CSS modifiers

[[css-modifiers]]


## SCSS variables

Below you can find the default SCSS variable values bound to this component. You can override them in `sfui.scss` in the root of your project.

[[scss-variables]]


## Partials

If you want to customize this component even more you can use its partials for limitless customization.

```html
<template lang="html" src="@storefront-ui/vue/src/components/[[atomic-type]]/[[sf-component-name]].html"></template>
<script src="@storefront-ui/vue/src/components/[[atomic-type]]/[[sf-component-name]].js"></script>
<style lang="scss">
@import "~@storefront-ui/shared/styles/components/[[sf-component-name]].scss";
</style>
```

You can read about using component partials [here](docs.storefrontui.io/customization)


## Play with this component

See all available configurations and play with this component on <a href="https://storybook.storefrontui.io/?path=/story/[[storybook-link]]">Storybook</a>.
````

### SfArrow.md
````md
# component-name
Arrow

# component-description
Description of Arrow

# usage-source
```html 
<template>
  <SfArrow />
</template>

<script>
import { SfArrow } from '@storefront-ui/vue'

export default {
  components: {
    SfArrow
  }
}
</script>
```

# storybook-link
atoms-arrow--basic
````

The other placeholders (like props, events, etc.) will be replaced with information from the source code (e.g. via _vue-docgen-api_).

**Comment by filrak** [comment]
Looks good to me! Only the headings in _most common usage scenario_ seem redundant (especially for small components) + keep in mind that `sf-component-name` in partials should be CamelCase

**Comment by EduardDopler** [comment]
Some news from my side: I make good progress on this issue. So I think I will incorporate the extraction of (S)CSS variables/modifier from the style files.

I'd suggest this syntax (similar to the `<-- @slot -->` syntax from vue-docgen):
```scss
// @modifier Change badge style to "warning" variation
&--warning {
  background-color: $badge--warning;
}
```

___

One more thing: To make this whole story fully automated, we'd also need to make changes to the _.vuepress/enhanceApp.js_ and _.vuepress/config.js_ files. Should I make the script do it? Or do you want to just output the changes which need to be done? Or neither?

**Comment by EduardDopler** [comment]
SCSS: Done.
I had to change the syntax a bit (making the modifier descriptions `/* @modifier Text */`-(block-)style because `//`-(line-)style comments get removed by the SASS compiler). But now the *generation of components docs files is complete*, as far as I can tell.
Of course we'd need to create the "component extra info" Markdown files sometime (for the common usage parts etc.)

Should I open a PR for that or should I complete the above-mentioned task first (insertion into _.vuepress/enhanceApp.js_ and _.vuepress/config.js_)?
