### ISSUE TITLE
Add active state for SfBottomNavigationItem

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#338]
Currently every element on SfBottomNavigation looks the same. It's a good UX practice to differentiate currently active element.

The task is to:
1. Make other icons grayed or with a transparency (90% visible)
2. add `sf-bottom-navigation-item--active` CSS class
3. Include it as an example in storybook

Below example of active menu element:
![image](https://user-images.githubusercontent.com/15185752/65030009-103b4e80-d93f-11e9-8027-6a24100d817e.png)

**Comment by thiagoabreudev** [comment]
Hi @filrak  , in SfBottomNavigation there is already the css modifier `sf-bottom-navigation__item--active`. There opacity is set to 1, while sf-bottom-navigation__item has opacity: 0.7. This create this effect.
![sf-bottom-navigation__item--active](https://user-images.githubusercontent.com/4981847/66243295-78798680-e6da-11e9-9446-4555471fb59b.png)

Do you want me to change this existing style, or prefer to keep this style?
