### ISSUE TITLE
[Automation] Write script generating index.js and js.js

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#340]
For now, we need to add components to root imports manually in `packages/vue/index.js` and `js.js`.

The task here is to create a node script traversing through the file tree and generating this file automatically. You can safely just use folder names to generate those imports.

**Comment by EduardDopler** [comment]
Maybe some parts of my component docs script (_create-vue-components-docs.js_) from PR #354 can be reused. There is already logic for inserting all components and their imports for the VuePress config files.

This is marked as "good first issue" but as I'm already "familiar" with this requirement, I could take care of it?

**Comment by filrak** [comment]
@EduardDopler that would be awesome. I cannot imagine a better person.
