### ISSUE TITLE
[A11y] Fix accesibility issues for SfArrow

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#341]
![image](https://user-images.githubusercontent.com/15185752/65074052-540c7300-d994-11e9-975b-3b25a6a770d5.png)

They can be found in "accessibility" section in storybook https://storybook.storefrontui.io/?path=/story/atoms-arrow--basic

**Comment by mayashavin** [comment]
@filrak can you add @jahvi as a contributor and assign this to him to avoid people picking it by mistake?
