### ISSUE TITLE
[Storybook] Change all CSS modifiers selects in Knobs section to options

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#342]
Currently some of the CSS modifiers in `Knobs` section on storybook are select lists like this.
![image](https://user-images.githubusercontent.com/15185752/65075268-e4e44e00-d996-11e9-95fa-ff29d655adde.png)
Instead we should always provide select to enable multiple choices:
![image](https://user-images.githubusercontent.com/15185752/65075319-fb8aa500-d996-11e9-9827-55c53068cfec.png)
The task is to change all SCSS modifier selects to options (`select` example - `SfBadge`, `options` example `SfArrow`)

Stories can be found under `*.stories.js` files

**Comment by jahvi** [comment]
Hey! Just opened #361 to address this, I only found the Searchbar and Counter components using it, not sure if I missed anything.
