### ISSUE TITLE
Add secondary modifier for button

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#343]
Add `sf-button-secondary` SCSS modifier in `SfButton.scss` (shared package).
It should look more or less like this (border with text, transparent background)
![image](https://user-images.githubusercontent.com/15185752/65076701-c7fd4a00-d999-11e9-8400-5c9f01aef23d.png).
keep in mind it should work with utility classes like `color-primary, `color-secondary`

Also add this modifier to `CSS modifiers` in knobs section of Storybook. (`SfButton.stories.js`)
In case of any questions feel free to join our Discord server (link in readme)

**Comment by thiagoabreudev** [comment]
Hello! I would like to work on this issue @filrak .

**Comment by filrak** [comment]
Thank you very much, I sent you an invite, once you accept it you can assign yourself

**Comment by przspa** [comment]
@thiagoabreudev how do you doin :) can I help you?

**Comment by thiagoabreudev** [comment]
Hi @przspa, Thanks so much for your help. I had a question of understanding and was talking to @leomp12 . My question was about the "keep in mind it should work with utility classes like color-primary, color-secondary" process. I understand that the button will always have a transparent background, but when you pass the primary or secondary color modifiers, it will change to border and text color, giving an empty button (outline) effect, is it the same? or did I get it wrong?

**Comment by leomp12** [comment]
@filrak @przspa what about `sf-button-outline` instead of `sf-button-secondary` modifier? `secondary` usually refers to the color...
