### ISSUE TITLE
Replace SfChevron isActive prop with CSS

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#347]
Instead of `isActive` it should be just a css class named `sf-chevron--top`. You should also take care of all components using `SfChevron` and make sure they work as previously.

**Comment by gibkigonzo** [comment]
@filrak Can you assign me?
For clear you want to remove `isActive` prop and pass responsibility of changing SfChevron to higher order components?
`<SfChevron  :class="{'sf-chevron--top': active}" />`

**Comment by przspa** [comment]
thanks @gibkigonzo
