### ISSUE TITLE
Unify info/alert/warning for all components

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#357]
So it is the same across project and uses same scss vars and modifiers

**Comment by filrak** [comment]
@przspa can you take care of this ?

**Comment by przspa** [comment]
@filrak https://docs.storefrontui.io/contributing/creating-new-component.html#edit-styles adjust it to global color modifire?

**Comment by filrak** [comment]
Actually in many of them icon also differs so `type` prop seems best
