### ISSUE TITLE
[ Tests ] Write unit tests for SfPagination

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#38]
![image](https://user-images.githubusercontent.com/15185752/55223393-65a76600-520e-11e9-96c0-c27536e43f2c.png)

Just adjust designs of the alpaca one leaving business logic untouched.

https://alpaca-storybook-ebth12xpx.now.sh/components/?path=/story/modules-pager--default
https://github.com/SnowdogApps/alpaca-storybook/tree/develop/components/src/03-modules/pager

Also read [Working with Alpaca](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/working-with-alpaca.md)

Can be found on [designs](https://alpaca-storybook-git-develop.snowdog1.now.sh/?path=/story/elements-form-checkbox--default) on category page

**Comment by leomp12** [comment]
Have you already tried to import some component from `@snowdog/alpaca-components`?
I couldn't import it at all, maybe I'm doing something wrong but don't know what.
Error with `@snowdog/alpaca-components/dist/Pager.vue`:
```
Module not found: Error: Can't resolve '../../02-elements/button/Button.vue'
```
With `@snowdog/alpaca-components` or even `@snowdog/alpaca-components/Pager.vue` (just to give a try):
```
Module not found: Error: Can't resolve '@snowdog/alpaca-components'
```

**Comment by filrak** [comment]
I guess it's just a problem with their local pathes. Please make an issue in alpaca repo and in the meantime just copy the files to SfPagination component folder in some temporary subdir until they'll fix

**Comment by leomp12** [comment]
my failure actually, the package was outdated, 0.1.x-alpha on `package.json`, and now it's 0.3.x-alpha

**Comment by leomp12** [comment]
Missing more unit tests for the component, mainly for props.
