### ISSUE TITLE
vuepress/lib/default-theme/util imports causing errors

### ISSUE THREAD

**Issue by PSDoff** [DivanteLtd/storefront-ui#383]
**node_modules/@storefront-ui/vue/src/components/molecules/SfSlidingSection/SfSlidingSection.js**
`import { isActive } from "vuepress/lib/default-theme/util";`

The import declarations of this file causes the following error after a fresh install (as of October 4th, 2019). Removing the import removes the error.

```ERROR in ./node_modules/@storefront-ui/vue/src/components/molecules/SfSlidingSection/SfSlidingSection.js?vue&type=script&lang=js&
Module not found: Error: Can't resolve 'vuepress/lib/default-theme/util' in '/Users/asomerville/Documents/demac_sites/shopify-spa/node_modules/@storefront-ui/vue/src/components/molecules/SfSlidingSection'```

**Comment by DonNicoJs** [comment]
I'll take a look at this

**Comment by DonNicoJs** [comment]
@PSDoff This just need an update npm package, the code is already updated!
