### ISSUE TITLE
[Docs] Create missing component docs

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#420]
**Progress of components docs for all components.**

_unchecked: To Do_
_checked: WIP or PR pending_

### Atoms
- [ ] atoms/SfIcon
- [ ] atoms/SfImage
### Molecules
- [x] molecules/SfAddToCart
- [x] molecules/SfAlert
- [x] molecules/SfBanner
- [ ] molecules/SfCallToAction
- [ ] molecules/SfCharacteristic
- [ ] molecules/SfCounter
- [ ] molecules/SfFilter
- [ ] molecules/SfGallery
- [ ] molecules/SfMenuItem
- [ ] molecules/SfModal
- [ ] molecules/SfNotification
- [ ] molecules/SfOptions
- [ ] molecules/SfPagination
- [ ] molecules/SfProductOption
- [ ] molecules/SfRadio
- [ ] molecules/SfReview
- [ ] molecules/SfSearchBar
- [ ] molecules/SfSection
- [ ] molecules/SfSelect
- [ ] molecules/SfSlidingSection
- [ ] molecules/SfSteps
- [ ] molecules/SfSticky
### Organisms
- [ ] organisms/SfAccordion
- [ ] organisms/SfBannerGrid
- [ ] organisms/SfBottomNavigation
- [ ] organisms/SfCarousel
- [ ] organisms/SfCollectedProduct
- [ ] organisms/SfHeader
- [ ] organisms/SfHero
- [ ] organisms/SfList
- [ ] organisms/SfMegaMenu
- [ ] organisms/SfProductCard
- [ ] organisms/SfSidebar
- [ ] organisms/SfStoreLocator
- [ ] organisms/SfTabs
- [ ] organisms/SfTopBar

## ✅ Done
- [x] atoms/SfArrow
- [x] atoms/SfBadge
- [x] atoms/SfBreadcrumbs
- [x] atoms/SfBullets
- [x] atoms/SfButton
- [x] atoms/SfCheckbox
- [x] atoms/SfChevron
- [x] atoms/SfCircleIcon
- [x] atoms/SfDivider
- [x] atoms/SfHeading
- [x] atoms/SfInput
- [x] atoms/SfLoader
- [x] atoms/SfOverlay
- [x] atoms/SfPrice
- [x] atoms/SfProperty
- [x] atoms/SfRating

**Comment by peoray** [comment]
I'm interested in this. How do I proceed?

**Comment by EduardDopler** [comment]
Hey @peoray! Thank you for your interest. This issue doesn't reflect the latest changes on this topic though; @aniamusial and I, we have work going on in #480 and #502. Once they are merged, this issue will be resolved.

To not further confuse others, I's better close it now though.
