### ISSUE TITLE
[RFC] Limit number of SCSS vars to certain properties

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#445]
Imho many SCSS vars should be removed for the sake of easier maintenance.

I suggest keeping:
- `color`
- `font-size`
- `padding`
- `margin`
- `background-color` (if present)
- `drop-shadow` (if present)

And add new one - `order` for child elements.

**Comment by EduardDopler** [comment]
In general, I like the idea. Some vars allow too fine-grained changes.
But I wouldn't limit to only those you mentioned. For example, `$bullet-border-radius` allows switching from rounded to rectangular bullets which seems like a useful modification for users.
Maybe we need to decide from case to case ("from SCSS var to SCSS var")?

**Comment by filrak** [comment]
@EduardDopler good point ;) Yeah I think there might be some cases when we would like to provide more vairiables depending on a component but above should be treated as a rule of thumb. We definitely have too much variables. The reasoning behind introducing them was to have variable-based visual configuration that is not tied to implementation details like markup so (in theory ^^) it's more bulletproof in case of updates

**Comment by leomp12** [comment]
As @EduardDopler said, Imo it's very relative, maybe we should discuss it individually for some components before trying a full refactor and new composition rules..

**Comment by filrak** [comment]
Ok, I will start proposing a PR's. Maybe we can somehow divide those components between ourselves?
Also we should start with introducing CSS vars instead of SCSS ones for components. It's important to allow scoped overrides.

Also we will probably need easier naming convention that is not tied to BEM anymore. I'll ry to figure out something in the upcoming days and present you as PR with RFC :)

**Comment by leomp12** [comment]
@filrak we can divide the components, just wait your PR to discuss and to have more defined conventions.
About CSS vars for components, I like the idea, just not sure about performance with many CSS vars.

**Comment by filrak** [comment]
@leomp12 i think at the end user can translate them to "normal" css on production. I didn't know css vars are a performance concern though. Do you have any date on their impact?

**Comment by leomp12** [comment]
Nope, I'm not an expert, it's more empirical, but we can find some articles searching a little...
Assuming on average 5 vars per component, we may have more than 350 CSS vars :open_mouth:
Never seen anything close to it to use as a parameter.

Maybe we can keep with SCSS and use CSS vars just for colors (or maybe some more properties, but not all suggested)?

I don't know if we can translate it, do you know any tools that do this?

**Comment by DonNicoJs** [comment]
> Maybe we can keep with SCSS and use CSS vars just for colors (or maybe some more properties, but not all suggested)?

I would not mix two approaches, it's a recipe for headache and confusion the more we grow.

> And add new one - order for child elements.

I think this deserve a separate discussion RFC ? what do you guys think ?

**Comment by leomp12** [comment]
> I would not mix two approaches, it's a recipe for headache and confusion the more we grow.

@DonNicoJs You're right, bad idea :stuck_out_tongue_winking_eye:

> I think this deserve a separate discussion RFC ? what do you guys think ?

I think you're right again haha

**Comment by filrak** [comment]
@leomp12 we can translate it, there are webpack loaders for this.

Imho all configuration shoudl be inscss vars to enable scoped configurations

**Comment by filrak** [comment]
Small update. We can think about this variables in a more declarative way, not exactly as a BEM representation of component structure. It will make them more future-proof (if structure change) and more understandable to designers.

**Comment by pspaczek** [comment]
add to #733
