### ISSUE TITLE
Change property names of src in SfImage

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#447]
Instead of `small` and `normal` perhaps we could use `mobile` and `desktop` which is more descriptive and can't be misunderstood (for example `small` can be misunderstood as thumb or sth)

@leomp12 ?

**Comment by leomp12** [comment]
Yup, sounds better!
Just to remember, it would be a breaking change, `SfGallery` and `SfProductCard` must be updated after that.

**Comment by leomp12** [comment]
I'll take it

**Comment by leomp12** [comment]
@NessaMr

**Comment by filrak** [comment]
@leomp12 awesome, thanks. Yeah I'm aware of it
