### ISSUE TITLE
Using inline SVGs instead of img tags for icons

### ISSUE THREAD

**Issue by marvinhuebner** [DivanteLtd/storefront-ui#45]
First of all: We are currently evaluating VS for new projects and I have clicked through here a little bit. I think storefront ui is a very solid foundation, especially for theme 2.0. I would have some thoughts about that, i hope it's ok.

I've seen that currently simple `img` tags are used for icons and want to ask if there have ever been any thoughts about using inline SVG's. For example with the help of the [vue-svg-loader](https://github.com/visualfanatic/vue-svg-loader)

I have already used it in some projects and could also help with the implementation.

I see limitations by using img tags for icons. If you use the SVG's directly you can style them e.g. via css. There is a lot more scope for customization (Custom colors, Hover styles).

I am looking forward to feedback and your thoughts!

**Comment by filrak** [comment]
I know that using svg in img tag has some styling limitations and this is why usually every img tag is placed in a slot that can be replaced. Is this what you're asking for or you'd like to see more direct way of including svgs? (like a special slot directly over every img tag) 



Is that what fulfils your needs or you'd like to see more direct way to use svg instead of img?

**Comment by marvinhuebner** [comment]
I've seen that almost every icon is placed in a slot. 

I was just thinking about why this limitation is integrated right from the start. 

When I'm looking at the alert component PR (https://github.com/DivanteLtd/storefront-ui/pull/31/files#diff-cdc78315299615709d1f22eb8f798bfaR3), I have the following in mind:

(Code is not tested, only a boilerplate)

```html
<template>
  <div class="sf-alert" :class="`sf-alert--${type}`">
    <slot name="icon" :icon="icon">
      <component :is="iconSrc" class="sf-alert__icon" v-if="icon"></component>
    </slot>
    <slot name="message" :message="message">
      <p class="sf-alert__text"  v-if="message">{{ message }}</p>
    </slot>
    <slot />
  </div>
</template>

<script>
  // Manually import could be replaced through automatic global registration
  // @see https://vuejs.org/v2/guide/components-registration.html#Automatic-Global-Registration-of-Base-Components
  import SfSvgAlert from '/assets/alert-alert.svg?inline';
  import SfSvgWarning from '/assets/alert-alert.svg?inline';
  import SfSvgSuccess from '/assets/alert-alert.svg?inline';

  export default {
    name: "SfAlert",
    props: {
      message: String,
      icon: {
        default: true
      },
      type: {
        type: String,
        default: "alert"
      }
    },
    computed: {
      iconSrc() {
        return typeof this.icon === "string"
          ? this.icon
          : `SfSvg${upperFirst(this.type)}`;
      }
    }
  };
</script>
``` 

This would give you the possibility to style the icons with css and if someone really wants to use `img` for icons, then he can still replace them via the slot.

But I can imagine, that by using inline SVG's it is often not necessary anymore to replace them with  own icons.

**Comment by filrak** [comment]
Hey,
Since this behavior requires additional dependency to be installed on the project using SFUI it's not suitable for us.

 I want to fulfil your needs though so we just make sure that every `<img>`tag is placed inside a slot. This way you can pass every image and svg into a `img` tag like before but replacing it with inline SVG will be as simple as passing the prop.

**Comment by marvinhuebner** [comment]
Hey @filrak,

with the extra dependency, that's a good point, of course. I've only used the `vue-svg-loader` at project level so far and not at library level, i hadn't considered that. 

I just checked how other ui librarys solve it, but nobody seems to use svgs, they use mostly icon fonts.

But thanks for your efforts!
