### ISSUE TITLE
[BUG] Storybook "filter" displays color even if "color" is "null"

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#452]
**Describe the bug**
SfFilter on storybook shows color even if it's `null`

**How to reproduce**
1. Go to https://storybook.storefrontui.io/?path=/story/molecules-filter--basic
2. Select 'color' to null
3. Color is still visible

**Comment by EduardDopler** [comment]
Fixed in #429 (aa0d3cf). Currently in develop branch.
