### ISSUE TITLE
[BUG] SearchBar issues

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#457]
1. Placeholder is still visible if we focus input window
![image](https://user-images.githubusercontent.com/15185752/69045572-65efae00-09f7-11ea-8fa8-71fa1e8a3882.png)
It shold be hidden once there is a focus on input

2. Clicking "x" does not clear the text field
![image](https://user-images.githubusercontent.com/15185752/69045620-81f34f80-09f7-11ea-9fb2-145c97e44989.png)

3. "Icon" is a prop where it should be a SCSS modifier "no-icon"

**Comment by DonNicoJs** [comment]
On it!
