### ISSUE TITLE
[feature] Implement vue-simple-portal for modals and overlays

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#466]
# Description
Implement vue-simple-portal (https://github.com/LinusBorg/vue-simple-portal) to remove all the z-index across the app.

**Comment by leomp12** [comment]
@aniamusial why not [`portal-vue`](https://github.com/LinusBorg/portal-vue)?
I think it's more common and stable than `@linusborg/vue-simple-portal`.
Despite being heavier, users and libraries often use the `portal-vue` (I guess), so adding it to dependencies would not increase the bundle in most cases.

**Comment by filrak** [comment]
@leomp12 this lib is from the same author and is much smaller. The fact is we don't need what vue-portal offers. Just this simple behavior from vue-portal is enough. 

Regarding potential usage of this lib by other libs - they will probably use other versions anyway so we won't benefit from this potential perf boost.

**Comment by filrak** [comment]
@aniamusial I think we should extend scope of this issue to:
- SfSidebar
- Mobile version of SfOptions
