### ISSUE TITLE
[feature] Add size props for SfImage

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/storefront-ui#474]
SfImage component should have the possibility to change their size via props (height, width). Currently, to change the size of the image you need to override two classes `sf-image`, `sf-image__img`.

**Comment by filrak** [comment]
@krskibin funny enough I just posted this on our Discord: 

```
I have some concerns about SfImage. RIght now if we don't define a placeholder with exactly the size of the image then we still ahve content jumping. Also we shouldn't force people to add any kind of placeholder. By default we should just have a gray (or other) background in the size of an image. My propostion is to add height prop. It will remove problem with different sizes of images on a listing (whitespace will be added) and let us have a nice css-only placeholders. 
```

@leomp12 what do you think?

**Comment by leomp12** [comment]
@filrak agree, we're already fixing this problem for product card pictures setting the height with SCSS [here](https://github.com/DivanteLtd/storefront-ui/blob/master/packages/shared/styles/components/SfProductCard.scss#L64), but sure we can't do the same for `SfImage`.

The only problem of forcing `height`/`width` by prop instead of CSS is that it'll not be responsive, only if we get an object with breakpoints, wdyt @krskibin @filrak ?

**Comment by EduardDopler** [comment]
@leomp12 Actually it will be responsive if we _also_ define CSS sizing properties (e.g. in percentages, like `width: 100%`, then it will take 100 % of the parent's width, no matter what the HTML attributes say).

And the best part is that this approach is a best practice now. Because it allows browsers to calculate the image's aspect ratio and to reserve space for it during layout–long before the first byte of the image arrives. Hence reducing jank.
There's a nice little [video](https://youtu.be/4-d_SoCHeWE) by Mozilla's Jane Simmons about the topic.

**Comment by przspa** [comment]
When I have a problem with image size then I use aspect ratio hack. 
You have always good size :D but you should define width and height to calc it )

**Comment by filrak** [comment]
Maybe we will have same approach as with images and have just string and object options (mobile, desktop)?

**Comment by przspa** [comment]
https://markus.oberlehner.net/blog/lazy-loading-responsive-images-with-vue/ guys what did you think about this issue? @filrak new props `:size={small:{w:"", h:""}, normal:{w:"", h:""}}` like in src?

**Comment by EduardDopler** [comment]
@przspa I like that. This can be combined with the HTML props, I mean: the `w` and `h` can be inserted in the final HTML as `width` and `height` so browser can calculate the final aspect ratio.
And if the `:size` prop is missing, we just let the image stretch full-width of the parent? This way the user can decide if he/she wants to image to be "fluid" or have breakpoints.

**Comment by leomp12** [comment]
@przspa like `src`, but we'll change it to `{ mobile, desktop }` (https://github.com/DivanteLtd/storefront-ui/issues/447), anyway, Imo your suggestion https://markus.oberlehner.net/blog/lazy-loading-responsive-images-with-vue/ is better.

@EduardDopler using aspect ratio approach I think we don't need `size` object prop with breakpoints, just original image dimensions from normal `width`/`height` number props, then we can calculate responsive height with aspect ratio function...

It solves content jumping, but does not solve this other problem:

> problem with different sizes of images on a listing (whitespace will be added)

To be honest, I think it's not responsibility of `SfImage` itself, but of the parent element (list or list item), as done by `SfProductCard`.
If you disagree with this we can add another `containerHeight` object prop `{ mobile, desktop }`, wdyt?

Sorry for the delay here and on Discord, hard work at black friday :sleepy:

**Comment by EduardDopler** [comment]
Thinking about it, I'm with @leomp12 on this.

What is an image holder like our SfImage all about?

❗️ **Showing an image.** Sure, this includes things like providing transitions for them (prop: `transition`). Also, which image source should be used for which screen size (`src` + `pictureBreakpoint`). And if there's a placeholder for when the image isn't loaded (`placeholder`). Lazy-loading (`lazy`) is a thing you want to have on the image level for fine-grained control which images should be loaded lazily and which shouldn't. And of course there's the alt tag (`alt`).

❓ **Should it change its behavior/appearance based on the parent it is included in?** This is tricky. There are pros and cons to this. I'd rather make the parent itself responsible (i.e. in charge of) for its children, e.g. by using a flex container or restricting them via CSS.

---

This is a little off-topic but is related to image sizing, too: I feel always a little restricted if I cannot set "new" or advanced features on HTML elements which are handled by a library, i.e. if I use SfImage I cannot set any attributes which we don't expose to the user. E.g. if I'd want to define more than 2 images (chosen from via a single breakpoint—which I have to set for every image if it's not exactly `576`), I couldn't. If I wanted my image source to be picked in concern to a pixel density, I couldn't. And this is true although the Web Platform can, e.g. via [`srcset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset). So I was thinking if we can somehow use more of the browsers' built-in capabilities; E.g. what if we don't restrict the user to define a custom src object but pass on all defined attributes to the underlying `<img>` tag in our template (*). Maybe it's even possible to abandon `<picture>` and use `img srcset` instead? This would simplify the public API of our component and allow more use cases, wouldn't it? Lozad [works with `srcset`](https://github.com/ApoorvSaxena/lozad.js#usage), too, so this shouldn't be a problem:

```html
<img class="lozad" data-src="image.png" data-srcset="image.png 1000w, image-2x.png 2000w" />
```

I guess, SfImage usage would then be sth. like:
```html
<SfImage
  :src="src"
  :alt="alt"
  :transition="myTransition"
  :lazy="true"
  :placeholder="myPlaceholder" />
```

```js
data() {
  return {
    src: "normal.jpg, small.jpg 400w, normal.jpg 800w, large.jpg 1200w",
    // alt, placeholder, ...
  }
}
```

The first element in the `src` prop will be the fallback element, inserted in lozad's `data-src`, the rest will go into `data-srcset` as-is.
If lazy is false, we insert it directly into an `<img>` tag without the `data-` prefix.

(*) Also, it could be beneficial to insert all other non-props into the final <img> tag, with `v-bind="$attrs"`. This enabled our users to use more or future features without us having to expose them/change the component's API.

Plus, without the distinction between `<picture>` tag and `<alt>` tag, our template gets simpler.

This is wild thoughts, I know 😅🙈 but wdyt?

**Comment by filrak** [comment]
@EduardDopler I think the idea is brilliant but it's not solving the issue this task is about (or i get it wrong, if so please correct me). We should specify somehow width/height of a gray placeholder (or image) that will be displayed before image appears

**Comment by EduardDopler** [comment]
Wouldn't/Shouldn't the placeholder also be restricted by the parent?

IMHO the placeholder should behave exactly like the final image – so no element size changes happen when the placeholder gets replaced by the final image.
