### ISSUE TITLE
Link in README does not exist

### ISSUE THREAD

**Issue by AjitZero** [DivanteLtd/storefront-ui#478]
The link in Line 40 of README.md does not exist in the `master` or `develop` branches. Searching the repo shows it to be available at [this path](https://github.com/DivanteLtd/storefront-ui/blob/370b40bf53b9a06c150876d7f55ed7f6933bfab4/packages/vue/docs/customization.md) instead.

Edit: It should preferably link to the actual hosted docs page at https://docs.storefrontui.io/customization.html

**Comment by EduardDopler** [comment]
Hi @AjitZero!
The file you're searching for is now at [/packages/vue/docs/customization.md](https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/docs/customization.md).

But I would link directly to the rendered version at our docs-domain, as the file contains VuePress-specific syntax which GitHub wouldn't render. Here: https://docs.storefrontui.io/customization.html

Feel free to push it with your existing PR #479 and close both your issues via [GH's commit keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords).

wdyt @filrak ?

**Comment by AjitZero** [comment]
@EduardDopler Done!
