### ISSUE TITLE
[BUG] Some transitions broken

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#489]
**Describe the bug**

Currently some transitions aren't working on `develop`. (`master` is fine.)

I tried to bisect the issue: In PR #442 all transitions are working, in PR #443 they don't anymore. The timespan is 19 days. I cannot detect problematic changes in #443 so I think it must have been a commit directly to `develop`.

This affects many components, like SfOverlay, SfModal, SfLoader etc.

**How to reproduce**
:heavy_check_mark: Working #442: https://deploy-preview-442--storefrontui-storybook.netlify.com/?path=/story/utilities-transitions--slide-right
:heavy_multiplication_x: Broken in #443: https://deploy-preview-443--storefrontui-storybook.netlify.com/?path=/story/utilities-transitions--slide-right

**Comment by przspa** [comment]
@EduardDopler I found it :) We never import https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/utilities/transitions/transitions.scss 🚀

**Comment by EduardDopler** [comment]
Wow, that makes sense! 😅
I guess it was imported somewhere else before then? Because the git history of __all.scss_ never had that import?

**Comment by przspa** [comment]
Because we import its inside components. But if you want to use it on page you can do that. Than we should import it in `_all.scss` what did you thing?

**Comment by EduardDopler** [comment]
When it's in __all.scss_ then it's globally available, right? I think that is the way to go, yes.
It is a pretty small overhead, gzipped 693 bytes... And as soon as someone uses a component with transitions, he/she gets those bytes anyway.
