### ISSUE TITLE
[ Storybook ] Adjust Storybook stories to common format

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#49]
Every available component stories should be adjusted to common format. If they don't exist they should be created.

The format is described [here](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/component-rules.md#stories-for-storybook)

In short words we should have at least those stories for every component:
- one with props (as knobs)
- one or more for different usage examples
- one for slots
- one for CSS modifiers

**Comment by leomp12** [comment]
Also about the storybook, should be good to add md components reference as notes on stories (https://storybook.js.org/docs/basics/writing-stories/#using-markdown), wdyt?

**Comment by filrak** [comment]
Yeah, this is also sth I thought about but had no time to properly configure it. markdown loader seems to have some problems with storybook. It might be trivial but it's the first time I'm using SB

**Comment by leomp12** [comment]
The problem is with the HTML template inside markdown, it works if we replace _````html_ to _```_ only, but gets really ugly, I've also tried parsing the markdown first, then other bug comes, the h1 tag is showed, and the code box stills bad.
I think we can just link the HTML file (directly to GitHub), if you think it's important to keep it on markdown we would take a look on [storybook notes](https://github.com/storybooks/storybook/tree/master/addons/notes) and try to fix it.

**Comment by leomp12** [comment]
Imho is not a problem to just link the template file, in fact when the template is big I believe it might even mess up the documentation, I think that for most users would be easier to see the component API first, and if it's not clear, take a look on HTML markup.

**Comment by filrak** [comment]
Yeah, you're right. Can you make an issue for this and leave it for someone else or take care of this?

**Comment by leomp12** [comment]
I can take care, I'll make a new PR with stories adjusted with notes and the components READMEs fixed.
Do you think we can just replace the template with the link, eg.:

```markdown
# HTML template
[@src/any/SfComponent.html](https://github.com/DivanteLtd/storefront-ui/src/any/SfComponent.html])
```

Or we should remove this block and just place the link on footer together with the others?

**Comment by filrak** [comment]
I guess for now we can leave the link. Once we will have it on storybook it will be enough. I need to talk with our adm about domain access
