### ISSUE TITLE
[BUG] Reactivity/Interaction broken in molecules stories

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#490]
**Describe the bug**

Some molecules components lost their interactions on events (clicks etc).

I'm not 100 % sure but I think it is related to `chore/molecules` ([merge commit](https://github.com/DivanteLtd/storefront-ui/commit/f674836cbc4a04b7480198354ce4ef0183f59fb7)).

I checked the following components which don't react on clicks anymore:
* SfModal,
* SfNotification,
* SfPagination

All of them work in PR #459 which is before that merge commit (cf. [Storybook at that state](https://deploy-preview-459--storefrontui-storybook.netlify.com/?path=/story/molecules-pagination--basic)) and stopped working in #460 ([Storybook at that state](https://deploy-preview-460--storefrontui-storybook.netlify.com/?path=/story/molecules-pagination--default)) which includes the changes from the chores branch, I think.

**Comment by przspa** [comment]
@EduardDopler I moved it behaviour to knobs. You can off it from knobs. But hmm probably we should emit the event and change `data`. I do that because when you change `data` you can't update it from knobs or something like that.

**Comment by EduardDopler** [comment]
Huh. You're absolutely right, I just tried all variants I could think about; nothing works as expected. Looks like a real limitation in Storybook.

Both ways are bad: components which don't respond to clicks and missing knobs for props. But I lean a little bit towards making the components respond to clicks again. Thinking of the future of the components docs, I think it would be nice to be able to interact with them directly in the docs.

wdyt? @przspa @filrak

**Comment by przspa** [comment]
@EduardDopler agree
