### ISSUE TITLE
[RFC] Proposal for Gitflow

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#512]
This RFC proposes the **gitflow style** for handling version control.

_**Limitation:** This is proposition for the gitflow \*style\*/convention, not the gitflow \*tool\*. The gitflow style can be used without using any git plugins._

## Background, Current State & Motivation
As the project evolved from committing directly to `master`, there are two long-living branches now, `master` and `develop`, which—by definition—don't hold the same state at all times. While our versioning is linear now (i.e. each minor or patch level release builds upon the most current state, dropping the support for earlier versions), this behavior will most likely change. In addition to those two branches there will be release version branches that need to be supported: As long as a release branch is supported, it needs to receive critical hotfixes but without receiving changes/features that were introduced in later releases.

There are several ways to tackle this situation in software engineering, with the **gitflow workflow** being among the most common ones.

### Daily Development & Feature Branches
Gitflow defines two major, long-living branches: **`master`** and **`develop`**. 
Daily development takes place in **_feature_ branches** which are derived from `develop` and, after QA, merged back into `develop`.
In a strict variant the only commits allowed to `develop` are merge commits. So everything that should land in `develop` needs to go through a feature branch. In a lesser strict workflow, _very_ small changes like typos are allowed to be pushed directly to `develop`. It's up to the team to settle on a variant.
In daily development `master` is never touched; neither branched from nor merged into.

Naming conventions for feature branches are beneficial. The original gitflow convention is to prepend every feature branch with `feature/` followed by an issue number and/or a brief description, e.g. `feature/#1234-sftoggle`. This makes it easier to distinguish the branch types in branch overviews.

### Releases
In order to release a specific repo state, with a version number and tag and all, a **_release_ branch** can be created. It is also derived from `develop` but merged into `develop` **and `master`**.
At the same time a **version tag** is created on `master`, pointing to the merge commit.
The release branch can stay open as long as that specific version line is supported. It is needed for hotfixes (see below).

_Note: Keeping release branches open is actually a deviation from the original gitflow workflow which is made for only one actively supported release. There, a release branch is closed the moment it is merged into `master`. With the need to maintain multiple version lines, the way proposed here is an appropriate variation._

The original gitflow naming convention for release branches is to prepend release branches with `release/` followed by the release version, e.g. `release/1.2.0`. A common _tag_ convention is the `v` prefix as in `v1.2.0`.

### Hotfixes
If the situation arrives where urgent bugs need to be fixed in all affected and still supported release versions, **_hotfix_ branches** are created. Those are the only branches created from `master` and must be merged back into `master`, `develop` **and all supported `release` branches**.
Those commits are normally small and don't create (many) merge conflicts. But sometimes hotfix changes require extra work in order to backport them into earlier releases. All this work has to go through QA, i.e. PRs, so no new issues are introduced into one or more releases.

The proposed naming convention for such branches is the prefix `hotfix/` plus the new version number, e.g. `hotfix/1.2.1`.
Theoretically (but not necessarily), to minimize confusion in the git history, it is advised to create a branch for each supported release branch, branched away from the original hotfix branch (which is targeted towards the most recent release) and name those branches according to the last version in those release branches.
(Example: Create a hotfix branch from `master` towards the most recent version, e.g. `hotfix/2.2.1`, merge it into `master` and `develop` and create new hotfix branches from that branch for older releases, e.g. `hotfix/2.1.6` and `hotfix/2.0.9`, and merge them into those.)

Also, new tags are created for all fixed release branches.

## More Information and Variations
The internet is full of resources, descriptions and graphics. I'm bad at graphics, that's why I didn't include any.

---

This RFC is open for discussion. Any proposed ideas or conventions are up for debate. There is a significant chance that I missed some edge cases which make the implementation of this convention harder or impossible, so let's brainstorm together 🌪⚡️

**Comment by filrak** [comment]
bumping as its important topic :) @pspaczek

**Comment by pspaczek** [comment]
@EduardDopler it's look's awesome for me. I just add to it one rules. "We work on our SFUI forks and don't create new branches on this repository" 

Now we use master and develop on right way as you propose. 
We should just add release and hotfix to our flow?

💚  Now in SFUI we have conventional commits linter and squash branch to develop and merge develop to master. Everything starts looking cleaner.

**Comment by EduardDopler** [comment]
Thank you! 😊

> I just add to it one rules. "We work on our SFUI forks and don't create new branches on this repository"

Great, then I will add a page with this text to our docs.

> Now we use master and develop on right way as you propose. We should just add release and hotfix to our flow?

Yes, every time we release a new major or minor version, we can create a tag and a branch with the appropriate name and maintain it (with hotfixes) as long as needed.

> Now in SFUI we have conventional commits linter and squash branch to develop and merge develop to master. Everything starts looking cleaner.

Awesome! Looking forward for the first automagic changelog! 📑
