### ISSUE TITLE
[Mobile/Desktop] Implement SfTable

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#513]
![Screenshot from 2019-12-06 15-28-13](https://user-images.githubusercontent.com/41487496/70331845-a09f7600-1840-11ea-9552-09173962ca7b.png)
![Screenshot from 2019-12-06 15-28-21](https://user-images.githubusercontent.com/41487496/70331855-a5642a00-1840-11ea-902c-7fd2f1d8da2a.png)

Can be found in desgins in My Account

Proposed API:
```vue
<SfTable>
  <SfTableRow>
    <SfTableHeader><!-- slot content --><SfTableHeader>
    <SfTableHeader><!-- slot content --><SfTableHeader>
  </SfTableRow>
  <SfTableRow>
    <SfTableData><!-- slot content --><SfTableData>
    <SfTableData><!-- slot content -->.<SfTableData>
    <SfTableData><!-- slot content --><SfTableData>
  </SfTableRow>
</SfTable>
```

**Comment by DonNicoJs** [comment]
@aniamusial chiming in because lately I am dealing with tables.. Do we plan to use html table markup or to emulate it with div and roles?

If the second is true there is a tons of rules to apply 😿

**Comment by aniamusial** [comment]
@DonNicoJs yes, we plan to use html table markup, emulating it would be a nightmare indeed!

**Comment by filrak** [comment]
Imho we should just style a regular table but this could lead to some rwd challenges. An option is to take already existing responsive table and just adjust it
