### ISSUE TITLE
[Feature] Use Decorators in Stories

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#514]
As a side result of #480 we want to encapsulate purely presentational information in our stories inside [Storybook decorators](https://storybook.js.org/docs/basics/writing-stories/#decorators). Cf. @filrak's [suggestion](https://github.com/DivanteLtd/storefront-ui/pull/480#issuecomment-561260742).

## List of decorators to add

**Therefore we need the following decorators which handle the _presentation_ of the component:**

* `withCustomStyle` – adds arbitrary CSS style declarations to the component
* `withMargin` – adds a margin around the actual component
* `centeredDecorator` – centers the component (at least horizontally)

It might be useful to have a decorator which adds the possibility to trigger a **state change** in the underlying component. This might be a more demanding task though (Wrapping Vue component? Vue mixin? …?).

* `withVisibilityToggle` – adds a button next to the actual component which toggles the visibility state (useful to re-trigger the component if a it was dismissed by user interaction, like by the close button of SfModal)

### Parametrized decorators
Parametrized decorators (like `withMargin`) may be added to stories via ~~JS _partial application_~~ _function factories_, so the decorators can be called like normal functions with parameters, e.g.
```js
.addDecorator(withMargin("10px"))
```

### Prefer local to global
Those decorators should *not* be applied globally (to all components) but can be chosen for each story which requires one or more of them.

### Directory structure and import strategy
All SfUI custom story decorators should reside in a separate file, e.g. _vue/config/storybook/decorators.js_ (next to the storybook config files).
To enable simple (ES-style) imports, all decorator functions should be exported as individual functions.

### Existing decorator(s)
The only existing custom decorator `PaddingDecorator` gets commented and uncommented in every other PR, so it should be removed. Stories which really rely on it have now other decorators to choose from.

**Comment by filrak** [comment]
As always brilliant idea :), it will make our life's easier if we decide to do some changes in the decorators some day in the future

**Comment by aniamusial** [comment]
@EduardDopler great idea! I'm currently working on removing all the inline css from stories, looking forward for the updates! :)

**Comment by EduardDopler** [comment]
@aniamusial I added a PR.

This whole thing makes use of the changes developed in #491. So that story needs to be merged first (that's why the PR is _WIP_).

**Comment by EduardDopler** [comment]
@filrak Not included in this PR but I've already adjusted the new auto-generation inside create-vue-components-docs (#473) to work with these changes.
I think it's beautiful: With these decorators the stories stay clean (they have only a decorator and a mixin to work with the data toggles) and the generated components docs show the data attributes correctly inside the `data` block 🌟
