### ISSUE TITLE
[Feature] Implement SfCircleIcon on SfProductCard 

### ISSUE THREAD

**Issue by przspa** [DivanteLtd/storefront-ui#522]
Implement  SfCircleIcon for SfProductCard to add product to cart. 
If you have question, fell free to aske me.
![image](https://user-images.githubusercontent.com/12138170/70608510-8aa70200-1c00-11ea-99f3-5611514917e6.png)

**Comment by filrak** [comment]
It should only has property `onAddToCart` defaulting to null, when filled the button appears
