### ISSUE TITLE
[Feature] Impement SfScrollable

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#523]
Create component SfScrollSection to hide to long content.
I think max-height should be set by CSS. But if it's impossible that you can use props.
```html
<SfScrollSection>
  <slot/>
</SfScrollSection>
```
https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=3494%3A8026
![SfScrollSection](https://user-images.githubusercontent.com/12138170/70609414-09e90580-1c02-11ea-847d-71bc64c025a1.png)

**Comment by filrak** [comment]
How about `SfScrollable`as name? I guess here we can set height by a prop as it's the only attribute.  Other option might be just to make it filling whole container

**Comment by aniamusial** [comment]
@przspa need some help with fixing test
