### ISSUE TITLE
[BUG] Not properly styled huge icons (cartIcon, wishListIcon, accountIcon in Header, Menu, Filters)

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/storefront-ui#527]
**Describe the bug**
When we use icons (cartIcon, wishListIcon, accountIcon) in our project for example in SfHeader, Cart or Category FIlters Panel we suffer from invalid styling of the icons. These icons appear to be huge and do not match the rest of the layout.

**How to reproduce**
Use icons from Storefront UI.

**Expected behavior**
Icons should appear just like in Storefront UI storybook.

**Actual behavior**

![image](https://user-images.githubusercontent.com/1880231/70780088-02059e80-1d85-11ea-8b89-a6722d696b4b.png)

![image](https://user-images.githubusercontent.com/1880231/70780152-08941600-1d85-11ea-8b11-670eb9781116.png)

**Additional context**
I can provide test environment in private messages. Unfortunately our testing environment is not public at the moment.

**Comment by przspa** [comment]
@rmakara we fix it here #515, but you use slot to override the default content
