### ISSUE TITLE
[Refactor] improve SfSelect > SfSelectOption

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/storefront-ui#533]
Create functionality which behaves like disabled option in native select's option (https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_option_disabled).
```
<SfSelectOption
                id="size_option"
                v-for="size in sizes"
                :key="size.id"
                :value="size.id"
                :disabled="size.disabled"    <------ proposal prop
              >
```

Then the disabled option could be visible, grayed out,  but not clickable/selectable. 
Users should be able to see that option but without the possibility to choose one.

**Comment by aniamusial** [comment]
Assigning to @przspa as he will do the whole refactor

**Comment by pspaczek** [comment]
add to #664
