### ISSUE TITLE
[BUG] Too many level 0 categories in SfHeader, which is too narrow

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/storefront-ui#535]
**Describe the bug**
When I have too many categories (level 0) in SfHeader then Vue Storefront logo on the left hand side is getting too narrow. Also there is no solution for handling many categories on level 0, that would not fit in the maximum width of the header.

**Expected behavior**
I think we should handle the appearance of the logo. The question to UX Designer is how shall we handle bigger amount of categories in level 0. In case of the decision of not handling that case - we should think about some limitation or information in documentation of Storefront UI on what's the maximum amount of level 0 categories to be added in SfHeader.

**Actual behavior**
![image](https://user-images.githubusercontent.com/1880231/70782817-28790900-1d88-11ea-984c-8dd7b27e1590.png)

![image](https://user-images.githubusercontent.com/1880231/70782843-36c72500-1d88-11ea-94ca-df70fe98b34a.png)

**Comment by pspaczek** [comment]
fixed on design side
![Zrzut ekranu 2020-03-12 o 11 37 06](https://user-images.githubusercontent.com/12138170/76512947-d5315800-6455-11ea-969a-ab90b8e70dd6.png)

**Comment by aniamusial** [comment]
#1011

**Comment by martaradziszewska** [comment]
solved by #1165
