### ISSUE TITLE
[BUG] Too long list of available filtering values in filters panel

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/storefront-ui#536]
**Describe the bug**
In the filtering panel we have a lot of some filters and below all of these filters we have let's call these "values" to filter by. Sometimes we have too many "values" and the list gets ultra long, which makes it hard to spot the next filter.

**Expected behavior**
Consider adding some kind of "More..." button to expand the long lists of available filters. By default we shouldn't show all of the available ones.

**Actual behavior**
![image](https://user-images.githubusercontent.com/1880231/70783006-a76e4180-1d88-11ea-8bd3-6cffea1246c3.png)

![image](https://user-images.githubusercontent.com/1880231/70783021-afc67c80-1d88-11ea-924f-fbf3dcb63e7b.png)

**Comment by przspa** [comment]
#523  I think here is a solution 🚀

**Comment by aniamusial** [comment]
Fixed in #523
