### ISSUE TITLE
[BUG] Too low contrast of the text (Low Vision)

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/storefront-ui#537]
**Describe the bug**
Some texts in the storefront are light-gray colour on white background. I am not sure if it meets the criteria of https://www.w3.org/TR/low-vision-needs/#text-contrast

Examples: "Sort by", "Products found".

**Expected behavior**
That would be nice to verify with our UX Designer we meet accessibility criteria. If not, that would be worth to fix it to meet the text contrast requirements.

**Actual behavior**
![image](https://user-images.githubusercontent.com/1880231/70783390-f320eb00-1d88-11ea-97a1-8e5433c23a8a.png)

**Comment by EduardDopler** [comment]
See also https://github.com/DivanteLtd/storefront-ui/pull/416#issuecomment-549508044. It shows that just the two text color variants "light" and "dark" don't work on many of our default colors. Each color should have a "recommended" foreground color which should be used on it.

**Comment by pspaczek** [comment]
will fixed on #819 thank you guys!
