### ISSUE TITLE
[BUG] Look of the gallery in Product Page against long descriptions

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/storefront-ui#538]
**Describe the bug**
When I am in the Product Page and I want to read Description / Properties, which are very long then I must scroll to the last image in the gallery.

**Expected behavior**
I would like to be able to read the whole product information details without going down with the images gallery.

**Actual behavior**
![image](https://user-images.githubusercontent.com/1880231/70783634-2794a700-1d89-11ea-98bc-d8f45add6610.png)

**Comment by aniamusial** [comment]
Fixed in 0.7.0
