### ISSUE TITLE
[BUG] SfCarousel shows not loaded SfProductCards when you have swiped to the last item

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/storefront-ui#545]
**Describe the bug**
SfCarousel on both the mobile and desktop view is not working properly. When you swipe elements on the SfCarousel to the last one. The not loaded, first SfProductCard will appeare as the next SfCarousel element.

**How to reproduce**
1. Find any SfCarousel
2. Swipe the SfProductCards (using only the cursor, not arrows) to the last one

**Expected behavior**
After last SfProductCard should be only white space

**Actual behavior**
Additional SfProductCard appears without a loaded image 

**Screenshots**
![bug](https://user-images.githubusercontent.com/12700136/70797359-a3e8b380-1da4-11ea-96c4-ca9692cb46e2.png)

**Devices (please complete the following information):**
 - Browser: [Chrome, Firefox]

**Additional context**
Nuxt project

**Comment by pspaczek** [comment]
merge to #1023
