### ISSUE TITLE
[REFACTOR] Refactor SfModal and SfSidebar for mobile

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#554]
Acceptance Criteria:
- SfModal and SfSidebar have ` :title` props
- SfModal and SfSidebar have SfSfBar on mobile
- SfModal and SfSidebar should be `position:fixed` and `top:0`
- SfBar for SfModal have close
- SfBar for SfSidebar have back

[SfModal]
![image](https://user-images.githubusercontent.com/12138170/70896334-ccfd8400-1ff0-11ea-8ac2-a13c5d3dd639.png)

[SfSidebr]
![image](https://user-images.githubusercontent.com/12138170/74141536-631be800-4bf7-11ea-910e-db76e65055f0.png)

**Comment by pspaczek** [comment]
@martaradziszewska can you do these issues?

**Comment by martaradziszewska** [comment]
@pspaczek yes, I'm on it
