### ISSUE TITLE
[BUG] SfSelect - not reacting on v-model change

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/storefront-ui#561]
**Describe the bug**

SfSelect takes v-model and on mounted sets selected values. But if v-model is changed *after* select mounted cycle, then the component is not rendering selected element.

**How to reproduce**
1. Display select with an empty v-model property
2. then set v-model property on parent component to pass

**Expected behavior**

The parent can fully control which option is selected by changing the value passed by v-model

**Screenshots**

![image](https://user-images.githubusercontent.com/13100280/70916103-680b5380-201b-11ea-8cbe-53e8a00a8bf8.png)

**Comment by filrak** [comment]
Well it works on storybook, both example and bare component https://storybook.storefrontui.io/?path=/story/pages-product--default Are you sure you're using it correctly?

**Comment by patzick** [comment]
#### example case
when you have in data
```
selectedValue: null
```
and now render componsnt
```
<SFSelect v-model="selectedValue" />
```

and now in parent, when you change `this.selectedValue`, then SfSelect is not showing selected element

**Comment by filrak** [comment]
Yeah, just checked. it works for falsy values like `""` but doesn't for null

**Comment by DonNicoJs** [comment]
Fixed by: https://github.com/DivanteLtd/storefront-ui/pull/572
