### ISSUE TITLE
[Desktop / Mobile ] Implement SfTabNavigation

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#57]
Desktop
![image](https://user-images.githubusercontent.com/15185752/55820056-7bfcce00-5afa-11e9-9a77-19f9923fe5f0.png)
![image](https://user-images.githubusercontent.com/15185752/55820133-a6e72200-5afa-11e9-811d-548ce7d2fb06.png)
Mobile
There is no strict design for mobile view so please copy font styles from Steps (can eb found on mobile checkout) 
![image](https://user-images.githubusercontent.com/15185752/55822094-2676f000-5aff-11e9-9e88-9bcd79539cfa.png)

Can be found on [designs](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0) on product page (desktop)

----
 Proposed API to implement

Second one treats nav as a totally separate component
````html
<SfTabNavigation :nav="navItems" current="currentTab" @change="newVal => currentTab = newVal">
````
+ slot item for nav item

`navItem` format 
````js
{ id: string, label: string }
````

**Comment by leomp12** [comment]
Imho we should handle the second (separating tabs and content) case first, it's more flexible, maybe later we create a component including both tabs and content.

**Comment by filrak** [comment]
Ok i updated the issue, it's ready to be picked
