### ISSUE TITLE
[ Desktop / Mobile ] Implement SfInputNumber

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#58]
[Figma designs](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A3210) on product page.

![](https://screenshotscdn.firefoxusercontent.com/images/6bff2e67-b273-440e-8ed6-838db5327054.png)

Imho it should have 2 chevrons (up and down), for best usability, even though it was otherwise suggested in Figma.
I think it's important that the native `<input>` have `type="tel"` to open the number keyboard by default on mobile (good practice) and skip design problems (varying by browser) created by `type="number"`.

---

### Props

- `step` - incremental step, 1 by default
- `value` / `v-model` - input value, 0 by default
- `min` - min value
- `max` - max value
- `placeholder` - placeholder for the native input element
- `precision` - decimal precision, 0 by default (for integers)
- `name` - native input name

When `max` is 0, native input should be disabled.

### Slots

- `default` - slot with input element, should bind the `value`
- `up` - arrow (control) up
- `down` - arrow (control) down

### Events

- `change`
- `focus`
- `blur`

### Methods

- `focus`
- `blur`
- `select`

Events and methods same as in native input.

**Comment by filrak** [comment]
Looks good to me! @mayashavin can you take care of a11y audit for this comoonent once PR is done?

**Comment by mayashavin** [comment]
@filrak sure :)
