### ISSUE TITLE
Add checkbox to SfFilter / Remove color property

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#591]
![image](https://user-images.githubusercontent.com/15185752/71357885-5e3ba000-2587-11ea-8f72-db71ffc94139.png)

- Remove `color` option from `SfFilter`
- Instead of being underline while choosen filters should have checkboxes and `isActive` prop
- use `SfProductOption` fro all demo selects instead of `SfFilter`

**Comment by peoray** [comment]
Hello, can I work on this issue if it's not taken already?

**Comment by aniamusial** [comment]
@peora keep in mind that this is task is tagged as important - if you are okay with that then go ahead, just remember to self-assign :)

**Comment by aniamusial** [comment]
@peoray I'll take care of this one, thank you :)

**Comment by peoray** [comment]
No problem @aniamusial. Sorry, I didn't work on this quicker cause of the holidays :(

**Comment by aniamusial** [comment]
@peoray totally understandable, go ahead and pick something else to work on :)
