### ISSUE TITLE
[FR] Ability to put sfui.scss in custom directory

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/storefront-ui#598]
**Story**
I want to be able to install sfui in my monorepo project where theme using storefront ui is one of the workspaces. In other words, I want to be able to set StorefrontUI as a dependency of Vue Storefront theme. Currently sfui.scss is automatically installed in root directory.

**How to reproduce**
1. Add sfui as dependency of vsf theme

**Expected behavior**
There is a documented way of configuring StorefrontUI to use sfui.scss in theme directory instead of root category/

**Actual behavior**
There is no such way AFAIK.

**Comment by lukeromanowicz** [comment]
Hmm... I'm not able to change the label to feature request. @pspaczek please help.

**Comment by pspaczek** [comment]
@lukeromanowicz now it's ok?

**Comment by filrak** [comment]
@lukeromanowicz i think its not an issue of sfui but issue of how you install dependencies. If you hoist sfui then its installed in root. If you install it in theme (like we have in CT project) it will be installed in theme
