### ISSUE TITLE
[ Mobile / Desktop ] Implement SfBadge

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#62]
[Figma designs](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=300%3A7) on _Mobile Guide > Urgency Elements_.

![](https://screenshotscdn.firefoxusercontent.com/images/5fb2f61f-17a8-4721-a6fe-5760673296cc.png)

## Proposed API

- default slot (for content);
- CSS modifiers `--info`, `--alert` and `--warning`, defaults to primary color (the green);

No props, no methods, no events (pretty simple :smile: ).
Take a look on [SfAlert](https://github.com/DivanteLtd/storefront-ui/tree/master/src/components/atoms/SfAlert) as reference.

Please mind that **it's just a proposal**. We're open to discussion regarding component API.

**Comment by filrak** [comment]
Looks good but shouldn't it be `SfBadge`? Afaik this element in UI is called a badge. Ref - https://www.google.com/search?biw=1440&bih=789&tbm=isch&sa=1&ei=pV-uXPCTLZHCUtKOuvgN&q=product+badge&oq=product+badge&gs_l=img.3..0i19l3j0i5i30i19l3j0i8i30i19l2.3463.4015..4267...0.0..0.97.412.5......1....1..gws-wiz-img.......0j0i30.a8nOnIEoEsE#imgrc=jCVqiPU5h9OVRM:

**Comment by leomp12** [comment]
Maybe, but we'd have another badge too, right? Circular and smaller (for the cart icon, for example), I had thought of calling it SfBadge, so I called this SfTag component.

**Comment by leomp12** [comment]
But if we do not have another badge component, I agree it's better to call this component of bagde than tag...

**Comment by filrak** [comment]
What you mean by the oen with cart icon ? You mean for example small circle indicating that it's not empty? I guess we will handle this case in a separate SfIcon component

**Comment by filrak** [comment]
It's ready to pick if anyone is interest ;)

**Comment by JCown** [comment]
I'll take this.

**Comment by filrak** [comment]
I'm uanssigning since it looks like abandoned one ;) ANyone willing to implement - feel free to do so

**Comment by decadef20** [comment]
I'm willing to have a try.

**Comment by decadef20** [comment]
Is there a group or anywhere we can talk about the code and design?

**Comment by filrak** [comment]
@decadef20 sure ping me here https://join.slack.com/t/vuestorefront/shared_invite/enQtMzA4MTM2NTE5NjM2LTI1M2RmOWIyOTk0MzFlMDU3YzJlYzcyYzNiNjUyZWJiMTZjZjc3MjRlYmE5ZWQ1YWRhNTQyM2ZjN2ZkMzZlNTg

I also added you as a collaborator so you can assign yourself in a future!

**Comment by leomp12** [comment]
https://github.com/DivanteLtd/storefront-ui/pull/96
