### ISSUE TITLE
[BUG] Can't change viewBox in SfIcon

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/storefront-ui#633]
**Describe the bug**
Can't change viewBox in SfIcon by passing prop.

**How to reproduce**
1. Go to https://storybook.storefrontui.io/?path=/story/atoms-icon--common
2. Try to change viewBox

**Expected behavior**
Custom viewBox will be applied to icon.

**Actual behavior**
Icon gets default viewBox.

**Code examples**
Probably problem is here https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/components/atoms/SfIcon/SfIcon.js#L72
Maybe change to something like this :man_shrugging: 
```
    iconViewBox() {
      const defaultSFIconViewBox = this.isSFIcons ? icons[this.icon].viewBox : '0 0 24 24'
      return this.viewBox || defaultSFIconViewBox
    },
```
and set `default: ''` for prop viewBox

**Comment by EduardDopler** [comment]
You cannot change the `viewBox` if you reference one of our SfUI built-in icons. This is intended, isn't it @mayashavin ? For custom icons you can: https://storybook.storefrontui.io/?path=/story/atoms-icon--props-default
Is there a special use case why you want to change the viewBox and not the `size` @gibkigonzo ?

**Comment by gibkigonzo** [comment]
cool, I didn't know that I can pass custom path 👍 I want to center default chevron icon in button. Right now it looks like this:
![Screenshot_5](https://user-images.githubusercontent.com/42383376/72379701-3d90e100-3714-11ea-8664-289432bf1e3c.png)
So I need to add viewBox `'0 -4 14 14'`. But if I can pass path, then problem is solved for me :)

**Comment by mayashavin** [comment]
@gibkigonzo sorry for late reply. Yes you can't pass viewBox if you are using built-in SF icons. And yes you can always pass custom path(s) - array of paths or string is ok.  Make sure you pass also the viewBox defined in your svg icon. :) Our default viewBox is according to Material Icon standards.
Have fun!
