### ISSUE TITLE
[BUG] Wrong z-index of SfQuantitySelector

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#637]
![image](https://user-images.githubusercontent.com/15185752/72149593-cf5ebe00-33a3-11ea-9182-e2072b9a6efb.png)

**Comment by aniamusial** [comment]
@filrak removed in https://github.com/DivanteLtd/storefront-ui/pull/638 although IMO I think this issue is more #632 related - after merging this one all those z-index issues shouldn't appear.
