### ISSUE TITLE
[BUG] After reaching last product from SfCarousel it immediately switches to the first few pictures

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/storefront-ui#651]
**Describe the bug**
After reaching the last product from the carousel and clicking the right arrow user is switching immediately to the first few pictures. That can be confusing for the user.

**How to reproduce**
In for example Shopware-pwa
1. go to detail product page
2. scroll down to the 'Mach it' carousel
3. click right arrow until you get switched to the first few pictures
4. repeat step 3 for 'You might also like' carousel

**Expected behavior**
The carousel: 
1. can go in circle or 
2. when reached to the last picture the right button inactive and user needs to click (swipe) to the left

**Comment by pspaczek** [comment]
merge to #1023
