### ISSUE TITLE
[REFACTOR] Remove usage of yarpm and require yarn

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#653]
## Background
This is a follow-up of the discussion here: https://github.com/DivanteLtd/storefront-ui/pull/499#issuecomment-562102217.
Quoting it:

---

Hmm looking at the `scripts` part, I think we require yarn now, so maybe we don't even need _yarpm_? I guess it isn't possible to run SfUI without yarn anyway, is it?

**vue/package.json**
```js
{
  "serve": "yarpm create-index-files && vue-cli-service serve",
  "build": "yarpm create-index-files && vue-cli-service build --target lib --name storefront-ui ./src/index.js",
  "lint": "vue-cli-service lint",
  "test:unit": "vue-cli-service test:unit",
  "test:dev": "vue-cli-service test:unit --watch",
  "storybook:serve": "yarpm create-index-files && vue-cli-service storybook:serve -s ./public -p 6006 -c config/storybook",
  "storybook:build": "yarpm create-index-files && vue-cli-service storybook:build -s ./public -c config/storybook",
  "docs:vuecomponents": "node scripts/create-vue-components-docs.js",
  "docs:dev": "yarpm docs:vuecomponents && vuepress dev docs",
  "docs:build": "yarpm docs:vuecomponents && vuepress build docs",
  "create-index-files": "node scripts/create-index-files.js",
  "postinstall": "node scripts/postinstall.js && yarn create-index-files", // here
  "version": "node scripts/version.js",
  "prepublish": "yarn create-index-files",                                 // here
  "postpublish": "node scripts/postpublish.js"
}
```

**/package.json**
```js
{
  "create-component": "node ./scripts/create-component.js",
  "storybook:serve": "cd packages/vue && yarn storybook:serve",  // here
  "vue-docs:dev": "cd packages/vue && yarn docs:dev"             // here
}
```

(`prepublish` is fine I guess because the user doesn't run it. But `postinstall` is run by every user so he/she has to have yarn, right? @przspa @patzick @filrak Then we could remove the dependency to yarpm...)

---

## Goal
- Remove usage of `yarpm` in all _package.json_ files and use `yarn` directly.
- Remove `yarpm` from `devDependencies`.
- Edit docs to reflect the changes.

**Comment by patzick** [comment]
That's correct. Yarn is enough to run with the project, so removing this dependency is a good move!

**Comment by peoray** [comment]
@patzick, to be clear, is this simply, replacing anywhere I see `yarpm` with `yarn`?

**Comment by EduardDopler** [comment]
@peoray And also if npm is mentioned for contributors. A quick search resulted in the following places which need to be edited:
- _creating-new-component.md_, lines 9 and 70
- _documentation-guidelines.md_, line 37

**Comment by patzick** [comment]
That's correct :) there should be a strong message for contributors to use just yarn

**Comment by aniamusial** [comment]
Hi @peoray please try to stick to one-task-at-the-time convention :) Review all tasks assigned to you and choose one to work on. This yarn task is really important right now and we need to merge it soon. Thank you! :pray:

**Comment by peoray** [comment]
@aniamusial Thanks for the reminder. This is almost done. Will be submitting a PR ASAP :)

**Comment by peoray** [comment]
About to submit PR. Should I uninstall the `yarpm` package?

**Comment by fancydev18** [comment]
Hi,

Since npm comes by default with node, what's missing from npm in order to use it instead of yarn?

npm v7 is in beta now, I can check if what's needed for storefront-ui is present there, if npm v6 isn't good enough.

**Comment by peoray** [comment]
@fancydev18 I'm not sure but I think the reason is that the team used yarn to install the dependencies needed for the project, so it's ideal that when trying to run the project, you should also use yarn to run the installations. Maybe the core team can chime in on this? @filrak ?

**Comment by pspaczek** [comment]
@fancydev18 @peoray we use yarn for contributors, probably when you use storefront-ui directly by npm you can use npm. We use lerna in our monorepo and base on yarn workspaces to improving our work.

**Comment by fancydev18** [comment]
Thanks!

@pspaczek 
> probably when you use storefront-ui directly by npm you can use npm. 

This would be ideal, but it doesn't work:

```
$ npm install --save @storefront-ui/vue
...
> node scripts/postinstall.js && yarn create-index-files

sh: yarn: command not found
```

Since that's only a node command (not requiring workspaces or something yarn-specific)
https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/package.json
```
"create-index-files": "node scripts/create-index-files.js",
```
could yarn be replaced with npm please in this file, please?

**Comment by pspaczek** [comment]
@fancydev18 we will change in next release, @peoray fix this issues here https://github.com/DivanteLtd/storefront-ui/pull/730/files#diff-099a765d0e8e27c90657641e46433003, thanks for your vigilance :)

**Comment by peoray** [comment]
@pspaczek Do I create a new issue for it or just make the change from the branch I did the PR from?

**Comment by pspaczek** [comment]
for what? you change this yarn to node in your PR :) everything is ok 
![Zrzut ekranu 2020-02-5 o 19 34 39](https://user-images.githubusercontent.com/12138170/73871675-8ee14b80-484e-11ea-88b4-d05450ea0da6.png)

**Comment by peoray** [comment]
Oh, sorry I thought you meant I should make a new change. That was confusing lol
