### ISSUE TITLE
[FEATURE] Moving to CSS Vars

### ISSUE THREAD

**Issue by ClaudiaPascualGea** [DivanteLtd/storefront-ui#657]
**Describe how this feature will help us improve**

Moving to CSS custom properties means visual properties are scoped to the element they are declared on, they cascade efficiently without mixins and they can be efficiently manipulated in Javascript. (https://cathydutton.co.uk/posts/why-i-stopped-using-sass/).

A better organization for component styles following the atomic design principle grants a better organization and architectural design. (https://dev.to/sanfra1407/how-to-organize-your-components-using-the-atomic-design-dj3).
 
Using mobile-first as the default style using min-width and scaling out progressively for larger devices is more consistent with the library purpose.

Enforce CSS best practices enhances overall maintainability.

**Is your proposal related to a problem?**

No

**Describe the solution you'd considered**

Components scss files are classified within folders following the atomic design principles, each one of them replaces SCSS variables with CSS properties decreasing the number of mixins to deal with. 

Moreover, taking advantage of CSS properties for some components reduces the abuse of !important properties for color variants, check the example below:

--circle-icon-color: var(--c-on-primary); 
--circle-icon-hover-background: var(--c-primary-lighten);

Enforcing the mobile-first with min-width makes the mobile style the default one. Following media queries target progressively larger screens and they work better than using max-width where implicitly the design is desktop-first.

A couple of utility color functions for color-variants generation have been added as well, they work through mixins including CSS properties.

**Additional context**

I've already prepared a PR for you including all of these changes you may want to look up if you accept this feature request.

**Comment by filrak** [comment]
Hey! Thanks for the suggestion ;) We already have this in our roadmap - could you please ping @Przemek Spaczek on discord as he has some plans regarding this feature as well.

**Comment by ClaudiaPascualGea** [comment]
Thanks @filrak, he had agreed on creating a WIP PR, can you assign me this issue please?

**Comment by pspaczek** [comment]
Thanks @ClaudiaPascualGea you are really awesome 💚
