### ISSUE TITLE
[BUG] SfQuantitySelector min behaviour

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#658]
**Describe the bug**
Min checker on SfQuantity is run too fast. It should be run after change input.

**How to reproduce**
1. Set min to 5
2. Try read 15
3. You see 55 no 15

**Expected behavior**
You should have 15 in input

**Actual behavior**
Now I have 55

**Comment by EduardDopler** [comment]
Maybe we should move the logic for resetting the value in a valid range to the `blur` event. This would allow users to enter invalid numbers for as long as they have the focus in the input, as soon as they leave it, it will be reset to the `min` value.

Another idea is to not reset the value at all but to apply the `:invalid` style to it.

**Comment by aniamusial** [comment]
Closing as its no longer valid due to #720 Thank you guys for your help! :green_heart:
