### ISSUE TITLE
[FEATURE] <SfProductCardHorizontal>

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#671]
![image](https://user-images.githubusercontent.com/15185752/72597940-17836080-390f-11ea-9774-0584c8a1a3ec.png)
Same API as `SfProductCard` but with description prop ;)

TODO:
- Add component
- Add it to product page (there is a grid change btn there)

**Comment by martaradziszewska** [comment]
Closed with #716
