### ISSUE TITLE
[BUG] SfBottomNavigation, SfCart z-index conflict

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/storefront-ui#680]
**Describe the bug**
SfBottomNavigation and SfCart have the same z-index value, so SfBottomNavigation is under the navigation on mobile even though it's a modal.

**How to reproduce**
On mobie device open cart from bottom navigation

**Expected behavior**
SfCart should be on the top layer of the page view.

**Actual behavior**
SfBottomNaviation is on the top layer of the page.

**Code examples**
```html
<style>
/* Temporary solution in Shopware-PWA 😉 */
.sf-bottom-navigation {
  z-index: 0;
}
</style>
```
Or add code snippets (Code sandbox)

**Screenshots**
<img width="401" alt="Zrzut ekranu 2020-01-19 o 21 57 58" src="https://user-images.githubusercontent.com/12700136/72688373-c5a52b00-3b06-11ea-962e-4388ff33bb9e.png">

**Devices (please complete the following information):**
 - Device: All

**Additional context**
Vue, Nuxt Project,

**Comment by aniamusial** [comment]
@peoray @lukeromanowicz created a fix for this one :)
