### ISSUE TITLE
 [ Mobile / Desktop ] Loading component and directive

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#69]
I think we should implement `SfLoading` component to handle loading spinners inside other components, but we may also append a spinner on body and create a `v-loading` directive to toggle this _global_ loading spinner.
Not a necessity, but I believe it would be comfortable to use in this way, waiting for opinions...

**Comment by filrak** [comment]
Actually v-loading directive would be useful but more like a wrapper for a certain component than a global one

**Comment by filrak** [comment]
I guess for those it would be awesome to have such loading states built into some components as placeholders for better loading experience 
![image](https://user-images.githubusercontent.com/15185752/56119942-601b8100-5f6d-11e9-845a-90ec8cbf64d2.png)

**Comment by leomp12** [comment]
Imho, inside those specific elements we can use the `SfLoading` component, so we prevent putting content with the directive on each element, witch is not a good practice...
Skeleton is good, but I'm not sure if we can use it generically, to be well implemented I think the layout must be known. So, I think we can provide skeleton component, but the user should implement it himself based on his custom layout.
I think a global `v-loading` directive, showing overlay and spinner, may be a more plug and play option to handle route transitions for example...
