### ISSUE TITLE
[DESIGN] Product with custom options.

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/storefront-ui#697]
**Describe how this feature will help us improve**
In vsf there are products which have custom options (radio, checkbox, text input, select (dropdown)). For example https://next.storefrontcloud.io/gear/gear-3/wayfarer-messenger-bag-custom-options-4.html

**Describe the solution you'd considered**
I've created something like this. Is there any design for that kind of products?
![Zrzut ekranu z 2020-01-23 08-28-44](https://user-images.githubusercontent.com/42383376/72978388-a8a67b80-3dd6-11ea-89ab-01ed11cb845b.png)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-19 o 21 43 51](https://user-images.githubusercontent.com/62093203/79698089-dd678900-8286-11ea-9895-08dc54e7493c.png)

Done:) Thanks for the idea!
