### ISSUE TITLE
[DESIGN] Product with bundle options

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/storefront-ui#698]
**Describe how this feature will help us improve**
In vsf there are products which have bundle options. It's a combination of radio buttons + quantity. For example https://next.storefrontcloud.io/gear/gear-3/sprite-yoga-companion-kit-45.html

**Describe the solution you'd considered**
I've created something like this. Is there any design for that kind of products?
![Zrzut ekranu z 2020-01-23 08-28-10](https://user-images.githubusercontent.com/42383376/72978768-53b73500-3dd7-11ea-923d-a289f471fb10.png)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-23 o 22 15 27](https://user-images.githubusercontent.com/62093203/80145100-f1292d00-85af-11ea-9cfe-4a464082c297.png)

If that's ok, please close the task:)

**Comment by pspaczek** [comment]
thank you @mbaran-dvnt
