### ISSUE TITLE
[FEATURE] Full page cart

### ISSUE THREAD

**Issue by fancydev18** [DivanteLtd/storefront-ui#703]
There's only a small slide-in cart at
https://storybook.storefrontui.io/?path=/story/pages-cart--common

**Describe how this feature will help us improve**
A full page cart allows having more information (eg minimum quantity required, upsells, various promotions)

**Additional context**
Most stores on Shopify have a full page cart, which lets merchants present more offers and actions in cart.

**Comment by aniamusial** [comment]
Designs: https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-and-Mobile-Vue-Storefront?node-id=99%3A3085

**Comment by aniamusial** [comment]
![Screenshot from 2020-01-31 14-33-10](https://user-images.githubusercontent.com/41487496/73543181-b0999780-4436-11ea-938f-802668c3c251.png)

**Comment by fancydev18** [comment]
Thanks Ania! Some things to consider:

1. It's confusing to have Quantity over the image. I've never seen that before. Here's how other stores usually show it:
https://www.tluxe.com/collections/new-drop/products/copy-of-slim-linen-poncho-top-2
2. A total per item, may shown only when Qty > 1, would be useful
3. What would 'Edit' do? Is that needed?
4. Would you please consider crafting a mobile mockup too? (460px)

Appreciate your time.

**Comment by aniamusial** [comment]
Hey @fancydev18 
Ad.1 You can post suggestions for design in separate task and mark them as "design"
Ad. 2, Ad.3 StorefrontUI is a components library - Edit button is just an example of usage, it will probably open a modal or smth. It work however you will like it work on your page. We are focusing on UI part, for advanced logic and fully working theme check out Vue Storefront :) 
Ad. 4 All the designs are in the link above :)
Feel free to ask in case of any more questions!

**Comment by pspaczek** [comment]
@fancydev18 it's just our proposition to design. You can create your own design and move components where you want. Storefront UI is just a component library base on atomic design. To be honest :) https://www.tluxe.com/collections/new-drop/products/copy-of-slim-linen-poncho-top-2 this project look really simple. Storefront UI is a modern library base on https://services.google.com/fh/files/events/pdf_retail_ux_playbook.pdf.  And you sent for our product page, not cart page.

**Comment by pspaczek** [comment]
added at v0.7.0 in the #942
