### ISSUE TITLE
[FEATURE] Product example with options/variants

### ISSUE THREAD

**Issue by fancydev18** [DivanteLtd/storefront-ui#704]
Hi, would you please add a Product example at
https://storybook.storefrontui.io/?path=/story/organisms-productcard--common

which has options/variants, such as Color and Size?

Looking for a component which produces this
https://hauslondon.com/collections/sofas/products/day-bed-four-by-another-country
(see Base, Upholstery options)

or
https://www.tluxe.com/collections/new-drop/products/copy-of-slim-linen-poncho-top-2
(see Size, Color options)

Thanks!

**Comment by pspaczek** [comment]
@fancydev18 You can find Product Page in our examples https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/examples/pages/product/Product.vue

**Comment by mariusa** [comment]
Thanks @pspaczek ! In that code, all sizes and all colors are listed. However, some products might not have all colors for all sizes. How would you recommend to handle this?

**Comment by fancydev18** [comment]
Thanks @pspaczek ! In that code, all sizes and all colors are listed. However, some products might not have all colors for all sizes. How would you recommend to handle this?

**Comment by pspaczek** [comment]
@fancydev18 Storefront-UI is just UI library without business logic. Our pages is just an example with simple demo functions to present how you can use our components, not recommended to use on production. Whole business logic you can find in [Vue Storefront](https://github.com/DivanteLtd/vue-storefront)
