### ISSUE TITLE
[BUG] v-bind:style on component root breaks this directive in usage

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#710]
If we have `v-bind:style` on any component root like `SfBanner`
```
  <section class="sf-banner" :style="style" v-on="isMobile ? $listeners : {}">
```
It breaks usage of this directive for this component in App
```
<SfBanner :style="sth" /> <-- will not work
```

Please check all the components and remove those bindings

**Comment by pspaczek** [comment]
https://codesandbox.io/s/style-binding-10mv1 I created some small test and it should work with both `v-bind:style`
