### ISSUE TITLE
[FEATURE] Adjust to SfUI rules SfStoreLocator and fix some bugs

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#714]
Acceptance Criteria
- [x] use PascalCase for Vue component on template `<l-map/>` to `<LMap/>`
- [x] use slots in SfStore for example for `media`, `heading`, `contact` check SfStoreLocator too and add slots if it is needed
- [x] adjust to changes in other components for example phone icon on SfStore
- [x] no error in Console
- [x] `{{registerStore(store)}}` Probably we shouldn't use this function in the template to register a new store. IMO we can yous some different solution

**Comment by DonNicoJs** [comment]
@pspaczek I am happy to work on this, can you ping me when you add the details?

**Comment by pspaczek** [comment]
@DonNicoJs sure, I will try to add detail to this issues today/tomorrow

**Comment by pspaczek** [comment]
@DonNicoJs I added more details about this task

**Comment by DonNicoJs** [comment]
@pspaczek Thanks for the details, all good minus this point: 

> {{registerStore(store)}} Probably we shouldn't use this function in the template to register a new store. IMO we can yous some different solution

I believe this is one of the center points of the component because without that the user can hardly deal with the slots to populate the markers, I will see if I can handle it differently but I doubt.

**Comment by pspaczek** [comment]
@DonNicoJs maybe you can use here provide/inject? Inject store on mount or update to keep reactivity :) what did you think? Check SfContentPages ;) how it's work with provide/inject :) 
```vue
<SfStoreLocator>
<SfStore v-for="store in stores" :props :key />
</SfStoreLocator>
````

**Comment by DonNicoJs** [comment]
Note: the mail icon is a bit squeezed @aniamusial

**Comment by DonNicoJs** [comment]
@pspaczek The errors in the console is leaflet trying to load a default icon that:
- is not there
- we do not use

so I think we can skip it :)

**Comment by DonNicoJs** [comment]
@EduardDopler With @aniamusial We were checking the documentation ( which is amazing btw ) I was wondering is there the ability to add custom part of the docs for additional explanations?

**Comment by EduardDopler** [comment]
Hey @DonNicoJs ! Sorry for coming so late back to you. 
I'm not fully at your speed right now, I'd need a little more context please :) Are we talking component docs and there auto-generation? If so, it'd be possible to add placeholders to appropriate places and replace them in the generation process. This would work only if the spot where you want to place the content is always the same though — if you want something at an arbitrary place you'd still need to come up with some kind of marker or something. But – as always – I'm open for suggestions!

**Comment by DonNicoJs** [comment]
@EduardDopler Yeah, any fixed place will do I guess! Just that we can add some custom explaination / text / code whatever to help the users. 

Cool point would be to use the `<doc>` tag in the SFC for this kind of stuff, like I do here: https://github.com/vue-leaflet/Vue2Leaflet/blob/master/src/components/LCircle.vue#L51
