### ISSUE TITLE
[ Mobile / Desktop ] Implement ProductCard

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#72]

**Comment by leomp12** [comment]
Please tell me when it gets ready, then I'll take care of SfCarousel.

**Comment by leomp12** [comment]
Additionally, imo we should handle lazy load for product pictures on cards by default or make it optional by prop, are you already planning to do this?

**Comment by chhonmeily** [comment]
@filrak please provide the mock up for this product card. Or do you want to see suggestion from us?

**Comment by filrak** [comment]
@chhonmeily i already implemeted MVP version of it ;)
