### ISSUE TITLE
[FEATURE] ZEIT for storybook and vuepress

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#728]
**Describe how this feature will help us improve**
After removed Netlify from develop we need something to deploy PR preview.

**Describe the solution you'd considered**
Use GH Actions and ZEIT to deploy Storybook and Vuepress from PR.

**Comment by peoray** [comment]
Whoever is gonna do this, please inform me. I want to learn how to do this :)

**Comment by pspaczek** [comment]
back to netlify, close this issues
