### ISSUE TITLE
[BUG] CSS Variables overrload sorybook dev mode 

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#729]
**Describe the bug**
When you use storybook:dev then all css variables loading a few times and destroy browser performance. You can develop sfui. Ip production mode everything is ok. 

**How to reproduce**
1. Go to component
2. Open dev tools 
3. Check how variables is overridden in loops

**Expected behavior**
CSS variables is loading just once 

**Actual behavior**
CSS variables is loading a lot of times

**Comment by pspaczek** [comment]
Probably we should move CSS global variable to separate files and don't import it to all components as we do now.

**Comment by peoray** [comment]
@pspaczek Can you provide more details on this so I can quickly work on it since it's important?

**Comment by pspaczek** [comment]
@peoray in all components in SFUI we have `@import '../../variables';` and always import global CSS variables (run storybook:serve and check many global CSS variables overrides).
I think we should move CSS and SCSS variables to seperated files and when we `@import '../../variables';` we should import just SCSS variable declarations, without CSS variables global declaration

**Comment by pspaczek** [comment]
@here I do hofix but probably we can do it better. If someone know how do it better than fell free to fit it 💚
