### ISSUE TITLE
[ Mobile / Desktop ] Implement SfColor

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#74]
![image](https://user-images.githubusercontent.com/15185752/56123973-e0de7b00-5f75-11e9-865d-78449ce03218.png)
and selected version 
![image](https://user-images.githubusercontent.com/15185752/56124093-2a2eca80-5f76-11e9-8bed-09e2c582ac5f.png)

Both:
![image](https://user-images.githubusercontent.com/15185752/56124110-33b83280-5f76-11e9-95e7-2e649bf10e5a.png)

Can be found on category sidebar ( designs - https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0 ) and product card

**Comment by Jensderond** [comment]
Is @runyasak working on this in #46 ?

**Comment by runyasak** [comment]
@Jensderond Yes, I'm working on making storybook and unit test. But the `SfOptions` has been finished.

**Comment by filrak** [comment]
hey @Jensderond I guess it will be easier to extract this from @runyasak PR and have it as an atom. I was thinking about using this for things like filter listing on category page. Let's wait until @runyasak PR is merged ;)

**Comment by runyasak** [comment]
I have finished SfOptions already. So, I will assign me on this issue and extract color components from SfOptions.

**Comment by filrak** [comment]
@runyasak can you please do an ainput instead. I guess I'll need to rethink this one a little bit ;)
