### ISSUE TITLE
[FEATURE] Implement SfTextarea

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#740]
**Is your proposal related to a problem?**
#604 

**Designs**
https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-and-Mobile-Vue-Storefront?node-id=465%3A137
-> In the bottom, under What can we improve heading

**Comment by peoray** [comment]
@aniamusial I want to work on this but I haven't done anything similar. Need a lot of guidance on how to go about it.
