### ISSUE TITLE
[Documentation] Make changes to contributing guide

### ISSUE THREAD

**Issue by peoray** [DivanteLtd/storefront-ui#743]
Describe how this feature will help us improve
- On the [docs](https://docs.storefrontui.io/contributing/github-guidelines.html#_4-create-an-issue-branch), it says to create a new branch from your `master` branch instead of working directly on the master branch of your forked. I think this line should be changed to reflect `develop` instead of master.
- The format for naming will cause an issue as git will throw an error. It's important to tell the user to make use of the escape slash (`\`) or the other different ways discussed [here](https://stackoverflow.com/questions/49665976/why-cant-a-branch-name-contain-the-hash-char-at-the-begining) while trying to name a branch.

This will make it easier for a new contributor to make a PR

Is your proposal related to a problem?
No

Describe the solution you'd considered
- Change the text from the master branch to develop branch.
- Include the different options of avoiding git error while trying to name a branch using the `#-issue-num-branch-name` method.

**Comment by aniamusial** [comment]
@peoray thank you for reporting an issue! Docs indeed need some update :)
