### ISSUE TITLE
[BUG] SfTab should be a button

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#746]
**Describe the bug**
Currently SfTab is a clickable` <div>` - it should be a styled `<button>` for accessability reasons.

**Comment by pspaczek** [comment]
@aniamusial you can add roles probably https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques

**Comment by aniamusial** [comment]
Or add role :)

**Comment by peoray** [comment]
@aniamusial which is it? :)

**Comment by aniamusial** [comment]
@peoray you can go with a role :)

**Comment by martaradziszewska** [comment]
@peoray are you still on it? :)

**Comment by peoray** [comment]
Yes @martaradziszewska
