### ISSUE TITLE
[DESIGN] We need to design our custom :focus 

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#754]
**Describe how this feature will help us improve**
We should have a custom focus for elements like buttons, links, anything interactive. The default one is not looking too good. Also, it is crucial for accessability.

**Is your proposal related to a problem?**
#588

**Comment by mbaran-dvnt** [comment]
I've added alternative buttons set on the left to the style guide. My idea is to replace old button with this set, much better imo:)
