### ISSUE TITLE
[FEATURE] Add possibility to pass .webp image with fallback to SfImage component

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/storefront-ui#761]
**Describe how this feature will help us improve**
Currently, there is not possible to pass .webp images with png/jpg fallback to SfImage component. After these changes, it will be possible.

**Is your proposal related to a problem?**
No

**Describe the solution you'd considered**
Currently, the object we passing to SfImage component looks like this:

```
src: {
  mobile: { url: "/assets/storybook/SfImage/product-109x164.jpg" },
  desktop: { url: "/assets/storybook/SfImage/product-216x326.jpg" }
}
```
instead, we can pass object like this and iterate through array elements:

```
src: {
  mobile: [{ url: "/assets/storybook/SfImage/product-109x164.webp" },{ url: "/assets/storybook/SfImage/product-109x164.jpg" }],
  desktop: [{ url: "/assets/storybook/SfImage/product-216x326.webp" }, { url: "/assets/storybook/SfImage/product-216x326.jpg" }]
}
```

**Additional context**
No additional context

**Comment by pspaczek** [comment]
@qiqqq what do you think about this way? When we do that in this way is just a feature. When we use your propose then is changes. IMO we won't use the same image on fallback. 
```
src = {
  mobile: {
    url: "/assets/storybook/SfImage/product-109x164.webp",
    fallback: "/assets/storybook/SfImage/product-109x164.jpg"
  },
  desktop: {
    url: "/assets/storybook/SfImage/product-216x326.webp",
    fallback: "/assets/storybook/SfImage/product-216x326.jpg"
  }
};
```

**Comment by qiqqq** [comment]
@pspaczek I think this is a good solution

**Comment by EduardDopler** [comment]
This is okay, imho. But then there is only one possibility for a fallback. How about my suggestion here: https://github.com/DivanteLtd/storefront-ui/issues/474#issuecomment-561093548

It is somewhat more complicated though.

**Comment by pspaczek** [comment]
@EduardDopler do you mean replace mobile/desktop Object to srcset String? Because now we suport just two case and when we start using srcs then user will decide about breakpoints sizes?

**Comment by EduardDopler** [comment]
Something like that, yes.

The user would decide all sources by entering a String like: `normal.jpg, small.jpg 400w, normal.jpg 800w, large.jpg 1200w`. Our logic can transform it directly to lozad, with the first one as fallback:
```html
<img class="lozad" data-src="normal.jpg" data-srcset="small.jpg 400w, normal.jpg 800w, large.jpg 1200w" />
```

---

But I've just noticed that this doesn't solve the problem with WebP. Then we could use a similar syntax and transform it into a `<picture>` tag! That would be 🚀  The lozad-syntax for the picture tag looks like this: https://github.com/ApoorvSaxena/lozad.js#example-with-picture-tag so I think it should be possible if we expect an array of objects like this:
```js
[
  {
    src: "normal.jpg"
  },
  {
    src: "high.webp",
    media: "(min-width: 1280px)", // optional
    type: "image/webp"            // optional
  },
  {
    src: "low.webp",
    type: "image/webp"
  },
  {
    src: "high.jpeg",
    media: "(min-width: 1280px)",
    type: "image/jpeg"
  },
  {
    src: "low.jpeg",
    type: "image/jpeg"
  }
]
```

This can be translated to lozad syntax:
```html
<picture class="lozad" data-iesrc="normal.jpg" data-alt="">
    <source srcset="high.webp" media="(min-width: 1280px)" type="image/webp">
    <source srcset="low.webp" type="image/webp">
    <source srcset="high.jpg" media="(min-width: 1280px)" type="image/jpeg">
    <source srcset="low.jpg" type="image/jpeg">
</picture>
```
