### ISSUE TITLE
[BUG] AddToCart component doesn't have maxium quantity validation

### ISSUE THREAD

**Issue by mikemarsian** [DivanteLtd/storefront-ui#765]
**Describe the bug**
AddToCart component description mentions that it supports maximum quantity validation. But actually, it only has qty-min binding, but no qty-max binding.
https://docs.storefrontui.io/components/AddToCart.html

**Comment by pspaczek** [comment]
Hi @mikemarsian it's not a bug. We moved responsibility for validation to the programmer. When we add min and max we can create a lot edge case (for example: when fire min, max invalid emit; change input calue to min / max or allow user overload). Now programmer should watch qty and implement invalid actions. Thanks for that you can have better control on it. What do you think about my explanation?

**Comment by mikemarsian** [comment]
Well, currently you do have min_quantity but don't have max_quantity. So I
think you should have both or neither, right?

**Comment by martaradziszewska** [comment]
@mikemarsian we removed min_quantity so now it is consistent as you suggested :)
