### ISSUE TITLE
[REFACTOR] Change SfRadio is-active and  is-disabled to modifiers

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#766]
SfRadio `is-disabled ` and `is-active` classes hould be modifiers

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
Instead of:
```
= { 'is-active' : isChecked}
```
change to:
```
= {'sf-radio--is-active}
```
Remember to adjust CSS as well.

**Comment by krystiansiwek** [comment]
@aniamusial Probably same for SfCheckbox. I will take it.
