### ISSUE TITLE
[BUG] Buttons with outline are higher than normal

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/storefront-ui#767]
**Describe the bug**
Button with class `sf-button--outline` are higher than normal, because border adds them additionals pixels.

**Expected behavior**
All buttons should have the same hight,

**Actual behavior**
Outlined buttons are higher than others.

**Screenshots**
![Screenshot_2020-02-17  shopware-pwa default-theme](https://user-images.githubusercontent.com/12700136/74657667-04bfae00-5191-11ea-9947-1ca88717ca46.png)

**Devices:**
 - all

**Comment by krystiansiwek** [comment]
@krskibin I can take care of that :)

**Comment by aniamusial** [comment]
@krystiansiwek I've assigned you, thanks for the help! :)

**Comment by martaradziszewska** [comment]
Done in https://github.com/DivanteLtd/storefront-ui/pull/770 :)
