### ISSUE TITLE
[BUG] SfOverlay not transitioning

### ISSUE THREAD

**Issue by jahvi** [DivanteLtd/storefront-ui#772]
**Describe the bug**
The SfOverlay component doesn't transition in/out even with the default `fade` transition prop.

Not sure if related to #489

**How to reproduce**
1. Go to https://storybook.storefrontui.io/?path=/story/atoms-overlay--common
2. Toggle `visible` prop
3. See overlay suddenly appear/disappear instead of fading in/out.

**Expected behavior**
Overlay should fade in or out by default.

**Actual behavior**
Overlay suddenly appears or disappears.

**Devices (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All

I can have a look at fixing this if it's an issue, not sure if it's intended.

**Comment by Trapdafifou** [comment]
I'd like to have a look at it 👁

**Comment by Trapdafifou** [comment]
Did a fix for this if you want to check [my PR](https://github.com/DivanteLtd/storefront-ui/pull/773).
