### ISSUE TITLE
[BUG] SfButton -  For sf-button--outline modifier on color choice only border should change

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#777]
**Describe the bug**
`color-{color}` class should apply different styles regarding different modifiers. f.e. Right now if we choose `--outline` and any color the background is also changing, is should be just border.

![Screenshot from 2020-02-24 14-50-23](https://user-images.githubusercontent.com/41487496/75157817-34346480-5715-11ea-8348-2e6acc9efba5.png)

**How to reproduce**
1. Go to SfButton
2. Click on` sf-button--modifier `and `color-danger`
3. See error

**Expected behavior**
sf-button--outline is changing its border and text-color on color change

**Comment by martaradziszewska** [comment]
@peoray I will take this because we need this ASAP. You can go with other tasks :)
