### ISSUE TITLE
[BUG] SfCircleIcon lost :active state

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#780]
**Describe the bug**
SfCircleIcon should have :active state with box-shadow bigger than on :hover state. Actually button lost its active state.

**How to reproduce**
1. Go to 'SfCircleIcon'
2. Click on 'button'
4. See that active state its not working

**Expected behavior**
![image](https://user-images.githubusercontent.com/34887212/75233653-7adb9a80-57b9-11ea-97c6-e9c8c3e263d1.png)

**Comment by aniamusial** [comment]
Fixed in #819
