### ISSUE TITLE
[BUG] SfTabs not working

### ISSUE THREAD

**Issue by AnnaLysiuk** [DivanteLtd/storefront-ui#788]
**Describe the bug**
SfTabs not rendered at https://storybook.storefrontui.io/?path=/story/organisms-tabs--common

**How to reproduce**
1. Go to https://storybook.storefrontui.io/?path=/story/organisms-tabs--common
2. See error

![Screen Shot 2020-02-26 at 08 30 27](https://user-images.githubusercontent.com/27008721/75322011-45df4e80-5872-11ea-97c1-78eef7abc8bd.png)

**Comment by pspaczek** [comment]
thank 🙏 @AnnaLysiuk I don't know how but we miss this bug before release
