### ISSUE TITLE
[BUG] SfAccordion folds first item in updated hook

### ISSUE THREAD

**Issue by psmyrek** [DivanteLtd/storefront-ui#790]
**Describe the bug**
If I have `firstOpen` prop not provided for `SfAccordion`, it is set to `false` as default value. Then `SfAccordion` folds first item in `updated` hook if something has changed in siblings elements in DOM. This causes that `SfAccordion` is always collapsed/folded automatically after clicking on any menu item in first `SfAccordionItem`.

**How to reproduce**
Lets assume we have the following component:
```
<template>
  <div>
    <SfAccordion>
      <SfAccordionItem v-for="category in 3" :key="category" :header="`${category}`">
        <SfList>
          <SfListItem v-for="item in 5" :key="item">
            <SfMenuItem :label="`${item}`" @click="selected = item" />
          </SfListItem>
        </SfList>
      </SfAccordionItem>
    </SfAccordion>
    Selected item: {{ selected }}
  </div>
</template>

<script>
import { SfList, SfMenuItem, SfAccordion } from '@storefront-ui/vue';
export default {
  name: 'Example',
  components: {
    SfList,
    SfMenuItem,
    SfAccordion
  },
  data () {
    return {
      selected: '-'
    };
  }
};
</script>
```
Having "Selected item" output as a sibling element next to `SfAccordion` causes that `updated` hook is triggered in `SfAccordion` after clicking on any menu item in first `SfAccordionItem` and then this causes that first `SfAccordionItem` is folded automatically.
After commenting out the `Selected item: {{ selected }}` line `updated` hook is not triggered and first `SfAccordionItem` is not folded/collapsed automatically anymore.

**Expected behavior**
I would like to not fold automatically first `SfAccordionItem` in `updated` hook if `firstOpen` prop is not provided. I would like to have first opened item kept as it is and `updated` hook should not modify it. Having `firstOpen = true` is not a solution here because it will open first item after mounting `SfAccordion`, which is also not nice.

**Actual behavior**
First `SfAccordionItem` is folded automatically in `updated` hook if `firstOpen` prop is not provided.

**Comment by justyna-13** [comment]
This problem was solved with a new ```open``` prop
