### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#8]
Hello,
I'm really interested on this project and also want to contribute here, but first I have to know if you are planning to release it open sourced (as Vue Storefront is), are you?
Thanks!

**Comment by filrak** [comment]
Hey!
I'm really glad you'd iike to help us. We are still preparing the repo for external contributions but it should be ready on Monday/Tuesday. 
It'll be MIT licensed as Vue Storefront is :)
Can you please ping me on VS slack so we can discuss your possible contributions?

**Comment by leomp12** [comment]
Perfect!
Sure, I'll call you on slack.
