### ISSUE TITLE
[FEATURE] Toggle content in SfRadio

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#845]
**Describe how this feature will help us improve**
Currently, we have SfRadio with the label, we need to improve it by adding additional content in dropdown according to new designs.
~~- add a slot for price~~
- add a slot for subtitle

![image](https://user-images.githubusercontent.com/34887212/75968915-7193b180-5ece-11ea-998a-0430e35cffc5.png)

**Additional context**
https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=216%3A4

**Comment by pspaczek** [comment]
@martaradziszewska maybe we need just #details slot for "Delivery within .." and don't touch description. IMO we do not need slot for price :). We can discuss the show/hide function

**Comment by martaradziszewska** [comment]
@pspaczek yes, that's a better idea to give the name more generic :) About show/hide function - maybe we need some Expansion Item a separate component?

**Comment by pspaczek** [comment]
@martaradziszewska we can think about it after these issues, IMO, but it sounds like a good idea

**Comment by AdamPawlinski** [comment]
@martaradziszewska @pspaczek I added the details. Is that only change that we need to apply now?
