### ISSUE TITLE
[FEATURE] SfQuantitySelector adjust logic to refactored design 

### ISSUE THREAD

**Issue by AdamPawlinski** [DivanteLtd/storefront-ui#848]
**Describe how this feature will help us improve**
After refactor SfQuantitySelector has new buttons +,- which should change the value of the input.
![image](https://user-images.githubusercontent.com/32042425/75974919-e5868780-5ed7-11ea-85b1-c6b7ed146f60.png)

**Is your proposal related to a problem?**
No

**Describe the solution you'd considered**
Cilck on buttons should change value (increment/decrement by 1), but it should be concidered that the value can be String or Number according to prop received.  

**Additional context**
no

**Comment by pspaczek** [comment]
PR: #834 COMMIT: https://github.com/DivanteLtd/storefront-ui/pull/834/commits/079d35905b2b0132f022eaaff1b5312b55a92a0a
