### ISSUE TITLE
[FEATURE] Implement SfColorPicker

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#851]
**Describe how this feature will help us improve**
With new designs comes new components - SfColorPicker is one of them.

Designs: 
Mobile -> https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=264%3A566

**Comment by pspaczek** [comment]
will be released at Storefront UI 0.8.0
