### ISSUE TITLE
[FEATURE] Implement SfDropdown 

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#853]
**Describe how this feature will help us improve**
We need to implement SfDropdown which will be used in SfContextMenu and also as a part of SfSelect. 
![image](https://user-images.githubusercontent.com/34887212/75979046-0652db00-5ee0-11ea-814c-6633794c9325.png)

Designs: https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=1%3A18

**Comment by pspaczek** [comment]
``` vue
<div class="sf-dropdown">
  <slot/>
</div>
```
and API for this component
``` vue
<SfDropdown :is-open="" transition="fade" class="sf-dropdown--up">
</SfDropdown>
```
