### ISSUE TITLE
[BUG] SfButton - no visual change on focus

### ISSUE THREAD

**Issue by Qrzy** [DivanteLtd/storefront-ui#863]
**Describe the bug**
When navigating through form with tab key there is no visual effect on `SfButton`s that become focused - this leads to confusion, some extreme example is password change form. This particular case lead to 2 discoveries:
- to navigate from password `SfInput` to another one I need to hit tab 2 times and I can't **see** why - but it's due to the `SfButton` inside that is responsible for password visibility
- I can't see when I focus submit `SfButton`

**How to reproduce**
1. Prepare a password change form (sequence of 3 `SfInput` of type `password` followed by `SfButton`)
2. Focus first `SfInput`
3. Navigate to next form elements with tab key

**Expected behavior**
A clear visual distinction of focused element (`SfButton` in this case), at least when navigating with keyboard.

**Actual behavior**
No visual sign of focused state.

**Comment by aniamusial** [comment]
@Qrzy we will be working on accessibility as soon as we finish implementing the design system - we have a v-focus directive already to fix that. Thanks for reporting! :)

**Comment by martaradziszewska** [comment]
@Qrzy @aniamusial I think this issue is solved with recent releases regarding improving accessibility.
