### ISSUE TITLE
[FEATURE]normalize, reset or none?

### ISSUE THREAD

**Issue by nordbit** [DivanteLtd/storefront-ui#867]
Bootstrap has build-in normalize.
With pure implementation of Storefront-ui in my project i got body margin, now I wonder - should I use reset or normalize by my own? I can't find any word in docs.

**Comment by pspaczek** [comment]
Hi @nordbit thanks for your issues, we add notice about this case to our docs. Storefront UI components have a style for fonts, spacer's etc. inside it. IMO the best way to clean CSS in your project now is a minimal CSS reset like:
``` css
body {
  margin: 0;
  padding: 0;
}
```
and expand it when you need it. For example, we don't set style's for `<a>` and `<p>` use outside Storefront UI, you must set it for your project.
