### ISSUE TITLE
[FEATURE] SfHeader - add wrap for more header items

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#872]
**Describe how this feature will help us improve**
Due to new designs, now if we have more than a few items, we should wrap SearchBar and icons.
![Screenshot from 2020-03-09 12-33-36](https://user-images.githubusercontent.com/41487496/76209468-39f47480-6202-11ea-862b-c4482820279f.png)

**Comment by pspaczek** [comment]
fixed #1165
