### ISSUE TITLE
[DESIGN] SfProductCardHorizontal on mobile / listing view

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/storefront-ui#894]
**Describe how this feature will help us improve**

Actually we don't have any specified view for SfProductCardHorizontal (listing) on mobile, which is really essential to have a proper mobile view also.

**Comment by mbaran-dvnt** [comment]
View and new components added to library.

**Comment by pspaczek** [comment]
thank you @mbaran-dvnt 
![Zrzut ekranu 2020-03-12 o 22 28 49](https://user-images.githubusercontent.com/12138170/76568304-db085700-64b0-11ea-8705-61948bed6445.png)
