### ISSUE TITLE
[ Desktop / Mobile ] Create SfInput

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#92]
Proposed API:

```HTML
<SfInput v-model="" label="" placeholder="" valid="" error-message="">
```
with slot for validation error + a11y (required, disabled, type etc)

Api is open to discussion. I guess we should focus on making it vuelidate-friendly :)
![image](https://user-images.githubusercontent.com/15185752/58046052-86bc7100-7b44-11e9-9b6e-573f7467b269.png)

Should animate like inputs on material design :) https://material.io/design/components/text-fields.html

**Comment by runyasak** [comment]
Thanks for assign me.
I love material design but never used it. This could be my challenge task. 😆
