### ISSUE TITLE
[DESIGN] How SfColor should look like for different views?

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#934]
**Describe the bug**
Currently on designs we have a few differents designs of SfColor. How it should look like on mobile and desktop, as a filter etc.?

![Screenshot from 2020-03-23 15-53-44](https://user-images.githubusercontent.com/41487496/77329763-bb79f580-6d1e-11ea-9ce2-e5b0fc5c197f.png)
![Screenshot from 2020-03-23 15-46-23](https://user-images.githubusercontent.com/41487496/77329775-bfa61300-6d1e-11ea-92ff-d6be1ccd20d5.png)

**Comment by mbaran-dvnt** [comment]
On mobile you have two versions:

1) On product page: which is simple square of color, with "checked' icon when selected

2) In filters for search and listings - and this is picked like in the design on the bottom of your request (sections size, color, material etc).

If it answers your question, we can close it:)
