### ISSUE TITLE
[Desktop/Mobile] Implement SfModal

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#94]
![image](https://user-images.githubusercontent.com/15185752/58155406-17459f00-7c74-11e9-9b0c-5dd29187d515.png)

Proposed API
```html
<SfModal cross="true/false">
<!-- default slot content -->
</SfModal>
```
cross is icon on top right corner and should just emit "close' event.

There should be no content except "x"

Should be closable with ESC press and a11y-friendly

Check SfSidebar for body-locking logic.

**Comment by lorenaramonda** [comment]
questions about this:
as the modal is a component a little different from the others as it should not be visible straight away but after some actions on the page or events (like loading) how should this be handled?
Should I develop the modal as it's visible and then provide some props to handle the visibility when the modal is used into the page?

yes 🤔 probably it's a silly question and the answer is already it (blowing in the wind) but, well, better sure than doubtful

**Comment by lorenaramonda** [comment]
Hello @filrak 
this is how the modal appears at this moment:

<img width="1456" alt="modal" src="https://user-images.githubusercontent.com/4409084/59159011-c3381880-8ac3-11e9-85f7-cea79f79b34c.png">

Questions!

1) should I handle a prop also for closing modal on click on the overlay?
2) should I handle the transition in opening the modal into the modal itself or this must be done/add when the modal is used? (into the storybook I add it before the <sfmodal> element, just to improve the presentation

Actually, I can't define where custom config must end in this "component-first" thing :P

**Comment by lorenaramonda** [comment]
maybe alos @leomp12 can help me here :P

**Comment by leomp12** [comment]
Hey @lorenaramonda ,
 
>     1. should I handle a prop also for closing modal on click on the overlay?

Yup, my suggestion is to have a prop to show or hide overlay and another prop to make modal persistent:

- `overlay`: whether to show the overlay, true by default;
- `persistent`: false by default, if true clicking outside will not dismiss the modal;

>     2. should I handle the transition in opening the modal into the modal itself or this must be done/add when the modal is used? (into the storybook I add it before the  element, just to improve the presentation

Imo you should handle transition into the modal itself by default, but you may also add a `transition` prop to receive custom transition name :)

**Comment by filrak** [comment]
@lorenaramonda @leomp12 Keep in mind that if we would like to use overlay it should be a separate component

**Comment by leomp12** [comment]
@filrak right, even so I think SfModal may have `overlay` and `persistent` props, to be easier to use

**Comment by lorenaramonda** [comment]
well, it is, as I'm testing it into storybook.
I'm gonna make a PR so it's easier for you to test, I don't know if the transitions are properly held 🤔 you will say
