### ISSUE TITLE
[FEATURE] Page size (items per page number) selection for pagination

### ISSUE THREAD

**Issue by Qrzy** [DivanteLtd/storefront-ui#941]
Sometimes one might want to give their users possibility to change page size on paginated list.
For now it's not clear whether this would be a part of pagination component or should be handled separately.

Current `SfPagination` component lacks such possibility and also example pages do not suggest any other components controlling this particular option.

I think two approaches could be considered here:
- building page size select as a part of `SfPagination` component
- suggesting usage of `SfSelect` (BTW: it shouts now that it doesn't accept number for now, but works with it :grin:) by placing it somewhere on the example pages

Some points of view:
- **beauty of the UI** - either solution can be perfectly designed to fit the styles
- **User eXperience** - depends on the usage of `SfPagination`; if it's used only on the bottom, it might be annoying to the user to scroll down just to change the page size if it's a part of pagination component - separate control item would be useful
- **Developer eXperience** - _One ring to bring them all and in the darkness bind them_ :ring: single component holding entire logic of one function is better in terms of DX

**Comment by pspaczek** [comment]
@mbaran-dvnt can you propose some solution for **page size** selector

**Comment by mbaran-dvnt** [comment]
It's done:) You can find two ways of using this component. In the top search filters bar and at the bottom along with pagination:)
