### ISSUE TITLE
Connect mobile and desktop previews

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#944]
Please connect desktop and mobile view. 
You can use something similar lika master or just put it side by side.

**Comment by mbaran-dvnt** [comment]
Done. I've put those views next to each other but to keep the logic flow in some of them, they are in some sections (cause sometimes action is shown on 2 desktop views, and 5 desktop views). Let me know if that's better solution for you:)

**Comment by pspaczek** [comment]
thanks @mbaran-dvnt this change is really useful for us 👍
