### ISSUE TITLE
Create stories for components that depend on framework grids

### ISSUE THREAD

**Issue by kokujin** [DivanteLtd/storefront-ui#95]
Can someone tell me how to add atoms/ organisms that might depend on a frameworks grid?(Bootstrap, Zurb Foundation e.t.c)

**Comment by filrak** [comment]
Can you be more precise?

**Comment by kokujin** [comment]
@filrak, yes I can. We have a few components that indirectly depend on a responsive grid. A simple example would be a date field that scales relative to the grid column it is in.

**Comment by filrak** [comment]
I still don't get how it connects to StorefrontUI.

Are you asking how our components behave when used in grid?

If so - as long as it's flexbox-based it should work out of the box without any problems. We don't have any grid in StorefrontUI (we are completely agnostic in this matter so it's usable with bootstrap flexboxgrid etc0)and component are adjusting to their container and/or width/height of themselves.

https://github.com/DivanteLtd/storefront-ui/blob/master/src/examples/pages/category/Category.vue - example for ref
