### ISSUE TITLE
[FEATURE]Product listing - one product in one row on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/storefront-ui#951]
**Describe the solution you'd considered**
On category and subcategory pages make product listing with one product in one row - description of the product is next to the picture (horizontal product listing) as below:
<img width="189" alt="HorizontalListing" src="https://user-images.githubusercontent.com/57936972/74728874-cf27cd00-5243-11ea-9680-e75e9a9b01c5.png">

Make possible for user to switch from default product listing to horizontal product listing.

**Acceptance criteria**

- [ ]  there is one product in one row with description next to the picture on product listing on mobile
- [ ] user can switch from default product listing to horizontal product listing

**Comment by akrajna** [comment]
related link https://github.com/DivanteLtd/shopware-pwa/issues/405

**Comment by pspaczek** [comment]
@mbaran-dvnt how we can change sorting now? 
![Zrzut ekranu 2020-04-16 o 15 20 00](https://user-images.githubusercontent.com/12138170/79460898-be9e9380-7ff5-11ea-9789-ee5ad2b8ff78.png)

**Comment by mbaran-dvnt** [comment]
![Zrzut ekranu 2020-04-19 o 22 18 47](https://user-images.githubusercontent.com/62093203/79698823-be1f2a80-828b-11ea-9466-84aa1be8b056.png)
Sorting was moved to Filters. I don't remember with who, but we had a big discussion on how to solve it and it seemed like the best solution.

**Comment by martaradziszewska** [comment]
@pspaczek issue with sort by on filters is reported in #1062, I am closing this according to merged #1041

**Comment by akrajna** [comment]
It is not working on https://shopware-pwa.storefrontcloud.io/ . Sort by filters is not implemented yet and switch between grid view and list view needs to be done.
Switch between grid view and list view will be done in this issue #655

**Comment by martaradziszewska** [comment]
@akrajna this should be implemented by Shopware team and you have issues for this new features https://github.com/DivanteLtd/shopware-pwa/issues/658, https://github.com/DivanteLtd/shopware-pwa/issues/657, https://github.com/DivanteLtd/shopware-pwa/issues/655
In our story with page Category there is an example of switching between rows.
