### ISSUE TITLE
[FEATURE]Offline mode- add info about offline mode instead of 500 error

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/storefront-ui#952]
**Describe how this feature will help us improve**
Helps user navigate trough the site during offline mode

**Describe the solution you'd considered**

Notification bar about being offline is displayed when user is in offline mode 'You are offline. Some features might not be available.' e.g.:

![Offline](https://user-images.githubusercontent.com/57936972/76304753-33c6cc80-62c4-11ea-8f70-839ab6e15060.png)
If any page is unavailable instead of 500 error page, the following information appears: 'The product, category or CMS page is not available in Offline mode. Redirecting to Home.'

![OfflineMode](https://user-images.githubusercontent.com/57936972/76305028-b18ad800-62c4-11ea-8275-221d9b943a99.png)

**Here is an interesting article on how to use $nuxt.isOffline for this**
 https://dev.to/debs_obrien/show-a-message-when-your-user-is-offline-with-nuxt-isoffline-1157

**Acceptance criteria**

- [ ]  Notification bar about being offline is displayed all the time when user is in offline mode 
- [ ] there is no 500 error page 
- [ ] If any page is unavailable  the following information appears: 'The product, category or CMS page is not available in Offline mode. Redirecting to Home.' and user is redirected to Home page.

Related link https://github.com/DivanteLtd/shopware-pwa/issues/476

**Comment by EduardDopler** [comment]
@patzick Correct me if I'm wrong, but this is isn't a SFUI feature, is it? Feel free to close it then. I see there is already a linked issue in shopware-pwa?

**Comment by patzick** [comment]
@EduardDopler, you're absolutely right! :)
For offline notification we can use: https://storybook.storefrontui.io/?path=/story/molecules-notification--common
Closing this one
