### ISSUE TITLE
[BUG] adjust SfPagination to the design

### ISSUE THREAD

**Issue by justyna-13** [DivanteLtd/storefront-ui#969]
**Describe the bug**
SfPagination differs from our new design. We need to add an option with one arrow on the right side

**Screenshots**
![Zrzut ekranu z 2020-03-31 15-19-36](https://user-images.githubusercontent.com/46591755/78030875-120cb280-7363-11ea-9c13-7b79cf07b177.png)

**Comment by pspaczek** [comment]
#1151 fixed
