### ISSUE TITLE
[FEATURE]Analysis of search with menu at the bottom of the page on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/storefront-ui#975]
**Describe how this feature will help us improve**
Analysis of the possibility of adding 'search' at the bottom of the screen on mobile devices is needed. So that the user does not have to take their hands off the screen. 

**Describe the solution you'd considered**
Consider adding search together with menu as the icon may suggest user such use.

<img width="154" alt="2020-04-01_10h37_06" src="https://user-images.githubusercontent.com/57936972/78134253-1ea31080-7420-11ea-99f0-15d5b0c3e0dc.png">

**Comment by mbaran-dvnt** [comment]
I've added alternative buttons set on the left to the style guide. My idea is to replace old button with this set, much better imo:)

**Comment by mbaran-dvnt** [comment]
I've added search to menu view on mobile, so I think it can solve it. as icon on to bottom nav suggest menu and search.

**Comment by akrajna** [comment]
It is done and should look as below:
![image](https://user-images.githubusercontent.com/57936972/82017319-2e4e7f80-9683-11ea-9254-a49abac53b63.png)
