### ISSUE TITLE
[FEATURE] Missing price cases/variant

### ISSUE THREAD

**Issue by EugeneHlushko** [DivanteLtd/storefront-ui#994]
**Describe how this feature will help us improve**
It is common for product card in category/carousels or other places to state different price variations of the options product has.
- From 26$
- From 26$ ~RRP 30$~
- 26$ RRP 30$
- 26$ (Sale color) ~28$~ 

**Is your proposal related to a problem?**
The issue is that we'd have to create a custom price component

**Describe the solution you'd considered**
- We should have an ability to display `from` tag before price for products with variants that have different prices.
- We should be able to display rrp price crossed or not crossed (crossing RRP price in different countries can be illegal afaik)

**Additional context**
This is available in most ecoms, should be in our great sfui

**Comment by pspaczek** [comment]
@EugeneHlushko you can use 'From' now, just put 'From $26' to specialPrice or regularPrice props. Color and line-through you can change by CSS variables and override it at global.scss file. Now we should add a few improvements to the SfPrice component but finally, it should work.
